Baptism
=======

It's very easy for our minds to get fixated on a particular image for something.
This image can stick with us and continue to influence our thinking in ways we are not even aware of.
When we think of baptism, for instance, what is usually the first thing that pops into mind?
Perhaps something like this: https://www.google.ca/search?q=baptism&tbm=isch.

Even if we realize there is much more to baptism than this, it is very hard to shake that image.
But what if when we thought of baptism, this was the first image to come to mind: https://www.google.ca/search?q=cross&tbm=isch.
How would this change our lives and impact our faith?

Baptism isn't a cut and dried matter.
It's a multi-facited concept, and the word often carries different meaning depending on the context.
For example, did you know that:

- The greatest teacher on baptism in the New Testament once said "Christ sent me not to baptize" (Paul in 1 Cor 1:17)?
- An entire nation was baptized in the OT without getting wet (Paul speaking of Moses in 1 Cor 10:2)?
- Christ actually had another significant baptism after he was baptized by John? (Jesus in Luke 12:50)

Christ actually had three baptisms: water purification, spirit anointing, and the cross.
Christianity has largely fixated on the first one even though it is the last one that really is the biggest deal.

Baptism: A Definition
---------------------

If baptism can be used in such different ways, is it possible to arrive at some common definition of the word that can actually help us understand all its varied uses?
We need to explore the word a bit more closely to find out.

The Greek word for baptism is βαπτίζω (baptizo).
Vine's has this to say about baptize.

Vine's Expository Dictionary of New Testament Words
___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

Two words: "to dip" vs "to baptize".

So while baptize can be used to describe dipping something into water, it means far more than that.
It signifies a permanent change, not just a temporary immersion.
There is no better illustration of this than pickles!

https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?strongs=G911&t=KJV
_________
Not to be confused with 907, baptizo. The clearest example that shows the
meaning of baptizo is a text from the Greek poet and physician Nicander, who
lived about 200 B.C. It is a recipe for making pickles and is helpful because
it uses both words. Nicander says that in order to make a pickle, the vegetable
should first be 'dipped' (bapto) into boiling water and then 'baptised'
(baptizo) in the vinegar solution. Both verbs concern the immersing of
vegetables in a solution. But the first is temporary. The second, the act of
baptising the vegetable, produces a permanent change.
_________

Often in evangelical Christian circles, baptism is presented as something that is optional but is encouraged as a way to follow Christ in obedience.
Baptism is not considered to produce any change in the individual, but it can perhaps be a faith building experience.
For example, believers questioning thier own faith who have not been baptized are often encouraged to get baptized as a way to make a testament of thier faith and overcome their doubts.
The risk is that we turn baptism into something that is more about us and our actions than about Christ.
But is baptism ever really presented as something optional in Scripture? And does baptism actually change people?

Being baptized into something means to be so affected that there is a lasting change that takes place.
Often, the emphasis is placed on the act rather than the change, or on the symbolism of the act rathen than the act itself.
How would we understand baptism if we focus on the change brought about by it?
The key is understanding that there are different baptisms in Scripture.
And the change brought about by each of those baptisms is different.

How does washing fit into this in Greek meaning? Is this reading too much into baptize? https://goddidntsaythat.com/2010/08/24/q-and-a-the-original-baptism/

Look at the different themes associated with baptism in scripture (e.g. deliverance, judgement, cleansing, healing).


Baptism in Water
----------------

When we think of water baptism today (particularly immersion in water), it's tempting to think that this is something that was instituted by John the Baptist.
After all, this is what he was doing at the banks of the Jordar river.
And wasn't this something of a sensation back in his day that created quite a stir among the religious leaders?

What was so special or unique about what John was doing?
It actually wasn't the fact that he was baptizing people in water.
Baptism in water was present in the Old Testament.
It was heavly associated with the tabernacle and the duties of the priests.

In Hebrews, we read this about the tabernacle service of the Old Tesament.

Heb 9:9-10 KJV
______________
[The Tabernacle] Which [was] a figure for the time then present, in which were offered both gifts and sacrifices, that could not make him that did the service perfect, as pertaining to the conscience;
[Which stood] only in meats and drinks, and divers washings, and carnal ordinances, imposed [on them] until the time of reformation.
______________

The word translated "washings" is the Greek word for baptism.
So we could quite correctly say that "diverse baptisms" were a significant part of the ceremonial law associated with the tabernacle.

If we look at baptism or washing in water as required for Priests under the Old Covenant, it fell under two major categories:
the initiation or consecration of the priest and the ongoing service of the priest in the tabernacle.

The very first initiation of a priest was perfomed by Moses. We read about it in Exodus.

Exo 29:4 KJV
_____________
And Aaron and his sons thou shalt bring unto the door of the tabernacle of the congregation, and shalt wash them with water.
_____________

Here it is Moses that washes Aaron and his sons as he prepares them as priests.
He then goes on to clothe them with new clothes and anoint them with oil as he prepares them for their office as priests.
The word wash in the Hebrew is *rachats*, and it is used numerious times throughout the Old Testament in the descriptions of priestly duties.
It can mean taking a whole body bath or just washing your hands. But it is a required form of purification under the Law.
But washing in water was not something that a priest experienced once; it was an essential, ongoing part of his duties.

Exo 30:20 KJV
_____________
When they go into the tabernacle of the congregation, they shall wash[H7364] with water, that they die not; or when they come near to the altar to minister, to burn offering made by fire unto the LORD:
_____________

This was very serious stuff. The consequence of not washing before coming near the altar was death.
The difference here is that the priest had to wash himself in his day to day service.
In fact, it is possible that the only priests that were baptized by someone else (at least as recorded in the Old Testament) were Aaron and his sons.

So the significance of what John the Baptist was doing is found here.
People were getting baptized by him rather than washing themselves.
The religious leaders were puzzled by this since this was not the norm.
In fact, they new that, after Moses, the only two others that might do this are Elijah and the Christ.

TODO: add reference here.

The significance of John's baptism can be really appreciated in light of God's purpose to make the nation of Israel a kingdom of priests.
In other words, the priestly tribe of the Old Covenant was a picture of what God wanted to make the entire Israel of the New Covenant.
John is announcing this and preparing for this.

So the baptism of Christ can be seen in light of Him fulfiling the requirements of a priest under the law.
In Mat 3:15, when John almost refuses to baptize Him, Jesus says that He was baptized to "fulfill all righteousness".

Mat 3:14-15 KJV
_______________
But John forbad him, saying, I have need to be baptized of thee, and comest thou to me?
And Jesus answering said unto him, Suffer [it to be so] now: for thus it becometh us to fulfil all righteousness. Then he suffered him.
_______________

But John's baptism of Jesus also served another purpose: it was how the Messiah was to be identified to the nation.

Jhn 1:30-31 KJV
_______________
This is he of whom I said, After me cometh a man which is preferred before me: for he was before me.
And I knew him not: but that he should be made manifest to Israel, therefore am I come baptizing with water.
_______________

So washing in water is not unique or new with John the Baptist.
But the location where he was doing this was special.
This was no ordinary washing taking place in the temple.
It was taking place far away from the temple near the Jordan River.
This was a location deeply assoiciated with the history of Israel.

https://en.wikipedia.org/wiki/Bethabara

This is potentially the location where Elija was taken up into heaven.
John the baptist was seen as ministring as Elijah (Mat 17:10-12).
So the very location where John was carrying out his ministry was potentially exactly the same location where Elija was last seen so many years before.

But there is another important connection to Bethabara in Israel's history.
This location is likely very close to the historical city of Jerico.
And Jerico is the historical location where Joshua and Caleb led the children of Israel out of the wilderness, across the Jordan river, and into the promised land.

Several key things stand out about this Jordan river crossing (Joshua 3-4):

- Joshua instructed Israel to sanctify themselves (e.g. wash up) because God was about to do wonders
- God used this to exhalt Joshua in the sight of Israel, much like Christ was going to be exhalted.
- Joshua chose 12 men to be witnesses for Israel.
- The 12 men carried stones out of the bottom of the river and placed them on the bank of the river as a memorial of the day.

John is baptizing in the Jordan river near the place where Joshua crossed over with the children of Israel many years before.
And you have John and Jesus as key figures now much like Caleb and Joshua were so many years later.

Washing in water is intimately connected to the Old Covenant.
What's different about the baptism of John is the fact that someone else (i.e. John) did the washing or pouring of water.
It is also very significant that John was doing this near the banks of the Jordan river.

While baptism in water can be symbolic of the death, burial, and resurrection of Christ, that wasn't the primary significant of John's baptism.
And it wasn't likely what any of those baptized by John were thinking about as they were getting baptized.
In fact, they really had no idea what was going to happen to Christ in just a few short years.
The washing in water represented the purification and repentance of the nation of Israel.
There is no evidence that this changed after the resurrection of Christ (Acts 2:38).
I believe Peter is carrying on the baptism of John here with the added baptism of the Spirit.


Baptism in Spirit
-----------------

John clearly says that one is coming who will baptize with Holy Spirit fire (Mat 3:11, Luk 3:16).

For priests, three that always goes together:

- Washing in Water (symbolic of purification)
- Anointing with Oil (symbolic of spirit anointing)
- Changing Clothes (symbolic of resurrected body?)

The oil is a symbol of Holy Spirit anointing.
So with the baptism of Jesus, we see the washing in water first followed by the anointing with the Holy Spirit.
The water and oil are closely linked with Priestly service. Much like water baptism and spirit baptism are for Israel.

Think about what happened when Christ was baptized by John.
The dove and voice from heaven indicated the Spirit anointing of the Christ.
The washing in water was present with faith, and the sign followed after.

In Matthew 3 and Lunk 3, baptize "with holy ghost and with fire" could be translated "with holy ghost even fire" based on the meanig of kai.
The Greek word here for "and" can be used to amplify something, meaning "even" as an example of something that amplifies.
Thinking about what happened at Penticost, the tongues of fire were visibile above the disciples as they were anointed with this Holy Spirit (Acts 2:3).
So it makes sense that this fire is associated with the Holy Spirit.

The anointing of the Spirit is a significant piece of the New Covenant.
We read about the purpose of this is Isa 61.

Isa 61:1-2a KJV
___________
The Spirit of the Lord GOD [is] upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to [them that are] bound;
To proclaim the acceptable year of the LORD ...
___________

This is the very verse Jesus read as He began His ministry.
He is first baptized by John, then anointed in the Spirit.
He then declares the purpose of His ministry.

Important things to highlight from Isa 61:

- Zion
- Rebuild cities
- Priests of the Lord, Ministers of God
- Receive Your Land
- Everybody that sees them will acknowledge they are blessed by Lord

Addresing the people gathered in Acts chapter 2, Peter clearly links Penticost with Joel chapter 2 (Acts 2:16-19).
Joel is speaking of a time when God will pour out his spirit on that nation.

Joe 2:28-29 KJV
_______________
And it shall come to pass afterward, [that] I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see visions:
And also upon the servants and upon the handmaids in those days will I pour out my spirit.
_______________

And just a few verses down, Joel specifically mentions Zion (multiple times) and Jerusalem in close association with this.

To understand water baptism and spirit baptism, we have to understand the Old Testament.
And if we truly want to understnad the Great Commission, we need to understand it in light of how Christ defined His ministry.
In the Great Commission in Mark 16, salvation is associated with baptism

Mar 16:15-16 KJV]
________________
And he said unto them, Go ye into all the world, and preach the gospel to every creature.
He that believeth and is baptized shall be saved; but he that believeth not shall be damned.
________________

But unfortunately what is almost always overlooked are the two verse that follows this.

Mar 16:17-18 KJV
________________
And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;
They shall take up serpents; and if they drink any deadly thing, it shall not hurt them; they shall lay hands on the sick, and they shall recover.
________________

Was water baptism a part of this? Yes, I think so!
But what closely followed this was an anointing of the Spirit. This anointing was possible only by faith.
And there were powerful, irrefutable signs that went with this anointing that we can't ignore.
And the point of the Spirit anointing was to prepare and equip Israel to fulfill God's purpose of a Kingdom of Priests.
These two baptisms go together much in the same what that a priest had to both wash in water and get anointed in oil in preparation for his work.


Baptism in Death
----------------

When we think about the word baptize, the cross is not necessarily the first association that jumps to mind.
However, baptism into the death of Christ is a central message to Paul's teaching.
Paul makes it clear that to be baptized into Christ is really to be baptized into His death.
A clear pattern in Paul's teaching is that when he mentions baptism, it is in close relationship with the cross.
The two words usually show up close to each other in his writing.

Rom 6:3-6 KJV
___________
Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?
Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been planted together in the likeness of his death, we shall be also [in the likeness] of [his] resurrection:
Knowing this, that our old man is crucified with [him], that the body of sin might be destroyed, that henceforth we should not serve sin.
___________

How do we know this baptism isn't washing in water? Who does this baptism?
See the circumcision and baptism in Col 2:12.

[Col 2:10-12 KJV]
_________________
And ye are complete in him, which is the head of all principality and power:
In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:
Buried with him in baptism, wherein also ye are risen with [him] through the faith of the operation of God, who hath raised him from the dead.
_________________

The circumcision done here is made without hands. It is the circumcision of Christ.
It makes total sense that the baptism done here is also without hands. In fact, it is the "operation of God".
Only God can do this baptism. And it was accomplished at the cross.
This baptism is done (past tense), but it is entered into by faith.
The baptism Paul is speaking of here is the same baptism Paul is speaking of in Rom 6.

Notice how the words baptism and cross both pop out in Rom 6 and Col 2.

Baptism and the cross are like flip sides of the coin.
Baptism into the death of Christ is not done by us and can only be done by God.
But embracing the message of the cross in our daily lives is something that is done by us.
This is evidence in the present to us and to others that our baptism is in fact real.
The cross points back to this but also symbolizes the active change that is taking place here and now in our lives to reflect this fact.
The cross symbolizes both a completed reality and an present change and a future change.
The future change is when the old creation is permanently replaced by the new.
The present change in our lives today is the work of the Spirit (the Word) filling us and changing us.

The structure of Galatians centers around baptism into Christ and the Cross:

- A: Gal 2:20: Paul crucified with Christ. Christ living in him.
- B: Gal 3:1: The Galatians had a clear example of Christ crucified.
- C: Gal 3:27-28: Baptized into Christ, distinction gone, all one in Christ Jesus
- B: Gal 5:24: They that are Christ's have crucified the flesh
- A: Gal 6:14: The world has crucified to Paul. The New Creation.

How was it that the Galatians has a clear example of Christ crucified set before them?
This was through the preaching and life of Paul. Because he was baptized into the death of Christ and had embraced the cross.
Paul made this evident through his life because this had become Paul's identity.

Did you ever realize that the central theme of the book of 1 Corinthians is baptism?
While there are a number of practical issues Paul is trying to deal with and correct in the church,
at the root of these issues lies a lack of understanding and failure to fully embrace baptism into the death of Christ.

A brief outline of 1 Corinthians might be summarized as this:

- Ch 1-2: Introduction, divisions created with water baptism, Paul sent not to baptize but preach the cross: the power and wisdom of God
- Ch 3-9: Confronting and dealing with issues in the Church
- Ch 10: Example of Baptism into Moses, eating and drinking together in the wilderness, but dying due to disobedience.
  This was a dry baptism, much like being baptized into the death of Christ. Even though the baptism into Moses was a done deal,
  many still died in the wilderness due to disobedience.
- Ch 11-12: Communion and its consequences, the spirit gifts, baptized into one body
- Ch 13-14: Follow after love: to have the spirit anointing without this is nothing
- Ch 15-16: Death, burial, resurrection of Christ (the cross), Conclusion

Buried inside of 1 Cor 15 is one of those verses that has puzzled people from time to time.

[1Co 15:29 KJV] 29 Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?

Paul is asking: why would someone be baptized "for the dead" if there is no resurrection of the dead.
What does being baptized "for the dead" mean?
The phrase in the greek can mean over as in position or also in place of.

Commonly, this verse is understood as a reference to a practice of either baptizing the dead or getting baptized in the place of a dead person.
But it is a bit strange to assume this given there is no hint of this anywhere else in this book.
Why would Paul randomly refer to a practice not found anywhere else in the Bible when he is trying to defend the truth of the resurrection?

It makes much more sense here if Paul is actually speaking of the same thing in v29 - v32.
Paul mentions that he fought with wild beasts a few verses down.
The criminals and Christians were at that time thrown before wild beasts (research more).
How many died in these very area floors for their faith?
Paul could be referring to those that were baptized over the same place as these dead.
This lifestyle of dying daily was the outcome of Paul embracing the message of the cross.

To "suffer the loss of all things" for Christ makes no sense if there is resurrection.
It would be pure foolishness.

Its not the physical act of dying that is central to the cross in practical application.
Paul says that if you give your body to be burned but don't have love, you are nothing.
It is getting to the point of being able to willingly let go of everything.
Did Christ die because He was nailed to a cross and couldn't escape?
No, He died because He willingly gave Himeself up.

The miracles performed by Jesus are not the ultimate expression of the power and the wisdom of God.
The cross is the expression of the power and the wisdom of God.
It is the ultimate expression of the defining characteristic of the new creation.

Paul was so changed by the cross that it had become part of his very identity.
When he preached the cross, he also lived out the power and wisdom of God in his very life.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

Baptism into the death of Christ is an accomplished fact that is received by faith.
And it becomes an evidence to others and to ourselves when we embrace the significance of the cross daily in our lives.

How critical it is to understand the Great Commission in light of something else Christ said:

Mar 8:34 KJV
____________
And when he had called the people [unto him] with his disciples also, he said unto them, Whosoever will come after me, let him deny himself, and take up his cross, and follow me.
____________

While the Great Commission from Mark chapter 16 seems to get a lot of attention today, this message of the cross is truly core to being a follower of Christ.


The One Baptism
---------------

So understanding baptism in Scripture requires that we distinguish between water, spirit, and death.
Each of these baptism has an underlying theme of purification and preparation for service.
Water is associated with the Old Covenant.
Spirit is associated with the New Covenant.
Death and the cross are associated with the New Creation.

There are multiple baptisms, not just one.
But then, when summarizing the unity of the Spirit in Ephesians chapter 4, Paul says this:

Eph 4:4-6 KJV
_____________
[There is] one body, and one Spirit, even as ye are called in one hope of your calling;
One Lord, one faith, one baptism,
One God and Father of all, who [is] above all, and through all, and in you all.
_____________

All purposes in the New Creation start with the baptism into the death of Christ.
The New Creation reveals the manifold wisdom of God (Eph 3:10).
Just because all are One in Christ does not mean all have the *same purpose* in Christ.

It is impossible to be a part of the New Creation without baptism into Christ.
Christ is the Head of this creation much like Adam was the head of the old.
Baptism into Christ is like a rite of passage for the new creation.
Is it possible to be a part of the New Creation without washing in water and having a spirit anointing?

|========
| Old Creation      | New Creation
| Temporary         | Eternal
| Shadows           | Reality
| Adam              | Christ
| Old Anthropos     | New Anthropos
| Adam & Eve        | Head & Body
| Israel & Nations  | Bride & Husband
| Flesh             | Spirit
| Law               | Promise
| Death             | Life
|========

Both John and Paul had special revelations associated with heaven and with the church in the new creation.
John calls the church the "bride". Paul call the church the "husband".
The old creation is at best a picture of what is coming.

The cross separates the old creation from the new creation.
Without baptism into the death of Christ, it is not possible to have any part of the new creation.
This baptism is foundational to the good news of the new creation. And it is a baptism that is done by God, not by human hands (Col 2).
If the circumcision done in Col 2 is without human hands, isn't it reasonable to understand that the baptism is also done without human hands?
If it was possible for believers to experience baptism in the Spirit without washing in water, is it so surprising if we can be baptized into the death of Christ without washing in water?
In Col, both the circumcision and baptism are accomplished by God, not human hands (Col 2:10-12).
If we have been baptized into the death of Christ, why would we keep returning to the pre-cross, old creation ways of thinking. See Col 2 and Gal 3.
What is the relationship of this circumcision to baptism and the cross here?

When we are baptized into the death of Christ, we are so impacted by the message of the cross that it changes us.
Even while we are still a part of the old creation today, we have been touched by the New Creation in such a way that it has permanently changed us.
We have been baptized into Christ and He is now a permanent part of us.
The cross is how the old creation is touched, infused, and changed by the new.

The distinctions and divisions of the old creation simply do not translate into the new creation.
Fleshly distinctions and differences are part of the old creation and end at the cross.
Your gender or race does not determine where you fit within the new creation in Christ.
They are at best, shadows or symbols of the corresponding reality in the new creation.
It is the calling of God that determines where you fit in the New Creation.

Realize that Circumcision and Baptism were required for a Gentile under the Old Covenant.
Both of these requirements reach an end in Colossians.

What is the defining characteristic of the New Creation? Love.
How do we remember and honour the work of Christ in our lives today?
How do we show evidence of this to others?
Is it through an outward washing ceremony? Or is it by being shaped by the cross in our daily lives?

Baptism and the cross are like opposite sides of the coin.
All of the reasons people feel the need to be baptized in water can be answered in the cross.


Baptism: References for Study
=============================

Christ as a Teacher on Baptism
------------------------------

A concordance of Christ's teaching on baptism:

- TODO

Did Jesus ever speak explicitly of baptism in water?
Did Jesus ever baptize anyone?
John indicates that Jesus was going to baptize with spirit (holy spirit fire) (Luke 3:16).

Peter as a teacher on Baptism
-----------------------------

A concordance of Peter's teaching on baptism:

- [1Pe 3:21 KJV] 21 The like figure whereunto [even] baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ:
- TODO

Peter makes the comment that "baptism doth also now save us", but he is very clear that this is not the washing away of filth of the flesh.
He clearly relates this "baptism" to the resurrection of Christ in that same verse.
This cannot be mere water baptism.
And just a few verses earlier, he speaks of Christ being put to death in the flesh but quickened in the Spirit.
So Peter aligns salvation with the death, burial, and resurrection of Christ.

Thinking of Noah and his family, it was actually faith that saved them.
Without the ark, there would be no salvation.
And it took faith in God's word to build the ark.

This baptism may be more symbolic of the transition from the old creation to the new creation than it is of water baptism itself as a cleansing ritiual.
Noah and his family stepped into the ark from the old creation and stepped off of the ark into the new creation.
While not the focus here, a more detailed study of ark throughout scripture would likely yield much very interesting insight.

Paul as a teacher on Baptism
----------------------------

A concordance of Paul's teaching on baptism:

- TODO


- The Crossing of the Red Sea (1 Cor 10:2): Moses and Israel didn't get wet
- References to carnal ordinances (Heb 9:10)

Paul speaks of baptism more than any other author when we consider all three.

Baptism in the Septuagint
-------------------------

See the article on "Baptism" in Alphabetical Analysis (C.H. Welch).
But some key passages are illustrated here.

The word baptizo is found in the following passages:

- 2 Kings 5:14
- Isa 21:4

The word bapto is found in the following passages:

- Job 9:31
- Dan 4:33, 5:21

Additional References for Reading
---------------------------------

- The Mikvah

    - http://www.chabad.org/theJewishWoman/article_cdo/aid/1541/jewish/The-Mikvah.htm
    - http://free.messianicbible.com/feature/mikvah-baptism-the-connection-between-immersion-conversion-and-being-born-again/
    - https://en.wikipedia.org/wiki/Ritual_washing_in_Judaism

- An excellent reference on baptism, washing, sprinking throughout the Bible: http://www.fivesolas.com/sprinkle.htm

- Concordance on Hebrew word for wash: https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?Strongs=H7364&t=KJV
