Baptism: References for Study
=============================

1. Introduction: Question
2. John the Baptist: John manifested the Sin Offering, Who is the Great High Priest. John baptized the last Great High Priest like Moses baptized the first Great High Priest.
3. The Ordination Christ: The 3 parts of OT ordination. Water Baptism fulfilled the Old Priesthood, Spirit Baptism introduced the New Priesthood.
4. The Work of Christ: The Baptism that was His work as Priest. Others joined Him as martyr.
5. Baptize: The Word. Baptize implies change.
6. Baptized into Christ: Paul focuses on righteousness by faith. Baptism and the Cross are flip sides of the same coin. Baptism into His death is performed by God. The Cross is the evidence of our baptism into the death of Christ.
7. One Baptism: New Creation. Can you be a part of the new creation without being a Priest?


Christ as a Teacher on Baptism
------------------------------

Christ challenged the Pharisees with their views on baptism by not baptizing before dinner.

[Luk 11:38 KJV] 38 And when the Pharisee saw [it], he marvelled that he had[G907] not first washed[G907] before dinner.

A concordance of Christ's teaching on baptism:

- TODO

Christ echoes this transition from old to new when he spoke about inheriting the kingdom

[Jhn 3:3, 5 KJV] 3 Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God. ... 5 Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and [of] the Spirit, he cannot enter into the kingdom of God.

The teaching of Christ on baptism seems to center on two things:

1. Great Commission
2. Baptism into death

Did Jesus ever speak explicitly of baptism in water?
Did Jesus ever baptize anyone?
John indicates that Jesus was going to baptize with spirit (holy spirit fire) (Luke 3:16).

Isa 61:1-2a KJV
___________
The Spirit of the Lord GOD [is] upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to [them that are] bound;
To proclaim the acceptable year of the LORD ...
___________



Peter as a teacher on Baptism
-----------------------------

A concordance of Peter's teaching on baptism:

- [1Pe 3:21 KJV] 21 The like figure whereunto [even] baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ:
- TODO

Peter makes the comment that "baptism doth also now save us", but he is very clear that this is not the washing away of filth of the flesh.
He clearly relates this "baptism" to the resurrection of Christ in that same verse.
This cannot be mere water baptism.
And just a few verses earlier, he speaks of Christ being put to death in the flesh but quickened in the Spirit.
So Peter aligns salvation with the death, burial, and resurrection of Christ.

Thinking of Noah and his family, it was actually faith that saved them.
Without the ark, there would be no salvation.
And it took faith in God's word to build the ark.

This baptism may be more symbolic of the transition from the old creation to the new creation than it is of water baptism itself as a cleansing ritiual.
Noah and his family stepped into the ark from the old creation and stepped off of the ark into the new creation.
While not the focus here, a more detailed study of ark throughout scripture would likely yield much very interesting insight.

Paul as a teacher on Baptism
----------------------------

A concordance of Paul's teaching on baptism:

- TODO

Paul discusses this in the context of inheriting the kingdom

[1Co 15:48-54 KJV] 48 As [is] the earthy, such [are] they also that are earthy: and as [is] the heavenly, such [are] they also that are heavenly. 49 And as we have borne the image of the earthy, we shall also bear the image of the heavenly. 50 Now this I say, brethren, that flesh and blood cannot inherit the kingdom of God; neither doth corruption inherit incorruption. 51 Behold, I shew you a mystery; We shall not all sleep, but we shall all be changed, 52 In a moment, in the twinkling of an eye, at the last trump: for the trumpet shall sound, and the dead shall be raised incorruptible, and we shall be changed. 53 For this corruptible must put on incorruption, and this mortal [must] put on immortality. 54 So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality, then shall be brought to pass the saying that is written, Death is swallowed up in victory.

- The Crossing of the Red Sea (1 Cor 10:2): Moses and Israel didn't get wet
- References to carnal ordinances (Heb 9:10)

Paul speaks of baptism more than any other author when we consider all three.

Paul explains what embracing the cross looks like in a somewhat puzzling passage in 1 Cor.

1Co 15:29 KJV
____________
Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?
____________

Paul is asking: why would someone be baptized "for the dead" if there is no resurrection of the dead.
What does being baptized "for the dead" mean?
The phrase in the Greek can mean over as in position or also in place of.

Commonly, this verse is understood as a reference to a practice of either baptizing the dead or getting baptized in the place of a dead person.
But it is a bit strange to assume this given there is no hint of this anywhere else in this book.
Why would Paul randomly refer to a practice not found anywhere else in the Bible when he is trying to defend the truth of the resurrection?
It makes much more sense here if Paul is actually speaking of the same thing in v29 - v32.
Paul mentions that he fought with wild beasts a few verses down.
The criminals and Christians were at that time thrown before wild beasts (research more).
How many died in these very area floors for their faith?
Paul could be referring to those that were baptized over the same place as these dead.
This lifestyle of dying daily was the outcome of Paul embracing the message of the cross.
This word "for" or "over" is the Greek word "hyper" and can mean "above" or "beyond".
I think Paul is speaking of being baptized beyond death: "I die daily".

Baptism in the Septuagint
-------------------------

See the article on "Baptism" in Alphabetical Analysis (C.H. Welch).
But some key passages are illustrated here.

The word baptizo is found in the following passages:

- 2 Kings 5:14
- Isa 21:4

The word bapto is found in the following passages:

- Job 9:31
- Dan 4:33, 5:21

Joshua and the Jordan River
---------------------------

there is another important connection to Bethabara in Israel's history.
This location is likely very close to the historical city of Jerico.
And Jerico is the historical location where Joshua and Caleb led the children of Israel out of the wilderness, across the Jordan river, and into the promised land.

Several key things stand out about this Jordan river crossing (Joshua 3-4):

- Joshua instructed Israel to sanctify themselves (e.g. wash up) because God was about to do wonders
- God used this to exhalt Joshua in the sight of Israel, much like Christ was going to be exhalted.
- Joshua chose 12 men to be witnesses for Israel.
- The 12 men carried stones out of the bottom of the river and placed them on the bank of the river as a memorial of the day.

John is baptizing in the Jordan river near the place where Joshua crossed over with the children of Israel many years before.
And you have John and Jesus as key figures now much like Caleb and Joshua were so many years later.

Additional References for Reading
---------------------------------

- The Mikvah

    - http://www.chabad.org/theJewishWoman/article_cdo/aid/1541/jewish/The-Mikvah.htm
    - http://free.messianicbible.com/feature/mikvah-baptism-the-connection-between-immersion-conversion-and-being-born-again/
    - https://en.wikipedia.org/wiki/Ritual_washing_in_Judaism

- An excellent reference on baptism, washing, sprinking throughout the Bible: http://www.fivesolas.com/sprinkle.htm

- Concordance on Hebrew word for wash: https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?Strongs=H7364&t=KJV
