Baptism
=======


Baptism: A Definition
---------------------

The Greek word for baptism is βαπτίζω (baptizo). Vine's has this to say about baptize.

Vine's Expository Dictionary of New Testament Words
___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

Two words: "to dip" vs "to baptize".

So while baptize can be used to describe dipping something into water, it means far more than that.
It signifies a permanent change, not just a temporary immersion.
There is no better illustration of this than pickles!

https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?strongs=G911&t=KJV
_________
Not to be confused with 907, baptizo. The clearest example that shows the
meaning of baptizo is a text from the Greek poet and physician Nicander, who
lived about 200 B.C. It is a recipe for making pickles and is helpful because
it uses both words. Nicander says that in order to make a pickle, the vegetable
should first be 'dipped' (bapto) into boiling water and then 'baptised'
(baptizo) in the vinegar solution. Both verbs concern the immersing of
vegetables in a solution. But the first is temporary. The second, the act of
baptising the vegetable, produces a permanent change.
_________

How does washing fit into this in Greek meaning? Is this reading too much into baptize? https://goddidntsaythat.com/2010/08/24/q-and-a-the-original-baptism/


Christ as a Teacher on Baptism
------------------------------

Christ illustrates with three baptisms in His earthly ministry:

- Water
- Spirit
- Death

The Great Commission
~~~~~~~~~~~~~~~~~~~~

Mark 16:16: This verse cannot be separated from the particular Good News the disciples were proclaiming and the confirmation
that followed belief in this good news (Mark 16:17-18). Furthermore, preaching was always confirmed with signs (Mar 16:20).

Consider and alternative way to translate this: if you believe and are changed by the gospel.

A Follower of Christ
~~~~~~~~~~~~~~~~~~~~

Christ's own words on what it takes to follow Him.


Peter as a teacher on Baptism
-----------------------------

- The Flood and the Ark (1 Pet 3:21): Notice how Noah and his family didn't get wet


Paul as a teacher on Baptism
----------------------------

Paul speaks of baptism more than any other author when we consider all three.

- The Crossing of the Red Sea (1 Cor 10:2): Moses and Israel didn't get wet
- References to carnal ordinances (Heb 9:10)


Baptism in Water
----------------

In the New Testament, we see John the Baptist performing this. But what is unique or special about this?

- Jordan River, not the Temple
- what else?

John clearly says that one is coming who will baptize with Holy Spirit fire (Mat 3:11, Luk 3:16). How is John's
Baptism similar to Old Testament mikvah?

Mikvah
~~~~~~

- http://www.chabad.org/theJewishWoman/article_cdo/aid/1541/jewish/The-Mikvah.htm
- http://free.messianicbible.com/feature/mikvah-baptism-the-connection-between-immersion-conversion-and-being-born-again/
- https://en.wikipedia.org/wiki/Ritual_washing_in_Judaism

Realize that Circumcision and Baptism were required for a Gentile.


Baptism in Spirit
-----------------

The one that instated this is Christ. But this goes back to an Old Testament promise to the Nation of Israel.


Baptism in Death
----------------

When we think about the word baptism, death is ususally not the first association that jumps to mind.
However, baptism into the death of Christ is a central message to Paul's teaching.
Paul makes it clear that to be baptized into Christ is really to be baptized into His death.

Rom 6:3 KJV
___________
Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?
___________

Both Galatians and 1 Corinthians provide a wealth of insight on the gospel through this baptism.

The structure of Galatians centers around baptism into Christ and the Cross:

- A: Gal 2:20: Paul crucified with Christ. Christ living in him.
- B: Gal 3:1: The Galatians had a clear example of Christ crucified.
- C: Gal 3:27-28: Baptized into Christ, distinction gone, all one in Christ Jesus
- B: Gal 5:24: They that are Christ's have crucified the flesh
- A: Gal 6:14: The world has crucified to Paul. The New Creation.

How was it that the Galatians has a clear example of Christ crucified set before them?
This was through the preaching and life of Paul. Because he was baptized into the death of Christ and had embraced the cross.
Paul made this evident through his life.
This had become Paul's identity.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________



Baptism and The New Creation
----------------------------

It is impossible to be a part of the New Creation without this baptism. Christ is the Head of this creation
much like Adam was the head of the old.

But can you be a part of the New Creation without experiencing the other baptisms?

In Col, both the circumcision and baptism are accomplished by God, not human hands (Col 2:10-12).

The New Creation reveals the manifold wisdom of God (Eph 3:10). Just because all are One in Christ does not mean all have the *same purpose* in Christ.

What is the defining characteristic of the New Creation? Love.


Questions
---------

Is there a relationship with these and the stages of growth that Paul describes in Corinthians?

- Slave
- Child
- Full Grown
