Christ as a Teacher on Baptism
------------------------------

Christ challenged the Pharisees with their views on baptism by not baptizing before dinner.

[Luk 11:38 KJV] 38 And when the Pharisee saw [it], he marvelled that he had[G907] not first washed[G907] before dinner.

A concordance of Christ's teaching on baptism:

- TODO

Christ echoes this transition from old to new when he spoke about inheriting the kingdom

[Jhn 3:3, 5 KJV] 3 Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot see the kingdom of God. ... 5 Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and [of] the Spirit, he cannot enter into the kingdom of God.

The teaching of Christ on baptism seems to center on two things:

1. Great Commission
2. Baptism into death

Did Jesus ever speak explicitly of baptism in water?
Did Jesus ever baptize anyone?
John indicates that Jesus was going to baptize with spirit (holy spirit fire) (Luke 3:16).

Isa 61:1-2a KJV
___________
The Spirit of the Lord GOD [is] upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to [them that are] bound;
To proclaim the acceptable year of the LORD ...
___________

Peter as a teacher on Baptism
-----------------------------

A concordance of Peter's teaching on baptism:

- [1Pe 3:21 KJV] 21 The like figure whereunto [even] baptism doth also now save us (not the putting away of the filth of the flesh, but the answer of a good conscience toward God,) by the resurrection of Jesus Christ:
- TODO

Peter makes the comment that "baptism doth also now save us", but he is very clear that this is not the washing away of filth of the flesh.
He clearly relates this "baptism" to the resurrection of Christ in that same verse.
This cannot be mere water baptism.
And just a few verses earlier, he speaks of Christ being put to death in the flesh but quickened in the Spirit.
So Peter aligns salvation with the death, burial, and resurrection of Christ.

Thinking of Noah and his family, it was actually faith that saved them.
Without the ark, there would be no salvation.
And it took faith in God's word to build the ark.

This baptism may be more symbolic of the transition from the old creation to the new creation than it is of water baptism itself as a cleansing ritiual.
Noah and his family stepped into the ark from the old creation and stepped off of the ark into the new creation.
While not the focus here, a more detailed study of ark throughout scripture would likely yield much very interesting insight.

Paul as a teacher on Baptism
----------------------------

A concordance of Paul's teaching on baptism:

- TODO

Paul discusses this in the context of inheriting the kingdom

[1Co 15:48-54 KJV] 48 As [is] the earthy, such [are] they also that are earthy: and as [is] the heavenly, such [are] they also that are heavenly. 49 And as we have borne the image of the earthy, we shall also bear the image of the heavenly. 50 Now this I say, brethren, that flesh and blood cannot inherit the kingdom of God; neither doth corruption inherit incorruption. 51 Behold, I shew you a mystery; We shall not all sleep, but we shall all be changed, 52 In a moment, in the twinkling of an eye, at the last trump: for the trumpet shall sound, and the dead shall be raised incorruptible, and we shall be changed. 53 For this corruptible must put on incorruption, and this mortal [must] put on immortality. 54 So when this corruptible shall have put on incorruption, and this mortal shall have put on immortality, then shall be brought to pass the saying that is written, Death is swallowed up in victory.

- The Crossing of the Red Sea (1 Cor 10:2): Moses and Israel didn't get wet
- References to carnal ordinances (Heb 9:10)

Paul speaks of baptism more than any other author when we consider all three.

Paul explains what embracing the cross looks like in a somewhat puzzling passage in 1 Cor.

1Co 15:29 KJV
____________
Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?
____________

Paul is asking: why would someone be baptized "for the dead" if there is no resurrection of the dead.
What does being baptized "for the dead" mean?
The phrase in the Greek can mean over as in position or also in place of.

Commonly, this verse is understood as a reference to a practice of either baptizing the dead or getting baptized in the place of a dead person.
But it is a bit strange to assume this given there is no hint of this anywhere else in this book.
Why would Paul randomly refer to a practice not found anywhere else in the Bible when he is trying to defend the truth of the resurrection?
It makes much more sense here if Paul is actually speaking of the same thing in v29 - v32.
Paul mentions that he fought with wild beasts a few verses down.
The criminals and Christians were at that time thrown before wild beasts (research more).
How many died in these very area floors for their faith?
Paul could be referring to those that were baptized over the same place as these dead.
This lifestyle of dying daily was the outcome of Paul embracing the message of the cross.
This word "for" or "over" is the Greek word "hyper" and can mean "above" or "beyond".
I think Paul is speaking of being baptized beyond death: "I die daily".

The structure of Galatians centers around baptism into Christ and the Cross:

- A: Gal 2:20: Paul crucified with Christ. Christ living in him.
- B: Gal 3:1: The Galatians had a clear example of Christ crucified.
- C: Gal 3:27-28: Baptized into Christ, distinction gone, all one in Christ Jesus
- B: Gal 5:24: They that are Christ's have crucified the flesh
- A: Gal 6:14: The world has crucified to Paul. The New Creation.

How was it that the Galatians has a clear example of Christ crucified set before them?
This was through the preaching and life of Paul. Because he was baptized into the death of Christ and had embraced the cross.
Paul made this evident through his life because this had become Paul's identity.
One of the disciples came to Jesus while He was on earth and asked to see the Father.
How did Jesus reply?
"Have I been with you so long, and yet you have not known Me, Philip? He who has seen me has seen the Father." (John 14:9)
In effect, Paul is saying a similar thing here.
If you have seen me (Paul), you have seen Christ.

What was Paul talking about here?
What does Christ crucified look like?
Is it powerful signs and wonders?
Paul used this example to confront issues in the Corinthian church.
Communion and its consequences, the spirit gifts, baptized into one body.
These had the baptism of the spirit. They had the gifts.
But they didn't understand the message of the cross.
Much like the Children of Israel in the Old Testament were baptized into Moses but died in the wilderness.
They were ordained priests under the New Covenant and had the spirit anointing to prove it.
Much like the priests under the Old Covenant, misusing the calling and gifts had serious consequences.
May were ill and some even died.
Paul says to have all of that but still not have love means you are nothing.
Another way we could say this is if you have been Ordained under the New Covenant, but you don't understand
the cross or its meaning for your life, it's kind of all for nothing.

The miracles performed by Jesus are not the ultimate expression of the power and the wisdom of God.
And the sign gifts of Spirit anointing are only temporary.
They are passing away as Paul says in 1 Cor 13.
If you have been baptized in water and anointed with the spirit, but you don't have love, you are nothing.
Its not the physical act of dying that is central to the cross in practical application.
Paul says that if you give your body to be burned but don't have love, you are nothing.
This sacrifice is only acceptable to God if it is done willingly.
Can you do something willingly if you don't have a choice?
I think there is the very real possibility that those that God calls to be martyrs also have choice (Heb 11:35).
Did Christ die because He was nailed to a cross and couldn't escape?
No, He died because He willingly gave Himself up.
That is the power and the wisdom of God in the cross.
It is getting to the point of being able to willingly let go of everything.


The One Baptism in Ephesians
~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Eph 2:11-18 KJV
_______________
Wherefore remember, that ye [being] in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;
That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:
But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.
For he is our peace, who hath made both one, and hath broken down the middle wall of partition [between us];
Having abolished in his flesh the enmity, [even] the law of commandments [contained] in ordinances; for to make in himself of twain one new man, [so] making peace;
And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:
And came and preached peace to you which were afar off, and to them that were nigh.
For through him we both have access by one Spirit unto the Father.
_______________

|========
| Eph 4                 | Eph 2
| One Body              | reconcile both unto God in one body (v16)
| One Spirit            | access by one Spirit to the Father (v18), habitation of God through the Spirit (v22)
| One Lord              | holy temple in the lord (v21)
| One Faith             | Saved through faith (v8)
| One Baptism           | Made both one (v14), One new anthropos (v15), by the cross (v16)
| One God and Father    | Access by one Spirit to the father (v18)
|========

Baptism: Fountaional versus Vocational
--------------------------------------

Being baptized into Christ is foundational to any purpose found in Christ.
But God does not stop building at the foundation.
He completes the purpose by finishing the building.

Moses didn't drop the Children of Israel off on the other side of the Red Sea with no destination.
What's follows identification with Christ is calling into purpose.

Could not God make a Priest out of a Jew or Gentile? But they were mostly Jews by origin.
Could not God make a Soldier out of a Gentile or Jew? But they were mostly Gentiles by origin.


Baptism in the Septuagint
-------------------------

See the article on "Baptism" in Alphabetical Analysis (C.H. Welch).
But some key passages are illustrated here.

The word baptizo is found in the following passages:

- 2 Kings 5:14
- Isa 21:4

The word bapto is found in the following passages:

- Job 9:31
- Dan 4:33, 5:21

Joshua and the Jordan River
---------------------------

there is another important connection to Bethabara in Israel's history.
This location is likely very close to the historical city of Jerico.
And Jerico is the historical location where Joshua and Caleb led the children of Israel out of the wilderness, across the Jordan river, and into the promised land.

Several key things stand out about this Jordan river crossing (Joshua 3-4):

- Joshua instructed Israel to sanctify themselves (e.g. wash up) because God was about to do wonders. What was this? Was this washing? Was this related to circumcision?
- God used this to exhalt Joshua in the sight of Israel, much like Christ was going to be exhalted.
- Joshua chose 12 men to be witnesses for Israel.
- The 12 men carried stones out of the bottom of the river and placed them on the bank of the river as a memorial of the day.

John is baptizing in the Jordan river near the place where Joshua crossed over with the children of Israel many years before.
And you have John and Jesus as key figures now much like Caleb and Joshua were so many years later.

Additional References for Reading
---------------------------------

- The Mikvah

    - http://www.chabad.org/theJewishWoman/article_cdo/aid/1541/jewish/The-Mikvah.htm
    - http://free.messianicbible.com/feature/mikvah-baptism-the-connection-between-immersion-conversion-and-being-born-again/
    - https://en.wikipedia.org/wiki/Ritual_washing_in_Judaism

- An excellent reference on baptism, washing, sprinking throughout the Bible: http://www.fivesolas.com/sprinkle.htm

- Concordance on Hebrew word for wash: https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?Strongs=H7364&t=KJV
