Priests and Soldiers
====================

Both John and Paul had special revelations associated with heaven and with the church in the new creation.
John calls the church the "bride". Paul call the church the "husband".
The old creation is at best a picture of what is coming.
Revelation: king, priest, bride
Ephesians: head, warrior, husband

- The two major ways scripture looks at callings of believers
- The roles and identities assumed by Christ in Revelation, also shared by believers
- OT Israel as an example of the bigger picture.
- What you were born into mirrors the calling of God. A priest was born a priest.

The preparation of the prest can be studied in the baptisms of Aaron and Christ.
The preparation of the warrior is found in Ephesians:

- Washing in water by the word (Eph 5:26-27)
- Put on the armor of God (Eph 6:10-17)
- Given the Sword of the Spirit (Eph 6:17-18)

Questions:

1. Do The Horse and Rider with Heavenly Armies in Revelation 19 relate to Christ and the Church of the Husband
2. Are those in the First Resurrection in Rev 20:4-6 the overcomers, the Kings and Priests of the Church of the Bride

The Tribe of Levi was not numbered to go to war by Moses (Numbers 1:3, 47). Did they ever fight?
