== Baptism
// depending on your npm version, you might need to override the default
// 'revealjsdir' value by removing the comments from the line below:
//:revealjsdir: node_modules/asciidoctor-reveal.js/node_modules/reveal.js

What do you think of when you hear this word?

== John the Baptist

What was significant about his baptism?

== Water Washing in the Tabernacle

Heb 9:9-10 KJV
______________
[The Tabernacle] Which [was] a figure for the time then present, in which were offered both gifts and sacrifices, that could not make him that did the service perfect, as pertaining to the conscience;
[Which stood] only in meats and drinks, and divers washings, and carnal ordinances, imposed [on them] until the time of reformation.
______________

== "Washing" is the word for "baptism"

These "diverse baptisms" were a significant part of the Tabernacle service done by priests.

== The Ordination of a Priest

Exo 29:4 NKJV
_____________
And Aaron and his sons you shall bring to the door of the tabernacle of meeting, and you shall wash them with water.
_____________

== The Work of a Priest

Exo 30:20 NKJV
______________
When they go into the tabernacle of meeting, or when they come near the altar to minister, to burn an offering made by fire to the LORD, they shall wash with water, lest they die.
______________

== Wash your hands or die!

== John the Baptizer

He was performing the baptisms

He was baptizing in the river Jordan

== The Phairsees Investigate

Why then do you baptize if you are not the Christ, nor Elijah, nor the Prophet?" (John 1:25)

== What was John doing?

1. Revealing The Lamb of God
2. Revealing The Great High Priest

== Revealing the Lamb of God

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
"This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
"I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

== Revealing The Great High Priest

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

== The Baptism of Christ

Mat 3:14-15 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

== Fulfill all Righteousness

Christ was born under the Law and lived under the Law

== The Ordination of a High Priest

1. Wash in water
2. Put on priestly garments
3. Anoint with oil

== The Baptism of Christ

1. Washed in water
2. Anointed by the spirit

== The Ordination of Christ

1. Water: Fulfillment of the Old Covenant
2. Spirit: Foretaste of the New Covenant

== A Nation of Priests

1Pe 2:9 NKJV
____________
But you [are] a chosen generation, a royal priesthood, a holy nation, His own special people, that you may proclaim the praises of Him who called you out of darkness into His marvelous light;
____________

== The Ordination of a Nation

The Great Commission / Penticost

== Another Baptism?

Luk 12:50 NKJV
______________
"But I have a baptism to be baptized with, and how distressed I am till it is accomplished!"
______________

== Jesus replies to James and John

Mat 20:22 NKJV
______________
"You do not know what you ask. Are you able to drink the cup that I am about to drink, and be baptized with the baptism that I am baptized with?"
______________

== Jesus replies to James and John

Mat 20:27-28 NKJV
______________
"And whoever desires to be first among you, let him be your slave--
just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many."
______________

== The Last Baptism of Christ

Foundational to His work as High Priest
