== Baptism
// depending on your npm version, you might need to override the default
// 'revealjsdir' value by removing the comments from the line below:
//:revealjsdir: node_modules/asciidoctor-reveal.js/node_modules/reveal.js

What do you think of when you hear this word?

== John the Baptist

What was significant about his baptism?

== Water Washing in the Tabernacle

Heb 9:9-10 KJV
______________
[The Tabernacle] Which [was] a figure for the time then present, in which were offered both gifts and sacrifices, that could not make him that did the service perfect, as pertaining to the conscience;
[Which stood] only in meats and drinks, and divers washings, and carnal ordinances, imposed [on them] until the time of reformation.
______________

== The word "washing" is the word "baptism"

These "diverse baptisms" were a significant part of the Tabernacle service done by priests.

== The Ordination of a Priest

Exo 29:4 NKJV
_____________
And Aaron and his sons you shall bring to the door of the tabernacle of meeting, and you shall wash them with water.
_____________

== The Work of a Priest

Exo 30:20 NKJV
______________
When they go into the tabernacle of meeting, or when they come near the altar to minister, to burn an offering made by fire to the LORD, they shall wash with water, lest they die.
______________

== Wash your hands or die!

== What was John doing?

The Phairsees ask..."Why then do you baptize if you are not the Christ, nor Elijah, nor the Prophet?" (John 1:25)

== John was manifesting the Lamb

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
"This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
"I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

== John was manifesting the Great High Priest

Moses and Aaron are a precursor to John and Christ

== The Baptism of Christ
