Baptism
=======

When you hear the word baptism, what kind of picture enters your mind?
Often it will be something along these lines: https://www.google.ca/search?q=baptism&tbm=isch.
But why is water so strongly associated with the word baptism?

There is an equally valid and even more powerful image that we can  associate with the word baptism:
https://www.google.ca/search?q=cross&tbm=isch.

How often is the cross the first image that enters your mind when you hear the word baptism?
How could this change how we look at the world?
How could this change how the world sees us?

John the Baptist
----------------

One of the main reasons water has become so strongly linked with baptism is a result of the ministry of someone who came before Jesus.
He is so widely known for water baptism, it has become a permanent part of his name.
He even baptized Jesus in water.
He is, of course, John the Baptist.
It may be tempting to think that John the Baptist was the one who established water baptism.
This is what he was doing along the banks of the Jordan river.

But baptism in water goes much further back in time.
It was present throughout the Old Testament.
It was, in fact, intimately associated with the Tabernacle and the duties of the priests.
In Hebrews, We read this about the Tabernacle.

Heb 9:9-10 NKJV
_______________
It [was] symbolic for the present time in which both gifts and sacrifices are offered which cannot make him who performed the service perfect in regard to the conscience--
[concerned] only with foods and drinks, various washings, and fleshly ordinances imposed until the time of reformation.
_______________

For a priest, this washing was no one-time event; it was a way of life.
Washing in water was required both at the ordination of a priest and during his ongoing day-to-day service in the Tabernacle.
The word translated "washings" is the Greek word for baptism.
We could quite correctly say that these "various washings" where "various baptisms" required under the ceremonial law.

The very first high priest to be ordained under the Old Covenant was Aaron.
Moses performed this ceremony that we read about in Exodus.

Exo 29:4 NKJV
_____________
And Aaron and his sons you shall bring to the door of the tabernacle of meeting, and you shall wash them with water.
_____________

This initial washing of a priest was special; it was different from the washing that was a part of his ongoing work.
The Hebrew word for wash used here may mean taking a full body wash like a bath or just washing your hands, depending upon the context.
When a priest was ordained, he was required to take a full body wash.
He had to bathe himself, not just wash his hands or feet.

But in the case of Aaron, there was an important difference.
Aaron did not do the washing; Moses washed Aaron.
Or we could say, Moses baptized Aaron as the first high priest.

After ordination, a priest was required to wash himself before performing any service within the tabernacle.
This ongoing washing was performed by the priest himself, and it was a more limited washing of the hands and feet (Exo 30:19-20).
There were serious consequences to not washing.

Exo 30:20 NKJV
______________
When they go into the tabernacle of meeting, or when they come near the altar to minister, to burn an offering made by fire to the LORD, they shall wash with water, lest they die.
______________

Imagine going into work each day and being greeted by a sign on the wall that said "wash your hands or die!".
You can imagine how it might be possible to get carried away with this and start washing a few extra times just to be sure you're safe.
The requirements of the law for washing had been embellished and built upon with layers of religious traditions.
Some groups like the Pharisees had become rather obsessed with ritual washing.

Fast forward to John the Baptist.
John was preaching a message of repentance.
People were coming to him to be baptized.
They weren't baptizing or washing themselves in water, they were being baptized by John.
And they weren't going to the temple for this, they were going out to the banks of the Jordan river.

When the Pharisees heard of this, they sent someone to investigate (John 1:25).
The fact that baptism was being performed in water was not puzzling to them.
It was the fact that John was performing the baptisms that surprised them.
As far as we know, the last time somebody was baptized by someone else was when Moses baptized Aaron.
They expected that the next time this would happen would be with Elijah or the Messiah.
If he wasn't the Messiah or Elijah, why was he doing this?

The location where John was baptizing was significant.
John was performing his baptisms near Bethabara, a location deeply connected with the history of Israel (https://en.wikipedia.org/wiki/Bethabara).
This was near the historical location of Jerico, so it would not have been far from where Joshua and the children of Israel crossed the Jordan Riveer on their way into the promised land.
It is also rumored to be the last location where the prophet Elijah was seen before he was taken up into heaven.
So you have someone doing what was expected of Elijah in the location where Elijah was last seen.

But why was John baptizing?
What was the purpose of all this?

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

John's purpose was to reveal the Lamb of God to the Nation of Israel.
This Lamb--the Messiah--would take away the sins of that nation and the world.
Under the Old Covenant, once a year, the High Priest would make a sin offering for the sins of the whole nation.
But in the case of Christ, He is the sin offering.
He is the Lamb.
But who was the High Priest that was going to perform this sacrifice?

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

Under the New Covenant, The High Priest and the sin sacrifice are one in the same.
This Great High Priest offered Himself once and for all.
The baptism of Aaron by Moses was a precursor to the baptism of Jesus by John.
Moses baptized the first high priest under the Old Covenant.
John baptized The Great High Priest of the New Covenant.

The Ordination of The Great High Priest
---------------------------------------

An interesting exchange takes place as Jesus comes to John to be baptized.
At first, John refuses to baptize Him.

Mat 3:14 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
________________

Remember that John was looking for the one who would baptize with the Spirit.
He wanted to be baptized by the Messiah, not the other way around.
The answer Jesus gives is insightful.

Mat 3:15 NKJV
________________
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

To fulfil what righteousness?
We have to remember that Christ was born under the Law and lived under the Law.
By His own words, He had come not to destroy the Law, but to fulfill or complete the Law (Mat 5:17).
The High Priest role and the sin offering of the Old Covenant are both fulfilled in Christ as the Mediator of the New Covenant.
But the Old Covenant was not something that instantly disappeared.
Even as late as in the book of Hebrews, which was written after both the resurrection of Christ and Penticost, the Old Covenant is described as being "ready to vanish away" (Heb 8:13).
That is, it had not yet vanished away.

How was the first High Priest ordained under the Old Covenant?
There were three things that Moses specifically did in Exodus 29.
First, he washed Aaron in water.
Washing in water was required for physical cleanliness under the law.
It was good hygiene but it was also required to be considered ceremonially clean.
Washing in water also symbolizes washing away sin and sickness.
Then, he then took the priestly garments and placed them on Aaron.
These garments were like the uniform for the office of a priest.
They represented his new identity as a priest.
The garments symbolize putting on righteousness.
Finally, he took some oil and anointed Aaron with it.
Throughout scripture, oil is used symbolically to represent the Holy Spirit.

Let's think about Christ's baptism in this light.
Matthew says that immediately after Jesus was baptized by John, the Spirit was seen descending on Him like a dove (REF).
The dove with the voice from heaven indicate the Spirit anointing of the Christ.
But in this case, the Spirit anointing followed immediately after the baptism in water.
What's missing?
There is no mention of changing into the Priestly garments.
Christ did not need to put on righteousness; He was already righteous.
And he was the first one to be baptized in the Spirit.
Everyone else had to wait until after Penticost.

The Baptism of Christ is the Ordination of Christ as the Great High Priest.
We can see both the completion of the old and the foretaste of the new in the baptism of Christ.
The washing in water performed by John for a Priest was present.
The anointing in the Spirit was a foretaste of the New Covenant.
Jesus was simultaneously completing the Old Covenant preisthood while He was becoming High Priest of the New Covenant.
Only the Heavenly Father could actually appoint this High Priest.
The voice of the Father was present with the Spirit.

The Ordination of Christ as the Great High Priest is a picture of what God wanted to do on a larger scale with the Nation of Israel.
Peter writes about this.

1Pe 2:9 NKJV
____________
But you [are] a chosen generation, a royal priesthood, a holy nation, His own special people, that you may proclaim the praises of Him who called you out of darkness into His marvelous light;
____________

What God did with the tribe of Levi under the Old Covenant was a picture of what He planned to do on a much larger scale with the Nation of Israel under the New Covenant.
The Kingdom of Heaven is really a Kingdom of Priests.
Christ's ministry to Israel was focused on preparing them to embrace this priestly role as a nation.
We need to understand the Great Commission (Mar 16:15-18) and Penticost (Acts 2) in light of the New Covenant Priesthood Christ was coming to establish.
Both of these events are closely related to the Ordaining of the Nation of Priests.
Once this Nation was Ordained, it would be used by God to preach the Gospel throughout the world.

The Work of the Great High Priest
---------------------------------

Remember how Aaron was baptized by Moses when he was ordained as the first high priest?
But after that, there was washing or baptism that was necessary as part of his work as high priest.
We see the same pattern with Christ, the Great High Priest of the New Covenant.
Only the baptism that was a part of His work is far different from any washing in water.
Christ Himself has this to say about it.

Luk 12:50 NKJV
______________
"But I have a baptism to be baptized with, and how distressed I am till it is accomplished!"
______________

This statement was made well after He was baptized by John the Baptist.
Whatever this baptism was, it was a source of stress or distress.
We can piece this together with what Matthew and Mark record to get a better picture.

James and John came to Jesus to ask a favor.
They wanted to sit at His right hand and left hand in the Kingdom.
They were asking for a position of great honour.
And, as it turns out, they didn't really understand the magnitude of what they were asking for.

Mat 20:22 NKJV
______________
"You do not know what you ask. Are you able to drink the cup that I am about to drink, and be baptized with the baptism that I am baptized with?"
______________

And He continues just a few verses down.

Mat 20:27-28 NKJV
______________
"And whoever desires to be first among you, let him be your slave--
just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many."
______________

The work of this High Priest was unlike that of any of the other priests under the Old Covenant.
Doesn't it make sense that the baptism associated with that work was different too?

According to tradition, James and John both became martyrs for their faith.
This was a baptism that they shared with Christ that was above and beyond any water baptism or spirit anointing.
They sacrificed everything for their faith.
It is this baptism that Christ had this is foundational to His work as a Priest.
But as we will see, it is even bigger than that.
It's foundational to the new creation, to everything that God is setting out to ultimately achieve in the redeemed universe.

Baptize: The Word
-----------------

The challenge in arriving at a complete understanding of baptism is the fact that one work is used to refer to at least three different things.
Baptism can refer to the washing in water that was so intimately associated with the service of the Old Covenant.
Baptism can refer to the Spirit anointing that was required for service under the New Covenant.
But baptism can also refer to the work of The Great High Priest, the sacrificial death of Christ.

But we have not yet examined the actual word itself.
Is there perhaps something more we can learn about baptism from the word itself?
The Greek word for baptism is βαπτίζω (baptizo).
Vine's Expository Dictionary has this to say about it.

___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

The term "frequentative form" is a technical way of saying that the word signifies greater intensity or repeated action.
An excellent illustration of this found in the form of an ancient recipe from around 200 B.C.
The Greek poet and physician Nicander described the process of making pickles.
First, the vegetable must be dipped (bapto) in boiling water.
Then the vegetable must be baptized (baptizo) in vinegar.
Nicander used the same Greek word that is used for baptism in the New Testament.

What is it a pickle a pickle?
Is it the fact that you observed it being dipped into vinegar?
Is it a label on the jar?
Or is it a pickle because you can taste the vinegar?

Water baptism was not a one-time event for a priest.
Yes, there was a baptism associated with his ordination, but washing in water was a very real part of his ongoing duties.
The washing was never done under the Old Covenant, because water could never truly wash away your sins.

Baptism in the Spirit as seen at Penticost was fundamentally different than anything seen in the Old Testament.
This anointing would not come and go; it was a permanent ongoing presence on the believer.
The baptism

The baptism that Christ went through as part of His great sacrifice was no just a one-time even on the Cross.
It was something He was living in His life leading up to that event.
In a sense, Christ died before He actually got to the cross.
The significance of the sacrifice was not that He was killed on the cross.
It was that He willingly gave up His life; He sacrificed Himself.
That's the baptism that James and John ultimately shared with Him.

Baptized into Christ
--------------------

The Apostle Paul may be the greatest teacher on baptism in the New Testament.
No other writer explains in such depth the significance of baptism in light of the work of Christ.
But Paul has this to say about the focus of his ministry in 1 Corinthians.

1Co 1:17 NKJV
_____________
For Christ did not send me to baptize, but to preach the gospel, not with wisdom of words, lest the cross of Christ should be made of no effect.
_____________

He was focused on preaching the gospel in such a way that the message of cross would always shine through.
The good news of righteousness by faith was always front and center in the ministry of Paul, whether he was preaching to the Jews or the Gentiles.
The book of Romans is nothing short of a masterpiece on this topic.

By his own words, there were very few individuals that Paul had actually baptized himself, at least as far as the Corinthians were concerned (1 Cor 1:14-16).
Water baptism simply was not a major focus of his ministry.
Paul spoke extensively about Spirit anointing, and the gifts that followed.
He had many of these gifts himself.
But neither spirit baptism nor water baptism were foundational to his ministry.

When Paul teaches about baptism, he is speaking about something that is foundational to the gospel he preached.

Gal 3:27 NKJV
_____________
For as many of you as were baptized into Christ have put on Christ.
_____________

The Greek work for "put on" is actually the same word that can be translated "clothed".
To put on Christ is to be clothed in Christ.
Righteousness by faith is found only in Christ.

Remember what happened when John baptized Jesus?
The anointing of the Spirit fell on Jesus immediately after He was washed in water.
There was no mention of changing garments.
This is because righteousness came before baptism.
In the case of Christ, He was already righteous.
Everyone else had to put on righteousness by faith first.
They had to wait until after His death, burial, and resurrection.
Penticost must come after the Passover.

Let's think about the Great Commission as recorded in Mark 16.
Christ said that those who believed and were baptized would be saved.
He also said that signs would follow those that believed.
If we understand belief to be faith in the Messiah and His sacrifice, then this is part of the good news of righteousness by faith that Paul was preaching.
In the Great Commission, faith must come before baptism, whether it is water or Spirit.

Under the Old Covenant, baptism was a perpetual requirement.
The washing and sacrificing would be repeated over and over again.
But sin was never truly washed away.
Under the New Covenant, these ceremonial washings in water were finished.
Those that had faith in Messiah washed in water one last time as a completion of the old.
And they were anointed in the Spirit as a foretaste of the new.
For a Priest entering the New Covenant, faith, water, and spirit were a package deal.

In Galatians, Paul teaches that to be clothed in Christ is to be baptized.
This baptism is foundational to the gospel and must come first.
It is received only by faith.

In the book of Romans, Paul explains this baptism in even more detail.

Rom 6:3-6 NKJV
______________
Or do you not know that as many of us as were baptized into Christ Jesus were baptized into His death?
Therefore we were buried with Him through baptism into death, that just as Christ was raised from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been united together in the likeness of His death, certainly we also shall be [in the likeness] of [His] resurrection,
knowing this, that our old man was crucified with [Him], that the body of sin might be done away with, that we should no longer be slaves of sin.
______________

Baptism and the cross are always closely connected in the teaching of Paul.
They are like opposite sides of the same coin.
To be baptized into Christ is to be baptized into His death.
This death is the death of the cross.
The old man has been crucified with Him in the past tense.
This was accomplished by Christ when He offered himself on the cross as a sacrifice for sin once and for all.
It is received only by faith.

In the book of Colossians, Paul explains the same concept in slightly different terms.
He is speaking to Gentiles at large; people who had never been circumcised or baptized before.

Col 2:8-14 NKJV
_______________
Beware lest anyone cheat you through philosophy and empty deceit, according to the tradition of men, according to the basic principles of the world, and not according to Christ. 9 For in Him dwells all the fullness of the Godhead bodily; 10 and you are complete in Him, who is the head of all principality and power. 11 In Him you were also circumcised with the circumcision made without hands, by putting off the body of the sins of the flesh, by the circumcision of Christ, 12 buried with Him in baptism, in which you also were raised with [Him] through faith in the working of God, who raised Him from the dead. 13 And you, being dead in your trespasses and the uncircumcision of your flesh, He has made alive together with Him, having forgiven you all trespasses, 14 having wiped out the handwriting of requirements that was against us, which was contrary to us. And He has taken it out of the way, having nailed it to the cross.
_______________

Under the Old Covenant, both circumcision and baptism in water (the mikvah) were required for a Gentile that wanted to become a practicing Jew.
Under the New Covenant, believing Gentiles received the anointing of the Spirit just like the Jews, but they were uncircumcised and didn't keep the ceremonial law.
Baptism in water was sill a part of this.

But the circumcision done here is performed without hands. It is the circumcision of Christ.
This circumcision was accomplished on the cross through the death of Christ.
Does it not make total sense that the baptism done here is also without hands?
In other words, Paul is saying you are complete in Christ with a circumcision and baptism not done with human hands.

Being baptized into Christ means we have been baptized into His death.
Even more than that, it means we have been buried with Him through baptism.
But this baptism doesn't leave us dead.
What follows is being raised from the dead to a newness of life.

You are complete in Christ through baptism into his death, burial, and resurrection.
Your completeness in Christ can never be achieved or enhanced through washing in water or Spirit anointing.
It stands solely and completely on the sacrifice of Christ and the working of God.
This baptism is absolutely foundational to the Gospel.

The One Baptism
---------------

Paul takes baptism to a new level when summarizing the unity of the Spirit in the book of Ephesians.

Eph 4:4-6 KJV
_____________
[There is] one body, and one Spirit, even as ye are called in one hope of your calling;
One Lord, one faith, one baptism,
One God and Father of all, who [is] above all, and through all, and in you all.
_____________

One Baptism.
Is there really just one baptism?
Can we leave the other two to the side and not miss them.
The unity of the Spirit in Ephesians chapter 4 is actually a reflection or a summary of a much more detailed explanation of the work of Christ found in chapter 2.
Paul explains this One Baptism in chapter 2.

Eph 2:14-16 NKJV
________________
For He Himself is our peace, who has made both one, and has broken down the middle wall of separation,
having abolished in His flesh the enmity, [that is], the law of commandments [contained] in ordinances, so as to create in Himself one new man [from] the two, [thus] making peace,
and that He might reconcile them both to God in one body through the cross, thereby putting to death the enmity.
________________

Remember that baptism and the cross are like flip sides of the same coin.
This One Baptism is accomplished by the cross.
Paul is sharing good news for the Gentile nations at large; he is speaking to those where uncircumcised and not part of the covenants of Israel (Eph 2:11-12).
The reconciliation here brings both Jew and Gentile into one body.
This isn't through any outward circumcision or ceremonial cleansing, but instead through the circumcision of Christ and baptism into His death.

The word for "new man" here isn't referring to a male specifically.
It's the word anthropos that is used to refer to a human being, whether male or female.
God is creating the new person in Christ.

|========
| Adam: Old Person (Rom)          | Christ: New Person (Eph)
| Adam & Eve as One Body (Gen)    | Christ & The Church as One Body (Eph)
| Nations & Israel (Gen)          | Husband & Bride (Eph & Rev)
|========

Christ is the Head of this creation much like Adam was the head of the old.
The New Creation is not defined by or based on these.
The only path to the new creation is through the death, burial, and resurrection of Christ.
Without baptism into the death of Christ, it is not possible to have any part of the new creation.
It is the calling of God that determines where you fit in the New Creation.
The New Person is the Church; it's those that were called out for a purpose.

This One Baptism is the greatest change being worked out in the purposes of God.
It is the transition from the Old Creation headed up by Adam to the New Creation headed up by Christ.
This change is accomplished through the cross of Christ.
The cross separates the old creation from the new creation.
The distinctions of the old creation are gender, race, and religion.
The more we find our identity in the old creation the more we will be lost and broken.
Our true identity is found not under the old creation but within the new creation.

What does the church look like?
The glimpses into the new creation we get in Scripture are few and far between.
Both John and Paul have the curtains peeled back a bit for a revelation.
John sees the Bride.
Paul sees the Husband.

The Soldier Husband calling.

The first half of Ephesians foundational to the New Creation. The second half is vocational.
But it isn't a priest that is being called here.

|========
| Soldier           | Priest
| Baptized          | Baptized
| Washed in Word    | Washed in Water
| Armed             | Anointed 
|========

Baptism into the death, burial, and resurrection of Christ is absolutely foundational to any vocation.
But what follows after is specific to the calling God has placed on you.

Based on the finished work of Christ, we are now encouraged to step into that new identity we have in Christ.
But we are also encouraged by Paul to "put on" or be "clothed" by this new person.
On one hand, our baptism is a done deal and there is nothing we can add to it.
On the other hand, we endeavour to keep or guard this one baptism through the things that we do.
Can we be a part of the New Creation--the New Person--without being a priest?

Ephesians reveals the husband soldier calling, part of the New Creation in Christ that was a secret up to this point.

Conclusion
==========

How do you identify a follower of Christ?
It's not through the vocational tools God may give through His Spirit.
The Corinthian believers had the priestly anointing, and they had the gifts of the Spirit to prove it. 
But unfortunately there were many things going on within the Corinthian church that were not in line with the heart of God.
Paul even described them as "carnal".
You can be ordained and anointed as a priest, but you can still miss out when it comes to having the heart of a priest.

Christ shared this insight on what it takes to truly follow Him.

Mar 8:34 KJV
____________
And when he had called the people [unto him] with his disciples also, he said unto them, Whosoever will come after me, let him deny himself, and take up his cross, and follow me.
____________

Being a follower of Christ means embracing the message and power of the cross in your life.
The power and the wisdom of God are expressed through the cross, not in the various gifts of the Spirit.
Paul says this another way in Colossians 3.

Col 3:3 NKJV
____________
For you died, and your life is hidden with Christ in God.
____________

We have died with Christ.
This is complete in the past tense.
But we reflect this reality in the present tense by "putting to death" (Col 3:5) the flesh that is in us.
This is putting off or stripping away the old person and putting on the new person (Col 3:9-10).
Embracing the cross is how our baptism into Christ becomes evident in our day-to-day life.

Paul was so changed by the cross that it had become part of his very identity.
He also lived out the power and wisdom of God in his very life.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

The cross caused Paul to look at the world differently.
The cross meant that Paul looked different to the world.
Baptism is a reality not just in the past tense but in the preset tense when the taste of the cross is present.
If you have seen me, you have seen Christ.
