Baptism
=======

When you hear the word baptism, what kind of picture enters your mind?
More often than not, the first picture that enters our mind will involve water in some way.
But there is an even more powerful image that we can associate with the word baptism.
How often is the cross the first image that enters your mind when you hear the word baptism?
How could this change how we look at the world?
How could this change how the world sees us?

John the Baptist
----------------

One of the main reasons water has become so strongly linked with the word 'baptism' is a result of the ministry of someone who came before Jesus.
He is so widely known for water baptism that it has become a permanent part of his name.
He even baptized Jesus in water.
He is, of course, John the Baptist.

It may be tempting to think that John the Baptist was the one who established baptism in water, but this practice goes back much further than John.
It was present throughout the Old Testament.
It was, in fact, intimately associated with the Tabernacle and the duties of the priests.
In Hebrews, we read this about the Tabernacle service.

Heb 9:9-10 NKJV
_______________
It [was] symbolic for the present time in which both gifts and sacrifices are offered which cannot make him who performed the service perfect in regard to the conscience--
[concerned] only with foods and drinks, various washings, and fleshly ordinances imposed until the time of reformation.
_______________

For a priest, this washing was no one-time event; it was a way of life.
Washing in water was required both at the ordination of a priest and during his ongoing service in the Tabernacle.
The word translated "washings" is the Greek word for baptism.
We could quite correctly say that these "various washings" where "various baptisms" required under the ceremonial law.

The very first high priest to be ordained under the Old Covenant was Aaron.
Moses performed this ceremony that we read about in Exodus.

Exo 29:4 NKJV
_____________
And Aaron and his sons you shall bring to the door of the tabernacle of meeting, and you shall wash them with water.
_____________

This initial washing of a priest was special; it was different from the washing that was a part of his ongoing work.
The Hebrew word for wash used here may mean taking a full body wash like a bath or just washing your hands, depending upon the context.
When a priest was ordained, he was required to take a full body wash.
He had to bathe himself, not just wash his hands or feet.
But in this case, Aaron did not do the washing; Moses washed Aaron.
Or we could say, Moses baptized Aaron as the first high priest.

After his ordination, a priest was required to wash himself before performing any service within the tabernacle.
This ongoing washing was performed by the priest himself, and it was a more limited washing of the hands and feet (Exo 30:19-20).
There were serious consequences to not washing.

Exo 30:20 NKJV
______________
When they go into the tabernacle of meeting, or when they come near the altar to minister, to burn an offering made by fire to the LORD, they shall wash with water, lest they die.
______________

Imagine going into work each day and being greeted by a sign on the wall that said "wash your hands or die!".
You can imagine how it might be possible to get carried away with this and start washing a few extra times just to be sure you're safe.
Over the centuries, the requirements of the law for washing had been embellished and built upon with layers of religious traditions.
Some groups like the Pharisees had gotten to the point of mild obsession with ritual washing.

Fast forward to John the Baptist.
John was preaching a message of repentance, and people were coming to him to be baptized.
They weren't baptizing or washing themselves in water, they were being baptized by John.
And they weren't going to the temple for this, they were going out to the banks of the Jordan river.
When the Pharisees heard of this, they sent someone to investigate (John 1:25).
The fact that baptism was being performed in water was not puzzling to them.
It was the fact that John was performing the baptisms that surprised them.
The last time baptism was performed like this was when Moses baptized Aaron.
They expected that the next time this would happen would be with Elijah or the Messiah.

The location where John was baptizing was also significant.
John was performing his baptisms near Bethabara, a location deeply connected with the history of Israel (https://en.wikipedia.org/wiki/Bethabara).
This was near the historical location of Jerico, so it would not have been far from where Joshua and the children of Israel crossed the Jordan River on their way into the promised land.
It is also rumored to have been the last location where the prophet Elijah was seen before he was taken up into heaven.
So you have someone doing what was expected of Elijah in the location where Elijah was last seen.

So what was John doing if he wasn't Elijah or the Messiah?

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

John's purpose was to reveal the Lamb of God to the Nation of Israel.
This Lamb--the Messiah--would take away the sins of that nation and the world.
Under the Old Covenant, once a year, the High Priest would make a sin offering for the sins of the whole nation.
But in the case of Christ, He was the sin offering.
He was the Lamb.
But who was the high priest that was going to sacrifice this Lamb?

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

Under the New Covenant, The High Priest and the sin sacrifice are one in the same.
This Great High Priest offered Himself once and for all.
The baptism of Aaron by Moses foreshadows the baptism of Jesus by John.
Moses baptized the first high priest under the Old Covenant.
John baptized The Great High Priest of the New Covenant.

The Ordination of Christ
------------------------

An interesting exchange takes place as Jesus comes to John to be baptized.
At first, John refuses to baptize Him.

Mat 3:14 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
________________

John was looking for the One who would baptize in the Spirit.
He wanted to be baptized by the Messiah, not the other way around.
The answer Jesus gives to John is insightful.

Mat 3:15 NKJV
________________
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

To fulfil what righteousness?
We have to remember that Christ was born under the Law and lived under the Law.
By His own words, He had come not to destroy the Law, but to fulfill or complete the Law (Mat 5:17).
The High Priest role and the sin offering of the Old Covenant are both fulfilled in Christ as the Mediator of the New Covenant.
But the Old Covenant was not something that instantly disappeared.
Even as late as in the book of Hebrews, which was written after both the resurrection of Christ and Penticost, the Old Covenant is described as being "ready to vanish away" (Heb 8:13).
That is, it had not yet vanished away.

There were three things that Moses did as he ordained the first high priest in Exodus 29.
First, he washed Aaron in water.
Washing in water is good hygiene but it was also required to be considered ceremonially clean under the Law.
Washing in water also symbolizes washing away sin.
Moses then took the priestly garments and clothed Aaron with them.
These garments were the uniform for the office of a priest.
They represented his new identity.
Symbolically the garments also represented righteousness.
The priest could not perform his work without having a righteous covering.
Finally, Moses took some oil and anointed Aaron with it.
Throughout scripture, oil is used symbolically to represent the Holy Spirit.

Matthew says that immediately after Jesus was baptized by John, the Holy Spirit was seen descending on Him like a dove.
The voice of the Heavenly Father was present acknowledging Him as His Son.
John performed the washing in water of this Priest.
The Heavenly Father performed the Spirit anointing this Priest.
But there is no mention of being clothed with the Priestly garments.
Christ did not need to put on righteousness; He was already righteous.
And he was the first to be baptized in the Spirit.
Everyone else had to wait until after Penticost.

In the baptism of Christ, we find both the fulfillment of the old and the first of the new.
He was both completing the Old Covenant priesthood and initiating the New Covenant priesthood.
Only the Heavenly Father could ordain this High Priest.
Christ as the Great High Priest is the first in a new order of priests that God was going to appoint under the New Covenant.
The Kingdom of Heaven is really a Kingdom of Priests.

The Work of the Great High Priest
---------------------------------

The baptisms of Christ were not complete at His ordination.
His most important baptism as Great High Priest was still future. Under the Old Covenant, there was a baptism or washing that was necessary as part of the ongoing work of the high priest. The same is true with the work of Christ.
But this baptism wasn't in water.
And once His work was finished, it was complete once and for all.

One day, James and John came to Jesus to ask a favor.
They wanted to sit at His right hand and left hand in the Kingdom.
They were asking for a position of great honor.
As it turns out, they were also asking for something else that went along with that position of honor.
Jesus answered their questions with another question.

Mat 20:22 NKJV
______________
"You do not know what you ask. Are you able to drink the cup that I am about to drink, and be baptized with the baptism that I am baptized with?"
______________

Is Jesus simply speaking of his baptism by John?
And He continues just a few verses down and makes the answer to this clear.

Mat 20:27-28 NKJV
______________
"And whoever desires to be first among you, let him be your slave--
just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many."
______________

The work of this High Priest was unlike any of the  priests that had come before Him.
His work was to lay down His life as the sacrifice for sin.
The Lamb without blemish.
This work was still future.

Luke 12:50 NKJV
______________
"But I have a baptism to be baptized with, and how distressed I am till it is accomplished!"
______________

James and John both became martyrs for their faith.
They shared this baptism with Christ.
Perhaps they actually received what they asked for.
They just didn't know what they were asking up front.

Baptize: The Word
-----------------

The challenge in arriving at a complete understanding of baptism is the fact that one work is used to refer to at least three different things.
Baptism can refer to the washing in water that was so intimately associated with the service of the Old Covenant.
Baptism can refer to the Spirit anointing that was required for service under the New Covenant.
But baptism can also refer to the work of The Great High Priest, the sacrificial death of Christ.

But we have not yet examined the actual word itself.
Is there perhaps something more we can learn about baptism from the word itself?
The Greek word for baptism is βαπτίζω (baptizo).
Vine's Expository Dictionary has this to say about it.

___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

The term "frequentative form" is a technical way of saying that the word signifies greater intensity or repeated action.
An excellent illustration of this found in the form of an ancient recipe from around 200 B.C.
The Greek poet and physician Nicander described the process of making pickles.
First, the vegetable must be dipped (bapto) in boiling water.
Then the vegetable must be baptized (baptizo) in vinegar.
Nicander used the same Greek word that is used for baptism in the New Testament.

What is it that makes a pickle a pickle?
Is it the fact that you observed it being baptized in vinegar?
Is it a label you read on the jar?
Or is it a pickle because you can taste the vinegar?
You can tell that the vinegar has actually become part of the pickle because you can taste it.

Water baptism was not a one-time event for a priest.
Yes, there was a baptism associated with his ordination, but washing in water was a very real part of his ongoing duties.
The washing was never done under the Old Covenant, because water could never truly wash away your sins.

Baptism in the Spirit as seen at Penticost was fundamentally different from anything seen in the Old Testament.
This anointing would not come and go; it was a permanent ongoing presence on the believer.

The baptism of Christ on the cross extended beyond the cross.
He was living this reality through His life leading up to that event.
In a sense, Christ died before He actually got to the cross.
He wasn't really killed by the cross, He willingly gave up His life as a sacrifice on the cross.

Baptized into Christ
--------------------

The Apostle Paul may be the greatest teacher on baptism in the New Testament.
No other writer explains in such depth the significance of baptism in light of the work of Christ.
But, he had this to say about his ministry in 1 Corinthians.

1Co 1:17 NKJV
_____________
For Christ did not send me to baptize, but to preach the gospel, not with wisdom of words, lest the cross of Christ should be made of no effect.
_____________

Paul was focused on preaching the gospel in a way that centered on the power of the cross.
By his own words, there were very few individuals that he had actually baptized himself, at least as far as the Corinthians were concerned (1 Cor 1:14-16).
Baptism in water was not foundational to his ministry.
Paul spoke extensively about the Spirit anointing and the gifts that followed.
But the anointing of the Spirit was not foundational to his ministry.

Paul's ministry was founded on a type of baptism that predated even the first high priest of the Old Covenant. This first baptism takes place shortly after Israel's first Passover.

1Co 10:1-2 NKJV
_______________
Moreover, brethren, I do not want you to be unaware that all our fathers were under the cloud, all passed through the sea
all were baptized into Moses in the cloud and in the sea,
_______________

When the children of Israel crossed over the Red Sea, they crossed over on dry ground.
The water was present, but it was kept on the sidelines.
The Spirit of God was present, symbolized by the cloud.
But the Spirit was above them, not directly upon them.
The this baptism "into Moses" was a dry baptism.
Israel was united with their leader in this event.
Together with their leader Moses they crossed over from slavery to freedom as they left Egypt.

Just like this first baptism of Israel into Moses, Paul's teaching on baptism is about the union of the believer with Christ.
It too, is a dry baptism.

Gal 3:27 NKJV
_____________
For as many of you as were baptized into Christ have put on Christ.
_____________

The Greek work for "put on" is actually the same word that can be translated "clothed".
To put on Christ is to be clothed in Christ.
Righteousness by faith is found only in Christ.
To be clothed in Christ is to be baptized.

In the book of Romans, Paul expands on the union that the believer shares with Christ through baptism.

Rom 6:3-6 NKJV
______________
Or do you not know that as many of us as were baptized into Christ Jesus were baptized into His death?
Therefore we were buried with Him through baptism into death, that just as Christ was raised from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been united together in the likeness of His death, certainly we also shall be [in the likeness] of [His] resurrection,
knowing this, that our old man was crucified with [Him], that the body of sin might be done away with, that we should no longer be slaves of sin.
______________

To be baptized into Christ is to be baptized into His death.
His death is the death of the cross.
Throughout the teaching of Paul, baptism and the cross are always closely associated.
They are like opposite sides of the same coin.

When Christ was baptized, the anointing of the Spirit fell on Him immediately after He was washed in water.
He was righteous when he was baptized.
There was no need for Him to first put on righteousness.
Everyone else had to wait until after His death, burial, and resurrection.
They had to first be clothed in Christ before they could be ordained as part of the New Covenant priesthood.
Penticost must come after Passover.

In announcing the Great Commission, Christ said very specifically that those who believed and were baptized would be saved (Mark 16).
He also that signs would follow those that believed.
This belief was faith in the Messiah and His sacrifice as the Lamb of God.
In the Great Commission, faith must come before baptism, whether it is water or Spirit.

Under the Old Covenant, water baptism was a perpetual activity.
The washing and the sacrificing would be repeated over and over again, but sin was never truly cleansed away.
Under the New Covenant, these ceremonial washings in water are complete.
Those with faith in Messiah washed in water one last time as a completion of the old.
And they were anointed in the Spirit as a firstfruits of the new.
For a Priest entering the New Covenant, faith, water, and spirit baptism were a package deal.
You cannot separate these and have a priest.

Complete in Christ
------------------

If we stop at the death and burial of Christ in our understanding of baptism, we have an incomplete picture. In the book of Colossians, Paul explains baptism to a slightly different audience than those addressed in Galatians and Romans. In this case, he is speaking to Gentile nations at large; these are people who had never been circumcised or baptized in water before. And he explains both of those practices in a new light.

Col 2:8-14 NKJV
_______________
Beware lest anyone cheat you through philosophy and empty deceit, according to the tradition of men, according to the basic principles of the world, and not according to Christ. 9 For in Him dwells all the fullness of the Godhead bodily; 10 and you are complete in Him, who is the head of all principality and power. 11 In Him you were also circumcised with the circumcision made without hands, by putting off the body of the sins of the flesh, by the circumcision of Christ, 12 buried with Him in baptism, in which you also were raised with [Him] through faith in the working of God, who raised Him from the dead. 13 And you, being dead in your trespasses and the uncircumcision of your flesh, He has made alive together with Him, having forgiven you all trespasses, 14 having wiped out the handwriting of requirements that was against us, which was contrary to us. And He has taken it out of the way, having nailed it to the cross.
_______________

Under the Old Covenant, two things were required for a Gentile to become a practicing Jew.
First, he would have to become circumcised. Second, he was required to take a full body bath.
In other words, he had to baptize.
But nether of these rituals is required to be complete in Christ.

The circumcision Paul is discussing here is accomplished without hands.
It was accomplished on the cross through the death of Christ.
It was the cutting off of the Christ.
If we are one with with Christ, when Christ died, we died.

If this circumcision is accomplished without human hands, does it not make total sense that this baptism is also performed without human hands? If we are baptized into the death of Christ, it means that when He was buried, we were buried.
But baptism doesn't stop with burial.
When He was raised, we were raised with Him.

Completeness in Christ is accomplished with a circumcision and a baptism not performed with human hands.
It is based solely upon His finished work.
This completeness is so complete it cannot even be improved upon with baptism after belief.
Washing in water or anointing with the Spirit doesn't change this.
It stands solely and completely on the sacrifice of Christ on the cross and the power of God who raised Him from the dead.

Priests and Soldiers
====================

We are complete in Christ based solely upon His finished work.
We can't add to or take away from that based upon what we do.
Does that mean baptism in water and anointing in the Spirit serve no purpose?

The problem with this thinking is that it is confusing something that is foundational with something that is vocational.
Baptism into the death, burial, and resurrection of Christ is absolutely foundational to any purpose of God.
We can't serve as part of the new creation in Christ without this baptism. But what follows after this is specific to the vocation that God has for you.
A priest isn't really a priest as far as the specifics of that role are concerned until ordination.
The tools of the trade are still required.
The question we should be asking is whether priesthood is the only vocation God has called believers into.

If you look at the book of Ephesians at a very high level, it can be split it into two halves.
In the first half, Paul explains the Work that Christ has done for us.
In the second half, Paul describes how we respond to the work of Christ through our day-to-day lives.
But in the book of Ephesians, Paul also reveals a new  vocation. 

Eph 4:1
_______
I, therefore, the prisoner of the Lord, beseech you to walk worthy of the calling with which you were called
_______

In the first half of the book, Paul lays the foundation for this new calling through the finished work of Christ on the cross.
In the second half, Paul describes what this vocation actually looks like in detail.

This vocation isn't the calling of a priest; it's the calling of a soldier. But each of the three steps of the calling of a priest are reflected here. Baptism into Christ is foundational to any vocation. The is the case  with the soldier. 

Eph 4:5
_______
one Lord, one faith, one baptism;
_______

The priest was washed before he was anointed.
The soldier is also washed, but the washing isn't in water, it is in the word.

Eph 5:26
________
That he might sanctify and cleanse it with the washing of water by the word,
________

Finally for a soldier to be a soldier, the armor must be put on.
Instead of being anointed in the Spirit like the priest, the soldier is armed in the Spirit.

Eph 6:11-17
____________
Put on the whole armor of God, that you may be able to stand against the wiles of the devil. ... And take the helmet of salvation, and the sword of the Spirit, which is the word of God;
____________

The soldier's weapon is the sword of the Spirit, the Word of God.

Within the nation of Israel, the priests in the tribe of Levi were not numbered in the census of Israel (Numbers 1).
This is because the priests had a special role that excluded them from going to war.
The soldier is not a priest.
And a priest cannot be a soldier.
Both together are needed to accomplish God's purpose.
There is one baptism that is foundational to both vocations, but the spiritual tools given to a soldier are different from those given to a priest.

Conclusion
==========

How does the fact that we have been baptized into the death, burial, and resurrection of Christ show through  our lives?

Is a priest defined by the spirit anointing and gifts?
The Corinthian believers had this anointing and they had the gifts of the Spirit to prove it.
But unfortunately there were many things going on within the Corinthian church that were not in line with the heart of God.
Paul even described them as "carnal".
You can be ordained and anointed as a priest, but you can still miss out when it comes to having the heart of a true priest.

Is a soldier defined by the armor and the use of the sword of the spirit?
The word of God can be used to build up and edify, but it can also be used to tear down.
How many soldiers use the sword in a way that pleases God?
How many of us have the heart of a true soldier?

The power and the wisdom of God are expressed through the cross, not in the various gifts He gives through the Spirit.
Paul was so changed by the cross that it had become part of his very identity.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

The cross caused Paul to look at the world differently.
The cross meant that Paul looked different to the world.
May we be able to say with Paul that the cross causes me to see the world differently.
And when others looks at me, they see the power and the wisdom of God at work.
