Baptism
=======

It's very easy for our minds to get fixated on a particular image for something.
This image can stick with us and continue to influence our thinking in ways we are not even aware of.
When we think of baptism, for instance, what is usually the first thing that pops into mind?
Perhaps something like this: https://www.google.ca/search?q=baptism&tbm=isch.

Even if we realize there is much more to baptism than this, it is very hard to shake that image.
But what if this was the first thing we though of when we heard the word baptism: https://www.google.ca/search?q=cross&tbm=isch.
How would this impact our our lives?
How would Christianity be different?
How would this impact the world?

John the Baptist
----------------

It would be easy to think that water baptism is something that was first instituted by John the Baptist.
After all, this was a big part of his ministry along the banks of the Jordan river.
It is probably what he has become most widely known for.
So much so, that it's a permanent part of his name.

But baptism in water was present throughout the Old Testament.
It was intimately associated with the tabernacle and the duties of the priests.

Heb 9:9-10 KJV
______________
[The Tabernacle] Which [was] a figure for the time then present, in which were offered both gifts and sacrifices, that could not make him that did the service perfect, as pertaining to the conscience;
[Which stood] only in meats and drinks, and divers washings, and carnal ordinances, imposed [on them] until the time of reformation.
______________

The word translated "washings" is the Greek word for baptism.
We could quite correctly say that these "diverse washings" where "diverse baptisms" required under the ceremonial law.
In fact, washing in water was required both at the initial consecration of a priest and during his ongoing day-to-day service in the tabernacle.

The initial washing or cleansing of a Priest was special; it was different from the rest.
Back in Exodus, it was Moses who performed the first consecration of Aaron and his sons.

Exo 29:4 KJV
_____________
And Aaron and his sons thou shalt bring unto the door of the tabernacle of the congregation, and shalt wash them with water.
_____________

The word for wash in the Hebrew is *rachats*.
It can mean taking a full body wash like a bath or just washing your hands, depending upon the situation.
This initial priestly cleansing performed by Moses was like a full body wash, not just a washing of hands and feet.
And Aaron and his sons did not do the washing, it was Moses who did the washing.
Or put another way, as part of the ordination of this first high priest, Moses baptized Aaron in water.

After this initial washing in water, a priest was required to wash himself before performing any service in the tabernacle.
This ongoing washing was performed by the priest himself. And it did not necessarily involve washing the entire body.

Exo 30:20 KJV
_____________
When they go into the tabernacle of the congregation, they shall wash[H7364] with water, that they die not; or when they come near to the altar to minister, to burn offering made by fire unto the LORD:
_____________

No doubt this was very serious stuff. The consequence of not washing before coming near the altar was death.
Imagine going into work each day and being greeted by a sign on the wall that said "wash your hands or die!".
You can see how it might be possible to get carried away with this and start washing a few extra times just to be sure you're safe.
While washing in water was an important required part of the ceremonial law given by God, it had been embellished and built upon with religious traditions.
You can see this especially with groups like the Pharisees, who had become somewhat obsessed with ritual washing.

Fast forward to John the Baptist.
John was preaching a message of repentance.
People were coming to him to be baptized.
They weren't baptizing or washing themselves in water, they were being baptized by John.
And they weren't going up to the temple to wash, they were going out to the banks of the Jordan river.

When the Pharisees heard of this, they sent someone to investigate (John 1:25).
It wasn't the fact that he was baptizing with water that was puzzling to them.
It was the fact that he was the one performing the baptism.
As far as we know, the last time somebody was baptized by someone else was when Moses baptized Aaron.
They were wondering why he was performing baptisms if he wasn't the Messiah, Elijah because they expected this to be done by Elijah or the Messiah.

The location where John was baptizing was also significant.
John was likely performing his baptisms near Bethabara, a location deeply connected with the history of Israel (https://en.wikipedia.org/wiki/Bethabara).
This was near the historical location of Jerico, so it would not have been far from where Joshua and the children of Israel crossed the Jordan Riveer on their way into the promised land.
It is also rumored to be the last location where the prophet Elijah was seen before he was taken up into heaven.
So you have someone doing what was expected of Elijah in the location where Elijah was last seen.
No wonder the religious leaders were taking notice.

But why was John baptizing?
What was the significance or the meaning of it?
John himself answers this question for us.

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

John's purpose was to reveal the Lamb of God to the Nation of Israel.
This Lamb--the Messiah--would take away the sins of that nation and the world.
Under the Old Covenant, once a year, the High Priest would make a sin offering for the sins of the whole nation.
But in the case of Christ, He is the sin offering.
He is the Lamb.
But who was the High Priest that was going to perform this sacrifice?

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

Under the New Covenant, The High Priest and the sin sacrifice are one in the same.
This Great High Priest offered Himself once and for all.
The baptism of Aaron by Moses was a precursor to the baptism of Jesus by John.
Moses baptized the first high priest under the Old Covenant.
John baptized The Great High Priest of the New Covenant.

John's Baptism of Christ
------------------------

An interesting exchange happens when Jesus comes to John to be baptized.
At first, John refuses to baptize Him.

Mat 3:14-15 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

To fulfil what righteousness?
We have to remember that Jesus was born under the Law and lived under the Law.
By His own words, He had not come to destroy the Law, but to fulfill or complete the Law (Mat 5:17).
The High Priest role and the sin offering of the Old Covenant are both fulfilled in Christ as the Mediator of the New Covenant.
But the Old Covenant was not something that instantly disappeared.
Even as late as in the book of Hebrews, which was written after both the resurrection of Christ and Penticost, the Old Covenant is described as being "ready to vanish away" (Heb 8:13).
That is, it had not yet vanished away.

How was the first High Priest ordained under the Old Covenant?
There were three things that Moses specifically did in Exodus 29.
First, he washed Aaron in water.
Washing in water was required for physical cleanliness under the law.
It was good hygiene but it was also required to be considered ceremonially clean.
Washing in water also symbolizes washing away sin and sickness.
Then, he then took the priestly garments and placed them on Aaron.
The garments symbolize putting on righteousness.
Finally, he took some oil and anointed Aaron with it.
Throughout scripture, oil is used symbolically to stand for the Holy Spirit.

Let's think about Christ's baptism in this light.
Matthew says that immediately after Jesus was baptized by John, the Spirit was seen descending on Him like a dove (REF).
The dove with the voice from heaven indicate the Spirit anointing of the Christ.
But in this case, the Spirit anointing followed immediately after the baptism in water.
What's missing?
There is no mention of changing into the Priestly garments.
Christ did not need to put on righteousness; He was already righteous.

Jesus was the first one to be baptized in the Spirit.
But everyone else who was baptized in the Spirit had to first put on righteousness.
They had to wait until after His death, burial, and resurrection.
Only then by putting on the righteousness by faith in Christ they could receive the gift of the Spirit.

The Baptism of Christ is the Ordination of Christ as the Great High Priest.
We can see both the completion of the old and the foretaste of the new in the baptism of Christ.
The washing in water performed by John for a Priest was present.
The anointing in the Spirit was a foretaste of the New Covenant.
Jesus was simultaneously completing the Old Covenant preisthood while He was becoming High Priest of the New Covenant.
Only the Heavenly Father could actually appoint this High Priest.
The voice of the Father was present with the Spirit.

The Ordination of Christ as the Great High Priest is a picture of what God wanted to do on a larger scale with the Nation of Israel.
Peter understood this and taught this.

1Pe 2:9 NKJV
____________
But you [are] a chosen generation, a royal priesthood, a holy nation, His own special people, that you may proclaim the praises of Him who called you out of darkness into His marvelous light;
____________

What God did with the tribe of Levi under the Old Covenant was a picture of what He planned to do on a much larger scale with the Nation of Israel under the New Covenant.
The Kingdom of Heaven is really a Kingdom of Priests.
Christ's ministry to Israel was focused on preparing them to embrace this priestly role as a nation.
This perspective sheds new light on both the Great Commission (Mar 16:15-18) and Penticost (Acts 2).
Both of these events are closely related to the Ordaining of the Nation of Priests.
Once this Nation was Ordained, it would be used by God to preach the Gospel throughout the world.


The Last Baptism of Christ
--------------------------

Remember how Aaron was baptized by Moses when he was ordained as the first high priest?
But after that, there was washing or baptism that was necessary as part of his work as high priest.
We see the same pattern with Christ, the Great High Priest of the New Covenant.
Only the baptism that was a part of His work is far different from any washing in water.
Christ Himself has this to say about it.

Luk 12:50 NKJV
______________
"But I have a baptism to be baptized with, and how distressed I am till it is accomplished!"
______________

This statement was made well after He was baptized by John the Baptist.
Whatever this baptism was, it was a source of stress or distress.
We can piece this together with what Matthew and Mark record to get a better picture.

James and John came to Jesus to ask a favor.
They wanted to sit at His right hand and left hand in the Kingdom.
They were asking for a position of great honour.
And, as it turns out, they didn't really understand the magnitude of what they were asking for.

Mat 20:22 NKJV
______________
"You do not know what you ask. Are you able to drink the cup that I am about to drink, and be baptized with the baptism that I am baptized with?"
______________

And He continues just a few verses down.

Mat 20:27-28 NKJV
______________
"And whoever desires to be first among you, let him be your slave--
just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many."
______________

According to tradition, James and John both became martyrs for their faith.
This was a baptism that they shared with Christ that was above and beyond any water baptism or spirit anointing.
They sacrificed everything for their faith.
It is this baptism that Christ had this is foundational to His work as a Priest.
But as we will see, it is even bigger than that.
It's foundational to the new creation, to everying that God is setting out to ultimately achieve in the redeemed universe.

Baptism: The Word
-----------------

It's critical to understand the difference between two words in the Greek: "to dip" vs "to baptize".

The Greek word for baptism is βαπτίζω (baptizo).

Vine's Expository Dictionary of New Testament Words
___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

So while baptize can be used to describe dipping something into water, it implies more than that.
There is no better illustration of this than pickles!

https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?strongs=G911&t=KJV
_________
Not to be confused with 907, baptizo. The clearest example that shows the
meaning of baptizo is a text from the Greek poet and physician Nicander, who
lived about 200 B.C. It is a recipe for making pickles and is helpful because
it uses both words. Nicander says that in order to make a pickle, the vegetable
should first be 'dipped' (bapto) into boiling water and then 'baptised'
(baptizo) in the vinegar solution. Both verbs concern the immersing of
vegetables in a solution. But the first is temporary. The second, the act of
baptising the vegetable, produces a permanent change.
_________

Being baptized into something means to be so affected that there is a lasting change that takes place.
Often, the emphasis is placed on the act rather than the change, or on the symbolism of the act rather than the act itself.
How would we understand baptism if we focus on the change brought about by it?
The key is understanding that there are different baptisms in Scripture.
And the change brought about by each of those baptisms is different.

Baptism in water was required to become a Priest under the Old Covenant.
And it was required as part of the priestly duties under penality of death.
Spirit anointing or spirit baptism was essential to serve under the New Covenant.
Misusing this gift could result in sickness or death.
True scriptural baptism is never optional.
True scriptural baptism always produces a change.

Baptized into Christ
--------------------

The last baptism of Christ was the defining work of His role as High Priest.
As High Priest He offered Himself on the cross as a sacrifice for sin once and for all.
Baptism and the cross are intimately related with each other.
In fact, these two concepts are so closely tied together that we might say they are flip sides of the coin.

In the book of Romans, Paul lays out the foundational basis that the baptism of Christ forms.

Rom 6:3-6 KJV
___________
Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?
Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been planted together in the likeness of his death, we shall be also [in the likeness] of [his] resurrection:
Knowing this, that our old man is crucified with [him], that the body of sin might be destroyed, that henceforth we should not serve sin.
___________

It's in the book of Galations that Paul brings out the radical change that is associated with baptism.

Gal 3:27 NKJV
_____________
For as many of you as were baptized into Christ have put on Christ.
_____________

Compare baptized into Christ with baptized into Moses.
Water isn't required in either case (but it may be present).

Col 2:10-12 KJV
_________________
And ye are complete in him, which is the head of all principality and power:
In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:
Buried with him in baptism, wherein also ye are risen with [him] through the faith of the operation of God, who hath raised him from the dead.
_________________

Paul is addressing all nations on a level playing field in the book of Colossians.
He is not saying "to the Jew First" like he does in Romans.
He is speaking to people here who were never circumcised.
Under the Old Covenant, both circumcision and baptism in water (the mikvah) were required for a Gentile that wanted to become a practicing Jew.
But the circumcision done here is performed without hands. It is the circumcision of Christ.
Does it not make total sense that the baptism done here is also without hands?

The baptism here is something so central to the gospel that it was common to both the believing Jew and the believing Gentile,
quite apart from any circumcision or washing of the flesh.
In fact, it is through the "operation of God".
Only God can perform this baptism.
This baptism is done (past tense), but it is entered into (present tenst) by faith.

Notice how the words baptism and cross both pop out in Rom 6 and Col 2.
Baptism and the cross are like flip sides of the coin.
Baptism into Christ is baptism into His death.
The significance of the cross is that it is how the death was accomplished.

Baptism into the death of Christ cannot be done by us; it can only be done by God.
But embracing the message of the cross in our daily lives is something that is done by us.
This is evidence in the present to us and to others that our baptism is in fact real.
The cross points back to this but also symbolizes the active change that is taking place here and now in our lives to reflect this fact.
The cross symbolizes both a completed reality and an present change and a future change.
The future change is when the old creation is permanently replaced by the new.
The present change in our lives today is the work of the Spirit (the Word) filling us and changing us.

The structure of Galatians centers around baptism into Christ and the Cross:

- A: Gal 2:20: Paul crucified with Christ. Christ living in him.
- B: Gal 3:1: The Galatians had a clear example of Christ crucified.
- C: Gal 3:27-28: Baptized into Christ, distinction gone, all one in Christ Jesus
- B: Gal 5:24: They that are Christ's have crucified the flesh
- A: Gal 6:14: The world has crucified to Paul. The New Creation.

How was it that the Galatians has a clear example of Christ crucified set before them?
This was through the preaching and life of Paul. Because he was baptized into the death of Christ and had embraced the cross.
Paul made this evident through his life because this had become Paul's identity.
One of the disciples came to Jesus while He was on earth and asked to see the Father.
How did Jesus reply?
"Have I been with you so long, and yet you have not known Me, Philip? He who has seen me has seen the Father." (John 14:9)
In effect, Paul is saying a similar thing here.
If you have seen me (Paul), you have seen Christ.

What was Paul talking about here?
What does Christ crucified look like?
Is it powerful signs and wonders?
Paul used this example to confront issues in the Corinthian church.
Communion and its consequences, the spirit gifts, baptized into one body.
These had the baptism of the spirit. They had the gifts.
But they didn't understand the message of the cross.
Much like the Children of Israel in the Old Testament were baptized into Moses but died in the wilderness.
They were ordained priests under the New Covenant and had the spirit anointing to prove it.
Much like the priests under the Old Covenant, misusing the calling and gifts had serious consequences.
May were ill and some even died.
Paul says to have all of that but still not have love means you are nothing.
Another way we could say this is if you have been Ordained under the New Covenant, but you don't understand
the cross or its meaning for your life, it's kind of all for nothing.

Paul explains what embracing the cross looks like in a somewhat puzzling passage in 1 Cor.

1Co 15:29 KJV
____________
Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?
____________

Paul is asking: why would someone be baptized "for the dead" if there is no resurrection of the dead.
What does being baptized "for the dead" mean?
The phrase in the Greek can mean over as in position or also in place of.

Commonly, this verse is understood as a reference to a practice of either baptizing the dead or getting baptized in the place of a dead person.
But it is a bit strange to assume this given there is no hint of this anywhere else in this book.
Why would Paul randomly refer to a practice not found anywhere else in the Bible when he is trying to defend the truth of the resurrection?
It makes much more sense here if Paul is actually speaking of the same thing in v29 - v32.
Paul mentions that he fought with wild beasts a few verses down.
The criminals and Christians were at that time thrown before wild beasts (research more).
How many died in these very area floors for their faith?
Paul could be referring to those that were baptized over the same place as these dead.
This lifestyle of dying daily was the outcome of Paul embracing the message of the cross.
This word "for" or "over" is the Greek word "hyper" and can mean "above" or "beyond".
I think Paul is speaking of being baptized beyond death: "I die daily".

The miracles performed by Jesus are not the ultimate expression of the power and the wisdom of God.
And the sign gifts of Spirit anointing are only temporary.
They are passing away as Paul says in 1 Cor 13.
If you have been baptized in water and anointed with the spirit, but you don't have love, you are nothing.
Its not the physical act of dying that is central to the cross in practical application.
Paul says that if you give your body to be burned but don't have love, you are nothing.
This sacrifice is only acceptable to God if it is done willingly.
Can you do something willingly if you don't have a choice?
I think there is the very real possibility that those that God calls to be martyrs also have choice (Heb 11:35).
Did Christ die because He was nailed to a cross and couldn't escape?
No, He died because He willingly gave Himeself up.
That is the power and the wisdom of God in the cross.
It is getting to the point of being able to willingly let go of everything.

Paul was so changed by the cross that it had become part of his very identity.
When he preached the cross, he also lived out the power and wisdom of God in his very life.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

The cross caused Paul to look at the world differently.
The cross meant that Paul looked different to the world.
These two things together are the strongest evidence of the reality of baptism into Christ in our daily lives.

While the Great Commission from Mark chapter 16 seems to get a lot of attention today, this message of the cross is truly core to being a follower of Christ.
How critical it is to understand the Great Commission in light of something else Christ said.
It's one thing to be ordained as a priest, it's a totally different thing to follow Christ and embrace the cross in your life.

Mar 8:34 KJV
____________
And when he had called the people [unto him] with his disciples also, he said unto them, Whosoever will come after me, let him deny himself, and take up his cross, and follow me.
____________

He's speaking to those who were already disciples.
But Christ is letting them into the deeper truth of what it really means to follow Him.

The One Baptism
---------------

We have seen that a full scriptural understanding of baptism requires that we distinguish between washing in water, being anointed by the spirit, and being baptized into the death, burial, and resurrection of Christ.
But Paul takes this one step further when summarizing the unity of the Spirit in Ephesians chapter 4:

Eph 4:4-6 KJV
_____________
[There is] one body, and one Spirit, even as ye are called in one hope of your calling;
One Lord, one faith, one baptism,
One God and Father of all, who [is] above all, and through all, and in you all.
_____________

How can Paul say there is only one baptism when we clearly saw that there are at least three?
Context.
Looking just a few verses down, Paul clearly defines the context for this.

Eph 4:22-24
___________
Put off ... the old man (anthropos) ... be renewed ... put on the new man (anthropos).
___________

The word for man here isn't referring to a male specifically.
It's the word anthropos that is used to refer to a human being, whether male or female.
In other words, we could say

___________
Put off ... the old humanity ... be renewed ... put on the new humanity.
___________

Or perhaps

___________
Put off ... the old creation ... be renewed ... put on the new creation.
___________

Remember that baptism in its truest sense always involves a change.
The change here is from the old creation to the new creation.
Just like the priesthood under the Old Covenant was first established with Moses baptizing Aaron and his sons.
Just like the new priesthood under the New Covenant that John the baptist was proclaiming.
Baptism is also deeply connected with identity.
Ephesians chapter 2 helps shed more detailed light on the new anthropos.

In some ways, you can think of all prior baptims being fulfilled or brought to completion in this One Baptism.

Eph 2:11-18 KJV
_______________
Wherefore remember, that ye [being] in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;
That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:
But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.
For he is our peace, who hath made both one, and hath broken down the middle wall of partition [between us];
Having abolished in his flesh the enmity, [even] the law of commandments [contained] in ordinances; for to make in himself of twain one new man, [so] making peace;
And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:
And came and preached peace to you which were afar off, and to them that were nigh.
For through him we both have access by one Spirit unto the Father.
_______________

|========
| Eph 4                 | Eph 2
| One Body              | reconcile both unto God in one body (v16)
| One Spirit            | access by one Spirit to the Father (v18), habitation of God through the Spirit (v22)
| One Lord              | holy temple in the lord (v21)
| One Faith             | Saved through faith (v8)
| One Baptism           | Made both one (v14), One new anthropos (v15), by the cross (v16)
| One God and Father    | Access by one Spirit to the father (v18)
|========

The cross separates the old creation from the new creation.
It is impossible to be a part of the New Creation without baptism into Christ.
Christ is the Head of this creation much like Adam was the head of the old.
The only path to the new creation is through the death, burial, and resurrection of Christ.
Without baptism into the death of Christ, it is not possible to have any part of the new creation.
This baptism is foundational to any good news of the new creation.
And it is a baptism that is done by God, not by human hands (Col 2).

The distinctions and divisions of the old creation simply do not translate into the new creation.
Fleshly distinctions and differences are part of the old creation and end at the cross.
Gender, race, religion.
Your gender or race does not determine where you fit within the new creation in Christ.
It is the calling of God that determines where you fit in the New Creation.

The glimpses into the new creation we get in Scripture are few and far between.
Both John and Paul have the curtains peeled back a bit for a revelation.

John sees the Bride.
Paul sees the Husband.

|========
| Old Anthropos     | New Anthropos
| Adam              | Christ
| Adam & Eve        | Head & Body
| Israel & Nations  | Bride & Husband
|========

We are getting a glimpse into the new Anthropos that God created in Christ.
Our true identity is found not under the old creation but within the new creation.
And that identity is based on the calling of God and the work of Christ, not on gender, race, or religion.
All purposes in the New Creation start with the baptism into the death of Christ.
The New Creation reveals the manifold wisdom of God (Eph 3:10).

When we are baptized into the death of Christ, we are so impacted by the message of the cross that it changes us.
Even while we are still a part of the old creation today, we have been touched by the New Creation in such a way that it has permanently changed us.
We have been baptized into Christ and He is now a permanent part of us.
The cross is how the old creation is touched, infused, and changed by the new.
This One Baptism is the the only universal all encompassing baptism.
All others are temporary in nature or limited in scope, much like the Old Covenant and New Covenant.

1. Old Covenant: water baptism: temporary, called of Israel according to flesh
2. New Covenant: spirit baptism: eternal, called of Israel according to spirit
3. New Anthropos: baptism into death of Christ: eternal, all the called in Christ (Bride and Husband)

Baptism and the cross are like opposite sides of the coin.
All of the reasons people feel the need to be baptized in water can be answered in the cross.

What is the defining characteristic of the New Creation? Love.
How do we remember and honour the work of Christ in our lives today?
How do we show evidence of this to others?
Is it through an outward washing ceremony? Or is it by being shaped by the cross in our daily lives?
