Baptism
=======

When you hear the word baptism, what kind of picture enters your mind?
Often it will be something along these lines: https://www.google.ca/search?q=baptism&tbm=isch.
But why is water so strongly associated with the word baptism?

There is an equally valid and even more powerful image that we can  associate with the word baptism:
https://www.google.ca/search?q=cross&tbm=isch.

How often is the cross the first image that enters your mind when you hear the word baptism?
How could this change how we look at the world?
How could this change how the world sees us?

John the Baptist
----------------

One of the main reasons water has become so strongly linked with baptism is a result of the ministry of someone who came before Jesus.
He is so widely known for water baptism, it has become a permanent part of his name.
He even baptized Jesus in water.
He is, of course, John the Baptist.
It may be tempting to think that John the Baptist was the one who established water baptism.
This is what he was doing along the banks of the Jordan river.

But baptism in water goes much further back in time.
It was present throughout the Old Testament.
It was, in fact, intimately associated with the Tabernacle and the duties of the priests.
In Hebrews, We read this about the Tabernacle.

Heb 9:9-10 NKJV
_______________
It [was] symbolic for the present time in which both gifts and sacrifices are offered which cannot make him who performed the service perfect in regard to the conscience--
[concerned] only with foods and drinks, various washings, and fleshly ordinances imposed until the time of reformation.
_______________

The word translated "washings" is the Greek word for baptism.
We could quite correctly say that these "various washings" where "various baptisms" required under the ceremonial law.
For a priest, washing was no one-time event; it was a way of life.
Washing in water was required both at the ordination of a priest and during his ongoing day-to-day service in the Tabernacle.

The very first ordination of a high priest recorded in scripture is unique.
Moses ordained Aaron as the first high priest under the Old Covenant.
We read about this in Exodus.

Exo 29:4 NKJV
_____________
And Aaron and his sons you shall bring to the door of the tabernacle of meeting, and you shall wash them with water.
_____________

The initial washing or cleansing of a Priest was special; it was different from the rest.
The Hebrew word used here for wash can mean taking a full body wash like a bath or just washing your hands, depending upon the situation.
When a priest was ordained, he was required to take a full body wash.
He had to bathe himself, not just wash his hands or feet.

But in this case, Aaron did not do the washing; Moses washed Aaron.
In other words, Moses baptized Aaron as the first high priest.

After this initial washing in water, a priest was required to wash himself before performing any service in the tabernacle.
This ongoing washing was performed by the priest himself. And it did not necessarily involve washing the entire body.

Exo 30:20 NKJV
______________
When they go into the tabernacle of meeting, or when they come near the altar to minister, to burn an offering made by fire to the LORD, they shall wash with water, lest they die.
______________

No doubt this was very serious stuff. The consequence of not washing before coming near the altar was death.
Imagine going into work each day and being greeted by a sign on the wall that said "wash your hands or die!".
You can see how it might be possible to get carried away with this and start washing a few extra times just to be sure you're safe.
While washing in water was an important required part of the ceremonial law given by God, it had been embellished and built upon with religious traditions.
You can see this especially with groups like the Pharisees, who had become somewhat obsessed with ritual washing.

Fast forward to John the Baptist.
John was preaching a message of repentance.
People were coming to him to be baptized.
They weren't baptizing or washing themselves in water, they were being baptized by John.
And they weren't going up to the temple to wash, they were going out to the banks of the Jordan river.

When the Pharisees heard of this, they sent someone to investigate (John 1:25).
It wasn't the fact that he was baptizing with water that was puzzling to them.
It was the fact that he was the one performing the baptism.
As far as we know, the last time somebody was baptized by someone else was when Moses baptized Aaron.
They were wondering why he was performing baptisms if he wasn't the Messiah, Elijah because they expected this to be done by Elijah or the Messiah.

The location where John was baptizing was also significant.
John was likely performing his baptisms near Bethabara, a location deeply connected with the history of Israel (https://en.wikipedia.org/wiki/Bethabara).
This was near the historical location of Jerico, so it would not have been far from where Joshua and the children of Israel crossed the Jordan Riveer on their way into the promised land.
It is also rumored to be the last location where the prophet Elijah was seen before he was taken up into heaven.
So you have someone doing what was expected of Elijah in the location where Elijah was last seen.
No wonder the religious leaders were taking notice.

But why was John baptizing?
What was the significance or the meaning of it?
John himself answers this question for us.

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

John's purpose was to reveal the Lamb of God to the Nation of Israel.
This Lamb--the Messiah--would take away the sins of that nation and the world.
Under the Old Covenant, once a year, the High Priest would make a sin offering for the sins of the whole nation.
But in the case of Christ, He is the sin offering.
He is the Lamb.
But who was the High Priest that was going to perform this sacrifice?

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

Under the New Covenant, The High Priest and the sin sacrifice are one in the same.
This Great High Priest offered Himself once and for all.
The baptism of Aaron by Moses was a precursor to the baptism of Jesus by John.
Moses baptized the first high priest under the Old Covenant.
John baptized The Great High Priest of the New Covenant.

The Ordination of The Great High Priest
---------------------------------------

An interesting exchange happens when Jesus comes to John to be baptized.
At first, John refuses to baptize Him.

Mat 3:14-15 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

To fulfil what righteousness?
We have to remember that Jesus was born under the Law and lived under the Law.
By His own words, He had not come to destroy the Law, but to fulfill or complete the Law (Mat 5:17).
The High Priest role and the sin offering of the Old Covenant are both fulfilled in Christ as the Mediator of the New Covenant.
But the Old Covenant was not something that instantly disappeared.
Even as late as in the book of Hebrews, which was written after both the resurrection of Christ and Penticost, the Old Covenant is described as being "ready to vanish away" (Heb 8:13).
That is, it had not yet vanished away.

How was the first High Priest ordained under the Old Covenant?
There were three things that Moses specifically did in Exodus 29.
First, he washed Aaron in water.
Washing in water was required for physical cleanliness under the law.
It was good hygiene but it was also required to be considered ceremonially clean.
Washing in water also symbolizes washing away sin and sickness.
Then, he then took the priestly garments and placed them on Aaron.
The garments symbolize putting on righteousness.
Finally, he took some oil and anointed Aaron with it.
Throughout scripture, oil is used symbolically to stand for the Holy Spirit.

Let's think about Christ's baptism in this light.
Matthew says that immediately after Jesus was baptized by John, the Spirit was seen descending on Him like a dove (REF).
The dove with the voice from heaven indicate the Spirit anointing of the Christ.
But in this case, the Spirit anointing followed immediately after the baptism in water.
What's missing?
There is no mention of changing into the Priestly garments.
Christ did not need to put on righteousness; He was already righteous.

Jesus was the first one to be baptized in the Spirit.
But everyone else who was baptized in the Spirit had to first put on righteousness.
They had to wait until after His death, burial, and resurrection.
Only then by putting on the righteousness by faith in Christ they could receive the gift of the Spirit.

The Baptism of Christ is the Ordination of Christ as the Great High Priest.
We can see both the completion of the old and the foretaste of the new in the baptism of Christ.
The washing in water performed by John for a Priest was present.
The anointing in the Spirit was a foretaste of the New Covenant.
Jesus was simultaneously completing the Old Covenant preisthood while He was becoming High Priest of the New Covenant.
Only the Heavenly Father could actually appoint this High Priest.
The voice of the Father was present with the Spirit.

The Ordination of Christ as the Great High Priest is a picture of what God wanted to do on a larger scale with the Nation of Israel.
Peter understood this and taught this.

1Pe 2:9 NKJV
____________
But you [are] a chosen generation, a royal priesthood, a holy nation, His own special people, that you may proclaim the praises of Him who called you out of darkness into His marvelous light;
____________

What God did with the tribe of Levi under the Old Covenant was a picture of what He planned to do on a much larger scale with the Nation of Israel under the New Covenant.
The Kingdom of Heaven is really a Kingdom of Priests.
Christ's ministry to Israel was focused on preparing them to embrace this priestly role as a nation.

The Work of the Great High Priest
---------------------------------

Remember how Aaron was baptized by Moses when he was ordained as the first high priest?
But after that, there was washing or baptism that was necessary as part of his work as high priest.
We see the same pattern with Christ, the Great High Priest of the New Covenant.
Only the baptism that was a part of His work is far different from any washing in water.
Christ Himself has this to say about it.

Luk 12:50 NKJV
______________
"But I have a baptism to be baptized with, and how distressed I am till it is accomplished!"
______________

This statement was made well after He was baptized by John the Baptist.
Whatever this baptism was, it was a source of stress or distress.
We can piece this together with what Matthew and Mark record to get a better picture.

James and John came to Jesus to ask a favor.
They wanted to sit at His right hand and left hand in the Kingdom.
They were asking for a position of great honour.
And, as it turns out, they didn't really understand the magnitude of what they were asking for.

Mat 20:22 NKJV
______________
"You do not know what you ask. Are you able to drink the cup that I am about to drink, and be baptized with the baptism that I am baptized with?"
______________

And He continues just a few verses down.

Mat 20:27-28 NKJV
______________
"And whoever desires to be first among you, let him be your slave--
just as the Son of Man did not come to be served, but to serve, and to give His life a ransom for many."
______________

The work of this High Priest was unlike that of any of the other priests under the Old Covenant.
Doesn't it make sense that the baptism associated with that work was different too?

According to tradition, James and John both became martyrs for their faith.
This was a baptism that they shared with Christ that was above and beyond any water baptism or spirit anointing.
They sacrificed everything for their faith.
It is this baptism that Christ had this is foundational to His work as a Priest.
But as we will see, it is even bigger than that.
It's foundational to the new creation, to everything that God is setting out to ultimately achieve in the redeemed universe.

Baptize: The Word
-----------------

The challenge in arriving at a complete understanding of baptism is the fact that one work is used to refer to at least three different things.
Baptism can refer to the washing in water that was so intimately associated with the service of the Old Covenant.
Baptism can refer to the Spirit anointing that was required for service under the New Covenant.
But baptism can also refer to the work of The Great High Priest, the sacrificial death of Christ.

But we have not yet examined the actual word itself.
Is there perhaps something more we can learn about baptism from the word itself?
The Greek word for baptism is βαπτίζω (baptizo).
Vine's Expository Dictionary has this to say about it.

___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

The term "frequentative form" is a technical way of saying that the word signifies greater intensity or repeated action.
An excellent illustration of this found in the form of an ancient recipe from around 200 B.C.
The Greek poet and physician Nicander described the process of making pickles.
First, the vegetable must be dipped (bapto) in boiling water.
Then the vegetable must be baptized (baptizo) in vinegar.
Nicander used the same Greek word that is used for baptism in the New Testament.

What is it a pickle a pickle?
Is it the fact that you observed it being dipped into vinegar?
Is it a label on the jar?
Or is it a pickle because you can taste the vinegar?

Water baptism was not a one-time event for a priest.
Yes, there was a baptism associated with his ordination, but washing in water was a very real part of his ongoing duties.
The washing was never done under the Old Covenant, because water could never truly wash away your sins.

Baptism in the Spirit as seen at Penticost was fundamentally different than anything seen in the Old Testament.
This anointing would not come and go; it was a permanent ongoing presence on the believer.
The baptism

The baptism that Christ went through as part of His great sacrifice was no just a one-time even on the Cross.
It was something He was living in His life leading up to that event.
In a sense, Christ died before He actually got to the cross.
The significance of the sacrifice was not that He was killed on the cross.
It was that He willingly gave up His life; He sacrificed Himself.
That's the baptism that James and John ultimately shared with Him.

Baptized into Christ
--------------------

The Apostle Paul may be the greatest teacher on baptism in the New Testament.
No other writer explains in such depth the significance of baptism in light of the work of Christ.
This great teacher on baptism had this to say about his ministry in 1 Corinthians.

1Co 1:17 NKJV
_____________
For Christ did not send me to baptize, but to preach the gospel, not with wisdom of words, lest the cross of Christ should be made of no effect.
_____________

The greatest teacher on baptism wasn't set to baptize.
What is this gospel that Paul was preaching?
It was the good news of righteousness by faith.
This was always front and center in the ministry of Paul, whether he was preaching to the Jews or the Gentiles.
The book of Romans is nothing short of a masterpiece on this topic.

The importance of righteousness was something that was emphasized symbolically even under the Old Covenant.
When a high priest was ordained, he was required to do something after he washed in water but before he was anointed with oil.
He had to put on the priestly garments.
These garments were like the uniform for the office of a priest.
They represented his new identity as a priest.

But more significantly, they were symbolic of righteousness.
The priest was not righteous in and of himself; he had to put on the garments that symbolized righteousness before he could do his work.
The righteousness that we put on is found in Christ alone.

Gal 3:27 NKJV
_____________
For as many of you as were baptized into Christ have put on Christ.
_____________

Being baptized into Christ means you have put on Christ.
The Greek work for "put on" is actually the same word that can be translated "clothed".
To put on Christ is to be clothed in Christ.
Paul is speaking about a change of clothing.

This baptism is not something that can be accomplished by water or even by Spirit anointing.
Paul is talking about something much deeper and more significant when he says "baptized into Christ".
If you are going to change your clothes, what has to happen before you can put on the new clothes?
The old clothes have to be removed.
This is the foundation that Paul lays in the book of Romans and then builds on in the book of Galatians.

Rom 6:3-6 NKJV
______________
Or do you not know that as many of us as were baptized into Christ Jesus were baptized into His death?
Therefore we were buried with Him through baptism into death, that just as Christ was raised from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been united together in the likeness of His death, certainly we also shall be [in the likeness] of [His] resurrection,
knowing this, that our old man was crucified with [Him], that the body of sin might be done away with, that we should no longer be slaves of sin.
______________

Being baptized into Christ means we have been baptized into His death.
Even more than that, it means we have been buried with Him through baptism.
But this baptism doesn't leave us dead.
What follows is being raised from the dead to a newness of life.

Throughout the teachings of Paul, baptism and the cross are always closely connected.
It is as if they are flip sides of the same coin.
Paul says that our old man was crucified with Him.
This baptism was accomplished by Christ when He offered himself on the cross as a sacrifice for sin once and for all.
Baptism into Christ cannot be done by us; it can only be done by God.

There is an important piece of context we must not miss with the books of Romans and Galatians.
Both Circumcised and Baptized in those books.

Paul is addressing all nations on a level playing field in the book of Colossians.
He is not saying "to the Jew First" like he does in Romans.
He is speaking to people here who were never circumcised.

Col 2:10-12 NKJV
________________
and you are complete in Him, who is the head of all principality and power.
In Him you were also circumcised with the circumcision made without hands, by putting off the body of the sins of the flesh, by the circumcision of Christ
buried with Him in baptism, in which you also were raised with [Him] through faith in the working of God, who raised Him from the dead.
________________

Under the Old Covenant, both circumcision and baptism in water (the mikvah) were required for a Gentile that wanted to become a practicing Jew.
But the circumcision done here is performed without hands. It is the circumcision of Christ.
This circumcision was accomplished on the cross through the death of Christ.
Does it not make total sense that the baptism done here is also without hands?

What is the difference between being dead and being buried?
The destruction of the body.
Think of Paul in Corinthians.
The baptism here includes both being buried and raised with Christ.
And this baptism is accomplished through faith in the working of God.
This baptism is done deal in Christ, but we enter into this by faith.

Your completeness in Christ can never be achieved through water or Spirit anointing.
It cannot even be improved or augmented through water or Spirit anointing.
It stands solely and completely on the sacrifice of Christ and the working of God.

The One Baptism
---------------

Paul takes baptism to a new level when summarizing the unity of the Spirit in the book of Ephesians.

Eph 4:4-6 KJV
_____________
[There is] one body, and one Spirit, even as ye are called in one hope of your calling;
One Lord, one faith, one baptism,
One God and Father of all, who [is] above all, and through all, and in you all.
_____________

One Baptism.
What is this baptism Paul is referring to?
The unity of the Spirit in Ephesians chapter 4 is actually a reflection or a summary of a much more detailed explanation of the work of Christ found in chapter 2.
Paul explains this One Baptism in chapter 2.

Eph 2:14-16 NKJV
________________
For He Himself is our peace, who has made both one, and has broken down the middle wall of separation,
having abolished in His flesh the enmity, [that is], the law of commandments [contained] in ordinances, so as to create in Himself one new man [from] the two, [thus] making peace,
and that He might reconcile them both to God in one body through the cross, thereby putting to death the enmity.
________________

Remember that baptism and the cross are like flip sides of the same coin.
This One Baptism is accomplished by the cross.
Paul is sharing good news for the Gentile nations at large; he is speaking to those where uncircumcised and not part of the covenants of Israel (Eph 2:11-12).
The reconciliation here brings both Jew and Gentile into one body.
This isn't through any outward circumcision or ceremonial cleansing, but instead through the circumcision of Christ and baptism into His death.

The word for "new man" here isn't referring to a male specifically.
It's the word anthropos that is used to refer to a human being, whether male or female.
God is creating the new person in Christ.

|========
| Adam: Old Person (Rom)          | Christ: New Person (Eph)
| Adam & Eve as One Body (Gen)    | Christ & The Church as One Body (Eph)
| Nations & Israel (Gen)          | Husband & Bride (Eph & Rev)
|========

Christ is the Head of this creation much like Adam was the head of the old.
The New Creation is not defined by or based on these.
The only path to the new creation is through the death, burial, and resurrection of Christ.
Without baptism into the death of Christ, it is not possible to have any part of the new creation.
It is the calling of God that determines where you fit in the New Creation.

What does the body of Christ look like?
If the One Baptism involves putting on this new person, would it not be good to have at least some concept of what this new person looks like?
The glimpses into the new creation we get in Scripture are few and far between.
Both John and Paul have the curtains peeled back a bit for a revelation.
John sees the Bride.
Paul sees the Husband.

This One Baptism is the greatest change being worked out in the purposes of God.
It is the transition from the Old Creation headed up by Adam to the New Creation headed up by Christ.
This change is accomplished through the cross of Christ.
The cross separates the old creation from the new creation.
The distinctions of the old creation are gender, race, and religion.
The more we find our identity in the old creation the more we will be lost and broken.
Our true identity is found not under the old creation but within the new creation.

Based on the finished work of Christ, we are now encouraged to step into that new identity we have in Christ.
But we are also encouraged by Paul to "put on" or be "clothed" by this new person.
On one hand, our baptism is a done deal and there is nothing we can add to it.
On the other hand, we endeavour to keep or guard this one baptism through the things that we do.
Can we be a part of the New Creation--the New Person--without being a priest?

|========
| Soldier           | Priest
| Wash in Word      | Wash in Water
| Put on Armour     | Put on Garments
| Sword of Spirit   | Anointing of Spirit
|========

And that identity is based on the calling of God and the work of Christ, not on gender, race, or religion.
The New Creation reveals the manifold wisdom of God (Eph 3:10).
Ephesians reveals the husband soldier calling, part of the New Creation in Christ that was a secret up to this point.

Conclusion
==========

While the Great Commission from Mark chapter 16 seems to get a lot of attention today, this message of the cross is truly core to being a follower of Christ.
We have to understand the Great Commission (Mar 16:15-18) and Penticost (Acts 2) in light of the New Covenant Priesthood Christ was coming to establish.
Both of these events are closely related to the Ordaining of the Nation of Priests.
Once this Nation was Ordained, it would be used by God to preach the Gospel throughout the world.

But there is something at the core of being a follower of Christ that we cannot forget.
Christ shared this insight while he was on earth.

Mar 8:34 KJV
____________
And when he had called the people [unto him] with his disciples also, he said unto them, Whosoever will come after me, let him deny himself, and take up his cross, and follow me.
____________

Christ is speaking to a wider audience here, not just the twelve disciples.
He is letting them into the deep truth of what it really means to follow Him.
It's one thing to be ordained as a priest, it's a totally different thing to follow Christ and embrace the cross in your life.
His work as the Great High Priest was defined by His ultimate sacrifice, not by the powerful sign gifts.

Baptism and the cross are opposite sides of the same coin.
The cross symbolized baptism in both in the past tense and in the present tense.
Embracing the message of the cross in our daily lives is something that is done by us.
This is evidence in the present to us and to others that our baptism is in fact real.
The cross points back to this but also symbolizes the active change that is taking place here and now in our lives to reflect this fact.
The cross symbolizes both a completed reality and an present change and a future change.
The future change is when the old creation is permanently replaced by the new.
The present change in our lives today is the work of the Spirit (the Word) filling us and changing us.
Even while we are still a part of the old creation today, we have been touched by the New Creation in such a way that it has permanently changed us.

Paul was so changed by the cross that it had become part of his very identity.
When he preached the cross, he also lived out the power and wisdom of God in his very life.

Gal 2:20,
Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

The cross caused Paul to look at the world differently.
The cross meant that Paul looked different to the world.

May we all be able to say:
Because of the cross, I see the world through the cross.
Because of the cross, the world sees the cross when through me.
If you have seen me, you have seen Christ.
