Baptism
=======

It's very easy for our minds to get fixated on a particular image for something.
This image can stick with us and continue to influence our thinking in ways we are not even aware of.
When we think of baptism, for instance, what is usually the first thing that pops into mind?
Perhaps something like this: https://www.google.ca/search?q=baptism&tbm=isch.

Even if we realize there is much more to baptism than this, it is very hard to shake that image.
But what if this was the only thing we though of when we heard the word baptism: https://www.google.ca/search?q=cross&tbm=isch.
How would this impact our our lives?
How would Christianity be different?
How would this impact the world?

John the Baptist
----------------

It would be easy to think that water baptism is something that was first instituted by John the Baptist.
After all, this was a big part of his ministry along the banks of the Jordan river.
It is probably what he has become most widely known for.
So much so, that it's a permanent part of his name.

But baptism in water was present throughout the Old Testament.
It was intimately associated with the tabernacle and the duties of the priests.

Heb 9:9-10 KJV
______________
[The Tabernacle] Which [was] a figure for the time then present, in which were offered both gifts and sacrifices, that could not make him that did the service perfect, as pertaining to the conscience;
[Which stood] only in meats and drinks, and divers washings, and carnal ordinances, imposed [on them] until the time of reformation.
______________

The word translated "washings" is the Greek word for baptism.
We could quite correctly say that these "diverse washings" where "diverse baptisms" required under the ceremonial law.
In fact, washing in water was required both at the initial consecration of a priest and during his ongoing day-to-day service in the tabernacle.

The initial washing or cleansing of a Priest was special; it was different from the rest.
Back in Exodus, it was Moses who performed the first consecration of Aaron and his sons.

Exo 29:4 KJV
_____________
And Aaron and his sons thou shalt bring unto the door of the tabernacle of the congregation, and shalt wash them with water.
_____________

The word for wash in the Hebrew is *rachats*.
It can mean taking a full body wash like a bath or just washing your hands, depending upon the situation.
This initial priestly cleansing performed by Moses was like a full body wash, not just a washing of hands and feet.
And Aaron and his sons did not do the washing, it was Moses who did the washing.
Or put another way, as part of the ordination of this first high priest, Moses baptized Aaron in water.

After this initial washing in water, a priest was required to wash himself before performing any service in the tabernacle.
This ongoing washing was performed by the priest himself. And it did not necessarily involve washing the entire body.

Exo 30:20 KJV
_____________
When they go into the tabernacle of the congregation, they shall wash[H7364] with water, that they die not; or when they come near to the altar to minister, to burn offering made by fire unto the LORD:
_____________

No doubt this was very serious stuff. The consequence of not washing before coming near the altar was death.
Imagine going into work each day and being greeted by a sign on the wall that said "wash your hands or die!".
You can see how it might be possible to get carried away with this and start washing a few extra times just to be sure you're safe.
While washing in water was an important required part of the ceremonial law given by God, it had been embellished and built upon with religious traditions.
You can see this especially with groups like the Pharisees, who had become somewhat obsessed with ritual washing.

Fast forward to John the Baptist.
People were coming to him to be baptized.
They weren't baptizing or washing themselves in water, they were being baptized by John.
And they weren't going up to the temple to wash, they were going out to the banks of the Jordan river.

When the Pharisees heard of this, they sent someone to investigate (John 1:25).
It wasn't the fact that he was baptizing with water that was puzzling to them.
It was the fact that he was the one performing the baptism.
As far as we know, the last time somebody was baptized by someone else was when Moses baptized Aaron.
They were wondering why he was baptizing if he wasn't the Messiah, Elijah because they expected this to be done by Elijah or the Messiah.

The location where John was baptizing was also significant.
John was likely performing his baptisms near Bethabara, a location deeply connected with the history of Israel (https://en.wikipedia.org/wiki/Bethabara).
This was near the historical location of Jerico, so it would not have been far from where Joshua and the children of Israel crossed the Jordan Riveer on their way into the promised land.
It is also rumored to be the last location where the prophet Elijah was seen before he was taken up into heaven.
So you have someone doing what was expected of Elijah in the location where Elijah was last seen.
No wonder the religious leaders were taking notice.

But why was John baptizing?
What was the significance or the meaning of it?
John himself answers this question for us.

Jhn 1:29-31 NKJV
________________
The next day John saw Jesus coming toward him, and said, "Behold! The Lamb of God who takes away the sin of the world!
This is He of whom I said, 'After me comes a Man who is preferred before me, for He was before me.'
I did not know Him; but that He should be revealed to Israel, therefore I came baptizing with water."
________________

John's purpose was to reveal the Lamb of God to the Nation of Israel.
This Lamb--the Messiah--would take away the sins of that nation and the world.
Under the Old Covenant, once a year, the High Priest would make a sin offering for the sins of the whole nation.
But in the case of Christ, He is the sin offering.
He is the Lamb.
But who was the High Priest that was going to perform this sacrifice?

Heb 9:11-15 NKJV
________________
But Christ came [as] High Priest of the good things to come, with the greater and more perfect tabernacle not made with hands ...
who through the eternal Spirit offered Himself without spot to God ...
And for this reason He is the Mediator of the new covenant
________________

Under the New Covenant, The High Priest and the sin sacrifice are one in the same.
This Great High Priest offered Himself once and for all.
The baptism of Aaron by Moses was a precursor to the baptism of Jesus by John.
Moses baptized the first high priest under the Old Covenant.
John baptized The Great High Priest of the New Covenant.

The Baptism of Christ
----------------------

An interesting exchange happens when Jesus comes to John to be baptized.
At first, John refuses to baptize Him.

Mat 3:14-15 NKJV
________________
And John [tried to] prevent Him, saying, "I need to be baptized by You, and are You coming to me?"
But Jesus answered and said to him, "Permit [it to be so] now, for thus it is fitting for us to fulfill all righteousness." Then he allowed Him.
________________

To fulfil what righteousness?
We have to remember that Jesus was born under the Law and lived under the Law.
By His own words, He had not come to destroy the Law, but to fulfill or complete the Law (Mat 5:17).
The High Priest role and the sin offering of the Old Covenant are both fulfilled in Christ as the Mediator of the New Covenant.
But the Old Covenant was not something that instantly disappeared.
Even as late as in the book of Hebrews, which was written after both the resurrection of Christ and Penticost, the Old Covenant is described as being "ready to vanish away" (Heb 8:13).
That is, it had not yet vanished away.

How was the first High Priest ordained under the Old Covenant?
There were three things that Moses specifically did in Exodus 29.
First, he washed Aaron in water.
Then, he then took the priestly garments and placed them on Aaron.
Finally, he took some oil and anointed Aaron with it.

Washing in water was required for physical cleanliness under the law.
It was good hygene but it was also required to be considered ceremonially clean.
Washing in water also symbolizes washing away sin and sickness.
The garments symbolize putting on righteousness.
The oil is a symbol the spirit throughout Scripture.

Think about what happened when Christ was baptized by John.
Matthew says that immediately after Jesus was baptized, the Spirit was seen descending on Him like a dove (REF).
The dove and voice from heaven indicated the Spirit anointing of the Christ.
So with the baptism of Jesus, we see the washing in water first followed by the anointing with the Holy Spirit.
We can see both the completion of the old and the foretaste of the new in the baptism of Christ.
The washing in water required for a Priest was present.
The anointing in the Spirit necessary for The Great High Priest of the New Covenant

Christ starts His public ministry shortly after His baptism.
He announces it one Sabbath day by reading a passage from Isaiah in the Synagogue.

Isa 61:1-2a KJV
___________
The Spirit of the Lord GOD [is] upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to [them that are] bound;
To proclaim the acceptable year of the LORD ...
___________

He then declares the purpose of His ministry and shows what is beginning to happen.

Important things to highlight from Isa 61:

- Zion
- Rebuild cities
- Priests of the Lord, Ministers of God
- Receive Your Land
- Everybody that sees them will acknowledge they are blessed by Lord

God chose a specific tribe out of the nation of Israel as priests to serve God and serve that nation.
What God was doing with the tribe of Levi under the Old Covenant was a picture of what God wanted to do on a larger scale with the Nation of Israel in the world.
John's ministry was baptizing the Great High Priest of the New Covenant.
In other words, John is preparing for this Kingdom of Priests.
The Kingdom of Heaven is a Kingdom of Priests.

Jesus was the first one to be baptized in the Spirit.
John clearly said that one was coming who would baptize with Holy Spirit fire (Mat 3:11, Luk 3:16).
Everyone else had to wait until after His death, burial, and resurrection.

Jesus as the greatest high priest would then anoint a nation of priests.
In Matthew 3 and Luke 3, baptize "with holy ghost and with fire" could be translated "with holy ghost even fire" based on the meaning of kai.
The Greek word here for "and" can be used to amplify something, meaning "even" as an example of something that amplifies.
Thinking about what happened at Penticost, the tongues of fire were visible above the disciples as they were anointed with this Holy Spirit (Acts 2:3).
So it makes sense that this fire is associated with the Holy Spirit.
When Peter addresses the believers at Penticost, he clearly links what was happening then back to the promise of the Spirit from the Old Testament (Acts 2:16-19)

We need to understand the Great Commission in light of how Christ defined His ministry.

Mar 16:15-16 KJV
________________
And he said unto them, Go ye into all the world, and preach the gospel to every creature.
He that believeth and is baptized shall be saved; but he that believeth not shall be damned.
________________

But unfortunately what is almost always overlooked are the two verse that follows this.

Mar 16:17-18 KJV
________________
And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;
They shall take up serpents; and if they drink any deadly thing, it shall not hurt them; they shall lay hands on the sick, and they shall recover.
________________

The order change in the Great Commission are significant.
In that if belief comes first, the one who is righteous by faith follows Christ in spirit anointing right after baptism in water.

But what closely followed this was an anointing of the Spirit. This anointing was possible only by faith.
And there were powerful, irrefutable signs that went with this anointing that we can't ignore.
And the point of the Spirit anointing was to prepare and equip Israel to fulfill God's purpose of a Kingdom of Priests.
These two baptisms go together much in the same what that a priest had to both wash in water and get anointed in oil in preparation for his work.

One way to look at the great commission: that Jesus commanded the disciples to truly go to everyone and they never got it.
Or Jesus was sending the twelve out to all of Israel scattered throughout the world to prepare the Nation of Priests.
This nation as a whole would then go into all the world into all nations.
So the great commission is in fact a commission to go out a prepare a scattered nation to embrace the role God had for them.

There was something that still had to take place before the New Covenant could come in full force.

Christ actually had three baptisms, not just one or two (Jesus in Luke 12:50)
Christ actually had three baptisms: water purification, spirit anointing, and the cross.

This baptism is the biggest deal of all.

Baptism: A Definition
---------------------

If baptism can be used in such different ways, is it possible to arrive at some common definition of the word that can actually help us understand all its varied uses?
We need to explore the word a bit more closely to find out.

The Greek word for baptism is βαπτίζω (baptizo).
Vine's has this to say about baptize.

Vine's Expository Dictionary of New Testament Words
___________________________________________________
"to baptize," primarily a frequentative form of bapto, "to dip," was used among
the Greeks to signify the dyeing of a garment, or the drawing of water by
dipping a vessel into another, etc. Plutarchus uses it of the drawing of wine
by dipping the cup into the bowl (Alexis, 67) and Plato, metaphorically, of
being overwhelmed with questions (Euthydemus, 277 D).
___________________________________________________

Two words: "to dip" vs "to baptize".

So while baptize can be used to describe dipping something into water, it means far more than that.
It signifies a permanent change, not just a temporary immersion.
There is no better illustration of this than pickles!

https://www.blueletterbible.org/lang/lexicon/lexicon.cfm?strongs=G911&t=KJV
_________
Not to be confused with 907, baptizo. The clearest example that shows the
meaning of baptizo is a text from the Greek poet and physician Nicander, who
lived about 200 B.C. It is a recipe for making pickles and is helpful because
it uses both words. Nicander says that in order to make a pickle, the vegetable
should first be 'dipped' (bapto) into boiling water and then 'baptised'
(baptizo) in the vinegar solution. Both verbs concern the immersing of
vegetables in a solution. But the first is temporary. The second, the act of
baptising the vegetable, produces a permanent change.
_________

Often in evangelical Christian circles, baptism is presented as something that is optional but is encouraged as a way to follow Christ in obedience.
Baptism is not considered to produce any change in the individual, but it can perhaps be a faith building experience.
For example, believers questioning thier own faith who have not been baptized are often encouraged to get baptized as a way to make a testament of thier faith and overcome their doubts.
The risk is that we turn baptism into something that is more about us and our actions than about Christ.
But is baptism ever really presented as something optional in Scripture? And does baptism actually change people?

While baptism in water can be symbolic of the death, burial, and resurrection of Christ, I do not believe that is the primary significance here.
And it wasn't likely that any of the people being baptized by John had heard of Jesus.
This was before the start of His public ministry.
And anyone who did know Jesus at this time probably had no idea what was going to happen to Him in just a few years.

Being baptized into something means to be so affected that there is a lasting change that takes place.
Often, the emphasis is placed on the act rather than the change, or on the symbolism of the act rathen than the act itself.
How would we understand baptism if we focus on the change brought about by it?
The key is understanding that there are different baptisms in Scripture.
And the change brought about by each of those baptisms is different.

How does washing fit into this in Greek meaning? Is this reading too much into baptize? https://goddidntsaythat.com/2010/08/24/q-and-a-the-original-baptism/

Look at the different themes associated with baptism in scripture (e.g. deliverance, judgement, cleansing, healing).

Baptism into Christ
-------------------

Who is the greatest teacher on baptism in the New Testament?
The greatest teacher on baptism in the New Testament once said "Christ sent me not to baptize" (Paul in 1 Cor 1:17)?

When we think about the word baptize, the cross is not necessarily the first association that jumps to mind.
However, baptism into the death of Christ is a central message to Paul's teaching.
Paul makes it clear that to be baptized into Christ is really to be baptized into His death.
A clear pattern in Paul's teaching is that when he mentions baptism, it is in close relationship with the cross.
The two words usually show up close to each other in his writing.

Rom 6:3-6 KJV
___________
Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?
Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life.
For if we have been planted together in the likeness of his death, we shall be also [in the likeness] of [his] resurrection:
Knowing this, that our old man is crucified with [him], that the body of sin might be destroyed, that henceforth we should not serve sin.
___________

How do we know this baptism isn't washing in water? Who does this baptism?
See the circumcision and baptism in Col 2:12.

Col 2:10-12 KJV
_________________
And ye are complete in him, which is the head of all principality and power:
In whom also ye are circumcised with the circumcision made without hands, in putting off the body of the sins of the flesh by the circumcision of Christ:
Buried with him in baptism, wherein also ye are risen with [him] through the faith of the operation of God, who hath raised him from the dead.
_________________

Paul is addressing all nations on a level playing field in the book of Colossians.
He is not saying "to the Jew First" like he does in Romans.
He is speaking to people here who were never circumcised.
Under the Old Covenant, both circumcision and baptism in water (the mikvah) were required for a Gentile that wanted to become a practicing Jew.
But the circumcision done here is performed without hands. It is the circumcision of Christ.
Does it not make total sense that the baptism done here is also without hands?

The baptism here is something so central to the gospel that it was common to both the believing Jew and the believing Gentile,
quite apart from any circumcision or washing of the flesh.
In fact, it is through the "operation of God".
Only God can perform this baptism.
This baptism is done (past tense), but it is entered into (present tenst) by faith.

Notice how the words baptism and cross both pop out in Rom 6 and Col 2.
Baptism and the cross are like flip sides of the coin.
Baptism into Christ is baptism into His death.
The significance of the cross is that it is how the death was accomplished.

Baptism into the death of Christ cannot be done by us; it can only be done by God.
But embracing the message of the cross in our daily lives is something that is done by us.
This is evidence in the present to us and to others that our baptism is in fact real.
The cross points back to this but also symbolizes the active change that is taking place here and now in our lives to reflect this fact.
The cross symbolizes both a completed reality and an present change and a future change.
The future change is when the old creation is permanently replaced by the new.
The present change in our lives today is the work of the Spirit (the Word) filling us and changing us.

The structure of Galatians centers around baptism into Christ and the Cross:

- A: Gal 2:20: Paul crucified with Christ. Christ living in him.
- B: Gal 3:1: The Galatians had a clear example of Christ crucified.
- C: Gal 3:27-28: Baptized into Christ, distinction gone, all one in Christ Jesus
- B: Gal 5:24: They that are Christ's have crucified the flesh
- A: Gal 6:14: The world has crucified to Paul. The New Creation.

How was it that the Galatians has a clear example of Christ crucified set before them?
This was through the preaching and life of Paul. Because he was baptized into the death of Christ and had embraced the cross.
Paul made this evident through his life because this had become Paul's identity.
One of the disciples came to Jesus while He was on earth and asked to see the Father.
How did Jesus reply?
"Have I been with you so long, and yet you have not known Me, Philip? He who has seen me has seen the Father." (John 14:9)
In effect, Paul is saying a similar thing here.
If you have seen me (Paul), you have seen Christ.

What was Paul talking about here?
What does Christ crucified look like?
Is it powerful signs and wonders?
Paul used this example to confront issues in the Corinthian church.
Communion and its consequences, the spirit gifts, baptized into one body.
These had the baptism of the spirit. They had the gifts.
But they didn't understand the message of the cross.
Much like the Children of Israel in the Old Testament were baptized into Moses but died in the wilderness.
Much like the priests under the Old Covenant, misusing the calling and gifts had serious consequences.
May were ill and some even died.

Paul explains what embracing the cross looks like in a somewhat puzzling passage in 1 Cor.

1Co 15:29 KJV
____________
Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?
____________

Paul is asking: why would someone be baptized "for the dead" if there is no resurrection of the dead.
What does being baptized "for the dead" mean?
The phrase in the Greek can mean over as in position or also in place of.

[Think about whether this could be related to parallel with Christ or just physically over the dead]

Commonly, this verse is understood as a reference to a practice of either baptizing the dead or getting baptized in the place of a dead person.
But it is a bit strange to assume this given there is no hint of this anywhere else in this book.
Why would Paul randomly refer to a practice not found anywhere else in the Bible when he is trying to defend the truth of the resurrection?
It makes much more sense here if Paul is actually speaking of the same thing in v29 - v32.
Paul mentions that he fought with wild beasts a few verses down.
The criminals and Christians were at that time thrown before wild beasts (research more).
How many died in these very area floors for their faith?
Paul could be referring to those that were baptized over the same place as these dead.
This lifestyle of dying daily was the outcome of Paul embracing the message of the cross.

The miracles performed by Jesus are not the ultimate expression of the power and the wisdom of God.
And the sign gifts of Spirit anointing are only temporary.
They are passing away as Paul says in 1 Cor 13.
If you have been baptized in water and anointed with the spirit, but you don't have love, you are nothing.
Its not the physical act of dying that is central to the cross in practical application.
Paul says that if you give your body to be burned but don't have love, you are nothing.
This sacrifice is only acceptable to God if it is done willingly.
Can you do something willingly if you don't have a choice?
I think there is the very real possibility that those that God calls to be martyrs also have choice (Heb 11:35).
Did Christ die because He was nailed to a cross and couldn't escape?
No, He died because He willingly gave Himeself up.
That is the power and the wisdom of God in the cross.
It is getting to the point of being able to willingly let go of everything.

Paul was so changed by the cross that it had become part of his very identity.
When he preached the cross, he also lived out the power and wisdom of God in his very life.

Gal 6:14 KJV
____________
But God forbid that I should glory, save in the cross of our Lord Jesus Christ, by whom the world is crucified unto me, and I unto the world.
____________

The cross caused Paul to look at the world differently.
The cross meant that Paul looked different to the world.
These two things together are the strongest evidence of the reality of baptism into Christ in our daily lives.

While the Great Commission from Mark chapter 16 seems to get a lot of attention today, this message of the cross is truly core to being a follower of Christ.
How critical it is to understand the Great Commission in light of something else Christ said.
It's one thing to be ordained as a priest, it's a totally different thing to follow Christ and embrace the cross in your life.

Mar 8:34 KJV
____________
And when he had called the people [unto him] with his disciples also, he said unto them, Whosoever will come after me, let him deny himself, and take up his cross, and follow me.
____________


The One Baptism
---------------

We have seen that a full scriptural understanding of baptism requires that we distinguish between washing in water, being anointed by the spirit, and being baptized into the death, burial, and resurrection of Christ.
But Paul takes this one step further when summarizing the unity of the Spirit in Ephesians chapter 4:

Eph 4:4-6 KJV
_____________
[There is] one body, and one Spirit, even as ye are called in one hope of your calling;
One Lord, one faith, one baptism,
One God and Father of all, who [is] above all, and through all, and in you all.
_____________

How can Paul say there is only one baptism when we clearly saw that there are at least three?
Context.
Looking just a few verses down, Paul clearly defines the context for this.

Eph 4:22-24
___________
Put off ... the old man (anthropos) ... be renewed ... put on the new man (anthropos).
___________

The word for man here isn't referring to a male specifically.
It's the word anthropos that is used to refer to a human being, whether male or female.
In other words, we could say

___________
Put off ... the old humanity ... be renewed ... put on the new humanity.
___________

Or perhaps

___________
Put off ... the old creation ... be renewed ... put on the new creation.
___________

Remember that baptism in its truest sense always involves a change.
The change here is from the old creation to the new creation.
Just like the priesthood under the Old Covenant was first established with Moses baptizing Aaron and his sons.
Just like the new priesthood under the New Covenant that John the baptist was proclaiming.
Baptism is also deeply connected with identity.
Ephesians chapter 2 helps shed more detailed light on the new anthropos.

In some ways, you can think of all prior baptims being fulfilled or brought to completion in this One Baptism.

Eph 2:11-18 KJV
_______________
Wherefore remember, that ye [being] in time past Gentiles in the flesh, who are called Uncircumcision by that which is called the Circumcision in the flesh made by hands;
That at that time ye were without Christ, being aliens from the commonwealth of Israel, and strangers from the covenants of promise, having no hope, and without God in the world:
But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ.
For he is our peace, who hath made both one, and hath broken down the middle wall of partition [between us];
Having abolished in his flesh the enmity, [even] the law of commandments [contained] in ordinances; for to make in himself of twain one new man, [so] making peace;
And that he might reconcile both unto God in one body by the cross, having slain the enmity thereby:
And came and preached peace to you which were afar off, and to them that were nigh.
For through him we both have access by one Spirit unto the Father.
_______________

|========
| Eph 4                 | Eph 2
| One Body              | reconcile both unto God in one body (v16)
| One Spirit            | access by one Spirit to the Father (v18), habitation of God through the Spirit (v22)
| One Lord              | holy temple in the lord (v21)
| One Faith             | Saved through faith (v8)
| One Baptism           | Made both one (v14), One new anthropos (v15), by the cross (v16)
| One God and Father    | Access by one Spirit to the father (v18)
|========

The cross separates the old creation from the new creation.
It is impossible to be a part of the New Creation without baptism into Christ.
Christ is the Head of this creation much like Adam was the head of the old.
The only path to the new creation is through the death, burial, and resurrection of Christ.
Without baptism into the death of Christ, it is not possible to have any part of the new creation.
This baptism is foundational to any good news of the new creation.
And it is a baptism that is done by God, not by human hands (Col 2).

The distinctions and divisions of the old creation simply do not translate into the new creation.
Fleshly distinctions and differences are part of the old creation and end at the cross.
Gender, race, religion.
Your gender or race does not determine where you fit within the new creation in Christ.
It is the calling of God that determines where you fit in the New Creation.

The glimpses into the new creation we get in Scripture are few and far between.
Both John and Paul have the curtains peeled back a bit for a revelation.

John sees the Bride.
Paul sees the Husband.

|========
| Old Anthropos     | New Anthropos
| Adam              | Christ
| Adam & Eve        | Head & Body
| Israel & Nations  | Bride & Husband
|========

We are getting a glimpse into the new Anthropos that God created in Christ.
Our true identity is found not under the old creation but within the new creation.
And that identity is based on the calling of God and the work of Christ, not on gender, race, or religion.
All purposes in the New Creation start with the baptism into the death of Christ.
The New Creation reveals the manifold wisdom of God (Eph 3:10).

When we are baptized into the death of Christ, we are so impacted by the message of the cross that it changes us.
Even while we are still a part of the old creation today, we have been touched by the New Creation in such a way that it has permanently changed us.
We have been baptized into Christ and He is now a permanent part of us.
The cross is how the old creation is touched, infused, and changed by the new.
This One Baptism is the the only universal all encompassing baptism.
All others are temporary in nature or limited in scope, much like the Old Covenant and New Covenant.

1. Old Covenant: water baptism: temporary, called of Israel according to flesh
2. New Covenant: spirit baptism: eternal, called of Israel according to spirit
3. New Anthropos: baptism into death of Christ: eternal, all the called in Christ (Bride and Husband)

Baptism and the cross are like opposite sides of the coin.
All of the reasons people feel the need to be baptized in water can be answered in the cross.

What is the defining characteristic of the New Creation? Love.
How do we remember and honour the work of Christ in our lives today?
How do we show evidence of this to others?
Is it through an outward washing ceremony? Or is it by being shaped by the cross in our daily lives?
