= The Greatest Commandment

Have you ever gotten so caught up in the details of something that you started to loose sight of what was actually most important? We might say that this is like not seeing the forest for the trees. It's not that details are unimportant. But detail alone cannot give us the entire picture. Perspective is required.

Imagine studying a piece of fine art using only a magnifying lens. We may be able to appreciate a portion of the artwork in great depth. We may uncover things about one part that would never be uncovered if we only studied from a distance. But focusing only on detail will ultimately lead to missing the message of the whole.

I wonder if the Scribes of Israel sometimes fell into this trap.

.Note
****
Expand on the description of the Scribes with actual research. Mention how they were meticulous with the law in every detail. A resource to start with http://www.jewishencyclopedia.com/articles/13356-scribes. Tie this into what Jesus is saying here in the expansion below.
****

Being a detail-oriented person myself, I can certainly identify with this. How easy it is to make the word of God about the details rather than the whole picture.

In the Gospel of Mark, a scribe approached Jesus with a detailed question about the law.

[quote, Mar 12:28-31 KJV]
____
And one of the scribes came, and having heard them reasoning together, and perceiving that he had answered them well, asked him, Which is the first commandment of all? And Jesus answered him, The first of all the commandments [is], Hear, O Israel; The Lord our God is one Lord: And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this [is] the first commandment. And the second [is] like, [namely] this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these.
____

When this Scribe used the word commandment, he wasn't just thinking about the ten commandments. He had in his mind all 613 commandments.
The scribe was focusing on detail.

But in his answer, Jesus brought perspective to that detail. Christ answered with something that was not directly one of the 613 or the ten commandments. He told the Scribe what the law was in fact actually about.

The greatest commandment is about *love*: first and foremost loving God, and then loving other people. In fact, it is only in loving God that we are truly able to love other people.

This love is not a feeling or emotion. It is service and sacrifice. The word for *love* is the same word used in John 3:16 "for God so *loved* the word that He gave". So loving with the heart, soul, mind, and strength is giving and serving with the heart, soul, mind, and strength.

But why would the heart, the soul, and the mind be specifically and distinctly mentioned here? What can we understand from this.

== The Mind

The key words to the greatest commandment are heart and soul. They are also closely related. To see this, we need to go back to the passage in Deuteronomy that Christ was quoting in Mark:

[quote,Deu 6:4-6 KJV]
____
Hear, O Israel: The LORD our God [is] one LORD: And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might. And these words, which I command thee this day, shall be in thine heart:
____

Which word is missing here that was present in Mark? *Heart* and *soul* and *strength* (or might, as it is translated here) are all present. But the word *mind* is absent. Why is this significant?

We must keep in mind that Deuteronomy was written long before Mark and that it was written from a Hebrew perspective. The people that Jesus was addressing in Mark were living in a culture that had been influenced by Greek philosophers like Plato for hundreds of years. And to Plato, the mind was a big deal. In fact, he believed that one could arrive at ultimate or absolute truth through use of the mind or the intellect. The mind was so elevated that it had practically become a god. The mind was viewed as a central part of the immortal soul.

But all of this is contrary to a true Scriptural understanding of the mind. Scripture teaches that the heart is the deepest part of the person. The heart is the ultimate point to which our desires, our will, can be traced. And it is actually the heart that steers the rational mind.

In Romans chapter 1, Paul describes the sad path of nations that resisted the truth of God and went after idols. It started when those nations failed to glorify God as God (Rom 1:21). This resulted in their foolish heart being darkened. Finally, God gave them over to a reprobate mind that led to all sorts of activities not in line with the heart of God (Rom 1:28). Not glorifying God led to a darkened heart which led to a reprobate mind. The heart  steered the mind off course.

Christ acknowledges the importance of the rational mind as part of a complete person, but I don't believe it was the major focus of His teaching. You can see this quite easily by looking at how many times he actually uses the word. Just looking at the words spoken by Christ in the book of Mark reveals the following:

* Heart: 8x
* Soul: 8x
* Mind: 1x (only in the above quotation from Deuteronomy)

It's fair to say that Christ focused on the heart and soul in His teaching. He speaks about them 8 times more frequently than the mind throughout the book of Mark.

Looking back at the book of Deuteronomy, it turns out it's filled with references to the heart. In fact, out of all the books in the Old Testament, it's one of the top books about the heart with 49 references to 'heart'. Imagine a book of Moses that's actually a book on the heart. The book that takes the prize for heart is Psalms with 133 reference.

Out of the 49 references to heart in Deuteronomy, ten of them are actually the phrase "heart and soul." This is very fitting seeing that there are ten commandments. After all, the law can be summed up by loving God with all of your heart and your soul and loving others as a result.

== The Soul

The challenge in understanding the word *soul* is that fact that the meaning of this word is colored heavily by Greek philosophy going all the way back to philosophers like Plato. Plato's concept of the soul was an immortal part of a person, distinct from their body. This soul was the "real person" trapped inside a body. Upon death, the soul leaves the body and carries on in existence.

This stands in stark contrast to the Hebrew concept for soul found in the Old Testament. The Hebrew word for soul is *nephesh*. We can get a pretty clear picture of the meaning of this word by looking at the first few occurrences of this word found in the creation account in Genesis 2.

The first three appearances of this word are not even in reference to human beings. The souls referred to here are living creatures that are in the water, on the land, and in the sky. They are fish, cattle, and birds. And this word is used to describe the complete creature, not just some part of the creature.

When we reach the creation of Adam (a human being), we read:

[quote, Gen 2:7 KJV]
____
And the LORD God formed man [of] the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.
____

In other words, when God combined the body formed from dust with the breath or spirit He breathed into Adam, the result was a living creature or a living soul.

One challenge with the word soul is the fact that it can be used figuratively. Even though soul includes the entire living creature, it can be used figuratively to refer to only parts of the creature. For example, you will come across passages in Scripture that speak of a soul rejoicing or a soul being troubled. This is a figurative use of the word soul, where the word for the whole person is used to represent an internal emotion or feeling.

Loving God with all of your soul doesn't mean loving Him with some piece of you that is inside your body but distinct from your body. It means loving God with the entire creature that He has made you to be. It is all encompassing.

== The Heart

When we think of this word, its natural to imagine a bodily organ that pumps blood. But the Hebrew words *leb* and *lebab*, which are translated *heart* in the Old Testament, literally mean the innermost part of something. These words are used in such phrases as "the *heart* of the sea" or the "the *midst* of heaven".

When heart is spoken of in the human context, it represents the innermost or central part of your soul. Life is described, in Proverbs, as flowing out of the heart:

[quote, Prov 4:23 KJV]
____
Keep thy heart with all diligence; for out of it [are] the issues of life.
____

The heart is seen as the fountain your life flows out of. It drives the very activities and actions of life.

This understanding of the heart is found throughout the teaching of Christ. In a great moment of teaching, the Pharasees come to Christ and ask Him why he didn't wash His hands before eating, according to their tradition. Christ has a marvelous way of taking this surface-level question and turning it around to teach something much deeper.

[quote, Mat 15:17-20 KJV]
____
Do not ye yet understand, that whatsoever entereth in at the mouth goeth into the belly, and is cast out into the draught? But those things which proceed out of the mouth come forth from the heart; and they defile the man. For out of the heart proceed evil thoughts, murders, adulteries, fornications, thefts, false witness, blasphemies: These are [the things] which defile a man: but to eat with unwashen hands defileth not a man.
____

The Pharasees were worrying about being made unclean with dirty hands. But this was only a surface level cleanliness. It was their heart that was really making them unclean. And no amount of washing in water could cleanse that part.

In the Sermon on the Mount in Matthew 5, Christ zeros in on the heart in a series of alternating contrasts between the letter of the law and the Spirit of God that was behind the law. He says, in effect:

____
You have heard it said: don't murder. This is the letter of the law. But I say unto you: anyone who is angry without cause has committed murder in his heart. This is the Spirit behind the law.

You have heard it said: don't commit adultery. This is the letter of the law. But I say unto you: anyone who lusts has committed adultery in his heart. This is the Spirit behind the law.
____

The Pharisees, in their attempt to not break the letter of law of God, added layer upon layer of protection around the law until it became almost unrecognizable. But none of this dealt with the source of the problem, the heart. The fact that so many laws were required to achieve a form of outward conformance is actually a testament to just how bad the heart problem was. Christ came to deal with the problem at its source. If the problem is deal with here, fulfilling the letter of the law will be a natural outcome.

Any works that are acceptable to God always flow out of a heart that is led by His Word. This is what Christ is getting at in the parable of the wise and foolish builders.

[quote, Luk 6:45-49 KJV]
____
A good man out of the good treasure of his heart bringeth forth that which is good; and an evil man out of the evil treasure of his heart bringeth forth that which is evil: for of the abundance of the heart his mouth speaketh. And why call ye me, Lord, Lord, and do not the things which I say? Whosoever cometh to me, and heareth my sayings, and doeth them, I will shew you to whom he is like: He is like a man which built an house, and digged deep, and laid the foundation on a rock: and when the flood arose, the stream beat vehemently upon that house, and could not shake it: for it was founded upon a rock. But he that heareth, and doeth not, is like a man that without a foundation built an house upon the earth; against which the stream did beat vehemently, and immediately it fell; and the ruin of that house was great.
____

Who or what is the rock in this parable? It is the Word of God. But more importantly, where is the rock? The wise builder dug deep and laid a foundation upon the rock. This was no mere surface encounter with the Word. This was an encounter with the Word at the deepest level. The heart filled with and led by the Word of God is what serving God is all about.

= A Man After God's Own Heart

When we looked at the words heart and soul in the Hebrew Old Testament, we saw that the book of Psalms had more references to *heart* than any other book. It's not entirely surprising that David, "a man after God's own heart" (1 Sam 13:14, Acts 13:22), would write a lot about the heart. What can we lean about the heart from David?

David make some pretty big mistakes during his life. He committed adultery and then saw to it that the husband of the woman he slept with was killed in battle. This sin didn't just take place in his imagination, he carried right through to the external action. How could someone like this be said to have a heart "after God's own heart?" The answer to this lies in David's response to his sin.

Psalm 51 records David's response to God after the prophet Nathan came to him to confront him about his sin:

[quote, "Psa 51:2-4, 6, 10, 16-17 KJV"]
____
Wash me throughly from mine iniquity, and cleanse me from my sin. For I acknowledge my transgressions: and my sin [is] ever before me. Against thee, thee only, have I sinned, and done [this] evil in thy sight: that thou mightest be justified when thou speakest, [and] be clear when thou judgest. ... Behold, thou desirest truth in the inward parts: and in the hidden [part] thou shalt make me to know wisdom. ... Create in me a clean heart, O God; and renew a right spirit within me. ... For thou desirest not sacrifice; else would I give [it]: thou delightest not in burnt offering. The sacrifices of God [are] a broken spirit: a broken and a contrite heart, O God, thou wilt not despise.
____

When the sinful heart encounters the Word of God, there can be only two responses: that heart can be hardened or it can be broken. David's encounter with the truth of his failure resulted in a broken spirit and a contrite heart. He knew that what God really desired in the law wasn't just burnt offerings and sacrifices. Yes, those were part of serving God under the law, but the actual objective of the law was to bring about an awareness of sin that leads to this broken and contrite heart. This is something God will never despise.

The cry of David's heart in Psalm 51 is answered 1000 years later in the Son of David. At the start of His earthly ministry, Christ went into a synagogue one Sabbath, opened the book of Isaiah, and read this:

[quote, Isa 61:1-2 KJV]
____
The Spirit of the Lord GOD [is] upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim liberty to the captives, and the opening of the prison to [them that are] bound; To proclaim the acceptable year of the LORD.
____

This is Christ announcing that He was there for those who had their heart broken by the law. He was there to set free those in bondage so they could become what God had always wanted them to be. God wanted Israel to be a light and an example to all other nations on earth. Israel was destined to be a living, breathing, walking, talking example of what God's heart looked like. They were to educate and teach the world about Him.

The ministry of Christ wasn't about healing the sick and feeding the hungry. Yes, these were signs that He did perform, but these signs were given to prove that He was the one who could truly heal the heart and feed the soul. But for that to be possible, you had to be open to Him like David was. A broken heart is a heart open to Him.

== The Greatest Prayer

Unfortunately, not many in the nation Israel had a heart like David's. Instead of being broken, they were hardened and blinded. The book of Acts is the history of God making every attempt to reach the hard heart of Israel who had rejected their own Messiah. The book of Acts ends with Israel in blindness. Not blindness for ever, but blindness until one day God prepares their hearts to look upon the one they had pierced and mourn (Zech 12:10). Blindness until one day they have a heart like the heart of David.

The Apostile Paul certainly experienced the hardness of this nation in his ministry to Israel during the Acts period. Perhaps this is why when he was addressing the nations at large in the book of Ephesians, he writes the book around this central prayer

[quote, Eph 3:14-19 NKJV]
____
For this reason I bow my knees to the Father of our Lord Jesus Christ, from whom the whole family in heaven and earth is named, that He would grant you, according to the riches of His glory, to be strengthened with might through His Spirit in the inner man, that Christ may dwell in your hearts through faith; that you, being rooted and grounded in love, may be able to comprehend with all the saints what [is] the width and length and depth and height--to know the love of Christ which passes knowledge; that you may be filled with all the fullness of God.
____

If Christ does not dwell in our hearts, we can at best become like the Pharisee, the Sadducee, or the Scribe. True Bible study is getting to know God at such a level that He fills our hearts with the love of Christ. If we understand all mysteries and don't have love, we really are nothing. The natural outcome of a true and complete understanding of God is love. If we could ask God only one thing, it would be this. This is a prayer that when spoken from a broken heart won't go unanswered.
