= The Two Testaments

Question: how do we divide or structure the Bible at the most basic level?

== Thesis

The Bible is the life story of the Lord Jesus Christ, Jehovah that was, and is, and is to come.
Rather than basing our structure of the Bible solely on historical timelines and languages, we should seek to develop a structure based on the major arcs in the life and work of Christ.
At the highest level, we will see that the Bible is the story of two marriages.
The first was ended by death and the second was possible only through resurrection.

The ultimate goal of God's will is bringing all nations back togehter under One Head and Lord.
For most of revealed history, God reveals Himself as taking on the husband role with first Jews and then some Gentiles taking on the wife role.
But The Mystery revealed to Paul opens our eyes to the identity of the Husband Himself, which is Christ as the Head and the nations as the body.

== Terms

The story of God's interaction with humans through Christ is heavily based on metaphor.
Key key metaphors used are:

- Promise (proposal)
- Marriage: (fulfillment)
- Husband
- Wife
- Child
- Heir

Our asumption is that these are used consistently throughout the Bible.
When we have a correct understanding, these terms will not result in inconsistencies or contradictions.