= The Things That Are God's

If you had the opportunity to ask God one question face to face, what would it be? Would it be a special request? An answer to a puzzling or challenging passage in the Bible? I'm sure we've all thought of something like this at one time or another.

During Christ's earthly ministry, three religious leaders from Israel actually had this very opportunity. I don't think that, from their perspective, they looked at it this way. In fact, these leaders saw Jesus as an up and coming threat. His teaching was powerful in a way that theirs wasn't. He was gaining popularity with the people. And he had repeatedly called them out for their hypocrisy.

They wanted to act forcefully against Him, but they were afraid of the people. So they devised a strategy: try to trap Jesus using His own words. If they could ask Him hard questions and get Him to say something outrageous or blasphemous, then they would have him in their trap.

Looking back on this from our perspective, this is actually a pretty ironic. The person they are about to question is the "Word of God made flesh" (John 1:14). The Word of God made flesh: sharper than a two-edge sword, and a discerner of the thoughts and intents of the heart (Heb 4:12). Trying to trick this person is a bad idea. But Christ skillfully takes something that was intended as a trap and uses it for powerful teaching.

== The Pharisee

The first question came from the Pharisees. The Pharisees were a highly religious sect so zealous about keeping the law that they wrapped layer upon layer of tradition around to it in their attempt to avoid breaking it. They ended up so far removed from the heart of God that the law really became unrecognizable.

____
[Mar 12:14-15 KJV] And when they were come, they say unto him, Master, we know that thou art true, and carest for no man: for thou regardest not the person of men, but teachest the way of God in truth: Is it lawful to give tribute to Caesar, or not? Shall we give, or shall we not give?
____

They first attempt to butter up and flatter Jesus, and then they get around to asking their question. To understand where this question is coming from, we need to appreciate how the Pharisees approached tithing. Under the law of Moses, each tribe of Israel other than the tribe of Levi was required to pay ten percent to help support the tribe of Priests in their service of the nation. In other words, this was a divinely-instituted tax system.

The Pharisees made tithing much more than this: they would give a tenth of their mint, of their dill, of their spices, and so on. They became obsessed with giving a tenth of everything. They built an elaborate system around this. They stared to think that worshiping God was about tithing.

When they ask whether it's *lawful* to pay tax, they aren't referring to the law of Rome, they are referring to the law of Moses. In other words, they were asking "does the Law of God require us to pay our taxes". They would see paying taxes as a form of worship to Caesar. They framed this question expecting a simple "yes" or "no" answer, knowing they had laid the trap.

But of course, Christ saw through this and gave them an extremely insightful answer:

____
[Mar 12:15-17 KJV] But he, knowing their hypocrisy, said unto them, Why tempt ye me? bring me a penny, that I may see [it]. And they brought [it]. And he saith unto them, Whose [is] this image and superscription? And they said unto him, Caesar's. And Jesus answering said unto them, Render to Caesar the things that are Caesar's, and to God the things that are God's. And they marvelled at him.
____

At a surface level, it would be easy to look at this answer and think that Christ simply avoided the trap and told the Pharisees to keep giving their tithes and keep paying their taxes. But I believe the Word of God is sharper than that and cuts deeper than that.

Christ knew what was going on in their heart, and this is what I believe he was discerning about them: "you may be tithing ten percent of everything you have, but you've actually given nothing to God. You may be paying your taxes, but deep down you hate doing it, and you are no different than someone who doesn't pay their taxes". Or put another way "if you truly gave God what He wanted, you wouldn't have so much trouble giving Caesar some tax money that has his face stamped on it."

The Phairsees distorted the Word of God by adding all their traditions to it until they ultimately used it to serve themselves.

== The Sadducee

The next question came from a Sadducee. The Sadducees were a religious sect that were opposed to all the added traditions of the Pharisees that weren't found in the Torah. They believed strongly that the written Word was the only authoritative source for doctrine. They also happened to deny the truth of resurrection. This, and other disagreements, put them at odds with the Pharisees. So they were probably glad to see the Pharisees put in their place with the first question.

The Sadducee came to Jesus with a hypothetical question about the doctrine of resurrection that involved seven brothers that had each married, and then died soon thereafter. The catch here was that they all married the same woman in succession:

____
[Mar 12:23-24 KJV] In the resurrection therefore, when they shall rise, whose wife shall she be of them? for the seven had her to wife.
____

How could resurrection ever take place, they were thinking, if you have a situation like this. Of course, Christ knew there was no real problem here and pointed out the source of their difficulty:

____
[Mar 12:24-25 KJV] And Jesus answering said unto them, Do ye not therefore err, because ye know not the scriptures, neither the power of God? For when they shall rise from the dead, they neither marry, nor are given in marriage; but are as the angels which are in heaven.
____

The Sadducees distorted the Word of God by leaving things out. And ultimately they were again using the Scriptures to serve themselves.

== The Scribe

Seeing how well Jesus had answered the Sadducee, a Scribe decided to ask a skill testing question. The Scribes were the keepers and teachers of the Law. They liked to sort, categorize, organize, and study the commandments. Perhaps they even got into debates over which commandments were most important:

____
[Mar 12:28 KJV] And one of the scribes came, and having heard them reasoning together, and perceiving that he had answered them well, asked him, Which is the first commandment of all?
____

Christ answers this simply and directly with insight that actually applies to all three questions:

____
[Mar 12:29-31 KJV] And Jesus answered him, The first of all the commandments [is], Hear, O Israel; The Lord our God is one Lord: And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this [is] the first commandment. And the second [is] like, [namely] this, Thou shalt love thy neighbour as thyself. There is none other commandment greater than these.
____

Remember the coin that was stamped with Caesar's image on it? Man was created in the image of God. We have God's image stamped on us. If we are to render unto God the things that are God's, that surely involves the whole person. It's one thing to read, teach, and debate the Words of God. But it's an entirely different thing to truly understand these words to the point that we actually desire what God wants. This involves the entire person. And I believe that this is what it means to render the things that are God's unto God.
