= Unity of the Spirit

Understanding the Unity of the Spirit in light of the New Creation.

== The Worthy Life

* The Focus: Make every effort to preserve the unity of the Spirit!

* The Words:

** Endeavoring -> making every effort: This is the same word as in 2 Tim 2:15.
** Keep -> Guarding: this is a parallel with Gen 2:

* The Question: Does it take effort?

Eph 4:3 is just as important as 2 Tim 2:15. Can we preserve something we don’t understand?

'''

Look at unity of spirit in two groups:

1. Body, spirit, hope - the new anthropos God is  creating
2. Lord, faith, baptism - related to put off and put on, faith in the Head of the Body

Finally, one God and Father above all.

'''

Thinking of the two major sections, the verses following the Unity of the Spirit can actually be looked at within this light:

1. Building the body: Eph 4:7-16
2. Fruit of the Spirit: Eph 4:8-6:9

The gifts God gives are given with the purpose of building up the Body. The Fruit of the Spirit is a result of seeing Christ as Master and Head, putting off the old while putting on the new.

== The New Anthropology

The New Person: The Last Adam, The Head of All, the Husband.
We are using "anthropos" here in the sense of one person standing for everyone related to that person. There are really only two people central to understanding the Bible. Associated with these two are two anthropologies.

We will find phrases like the "old man" used in Romans (Rom 6:6) or "natural man" used in Corinthians (1 Cor 2:14). We are introduced to the "second person" (Anthropos) in 1 Cor 15:47, but that is in direct reference to the "Lord from heaven." It is only in Ephesians that we gain insights into the deep Mystery of this New Person.

'''

Instead of thinking about space and time, we need to think about purpose. Redemption. The transition from old to new.

How do we think about Ephesians:
- Middle wall broken down?
- hidden plan to fill time after Israel rejected?
- revelation about a new heavenly sphere?

These don’t capture the full magnitude. How about the very genesis of the new creation? The basis for all of the new creation in Christ?

'''

Keywords describing Ephesians:

- mystery
- far above all heavens
- before foundation
- purpose
- person

The purpose of the new person!

'''

The unity of the spirit has to be understood in light of the new person created in Ephesians. Ephesians is the genesis of the new creation. The new creation cuts across all layers of heaven and earth. We can’t confine it to one.

'''

Fruit of Spirit is used in KJV.

Look at the unity of the spirit in the light of how Ephesians defines it. Each aspect is defined within the book.

Understand Ephesians from the horizontal view of God’s purpose. The old vs the new. The Genesis of the New. This is a different way to understand things than just thinking about earth vs heaven vs far above all. The unity found in Ephesians exists only in the new, but we can tap into it during our lives now.

'''

Ephesians 1:10 shows how the Mystery brings unity across heaven and earth. It illustrates how the future purposes of God depend on this. Eph 2 talks about present time in heaven and ages to come. Eph 1 talks about distant past. Before the foundation.

Time and space are not the only way to slice it. We need to consider the purpose at work.

Structure:

- unity of Spirit
- Gifts of Grace
- Fruit of Light

What does the new creation (anthropos) look like? We can answer with a more abstract look a structure or a more concrete experience of fruit. How do we “see” the Body of Christ today?

== Created in Christ

Thesis: Ephesians is the Genesis for the New Person. We get a glimpse into God’s purpose with Christ as the last Adam unlike any other place in scripture.

Created in Christ (what's done, creation):

- One Body
- One Spirit
- One Hope

'''

Ephesians is describing the creation of the body of the new person, the last Adam. The called of the new creation are all found in one person, Christ. He is all and in all. The far above all might be thought of as the eden of the new creation.

We’re learning about this last Adam in Ephesians at a level never before revealed. His body is composed of called believers, and He is the head. All callings and hopes find their origin in Him.

'''

Comparing the two Adams:

- 1 Cor 15
- Creation in Eph
- Body given life by the Spirit
- Filling the earth in Gen vs filling all things in Eph 4:10
- Given a purpose: keep the garden vs keep the unity of the Spirit
- Being like the last Adam vs being a part of the last Adam

'''

Examine all elements of Unity of Spirit within this chapter (+ highlights from 4 & 5).

Can 1 + 1 = 1? Our understanding of one is very important when we come to the body of Christ.

== Putting on Christ

Putting on Christ (what we do, submission):

- One Lord
- One Faith
- One Baptism

'''

Baptism in Eph 4 should be studied in light of the phrase "put off ... put on". See Paul's teaching on putting on Christ in Gal, Col, Rom.

Keeping the Unity of the Spirit (and making every effort to do so) is "walking worthy". Paul gives us a lot of practical advice around what it looks like to keep this unity through the list of "put off" and "put on." In fact, if we we are struggling with an area in our life, we should focus on "putting on" the behavior of the new person in that area trough faith in our Lord and Head.

== Making Every Effort

Making every effort: Paul's advice

'''

A worthy life is summed up in 2 verses in Eph 4:2-3:

Ephesians 4:2-3 (KJV) 2 With all lowliness and meekness, with longsuffering, forbearing one another in love; 3 Endeavouring to keep the unity of the Spirit in the bond of peace.

This sums up the entire chapter. And in some ways the will of God in Ephesians.

Building and growing is how we get from the Unity of the Spirit to the Fruit of the Spirit.

'''

Recall Israel in the wilderness before entering the promised land. The work they had to do on this journey then was believing and not complaining! God would not take an unbelieving, complaining army into battle. It may be tempeting to focus on the future plans God has, but He has work for us to do right here and right now.

This perspective brings new light on Paul’s comments in Philippians: “I can do all things through Christ who strengthens me!” These "all things" aren't the things that we want selfishly, they are the good works God has created us to do.

'''

We get hints at how God is creating the body of Christ. But we get many verses describing what this body looks like through fruit.
