= Unity of the Spirit

Paul opens the fourth chapter of Ephesians by urging us to "walk worthy" of the calling we have received from God.
This is a critical turning point in the book of Ephesians.
Paul just spent three chapters explaining what God has done for us in Christ.
That's what the calling is based on.
But now he shifts focus to explain what our response should be to this calling.

The Unity of the Spirit of Ephesians 4 is central to this worthy walk.
And it is fundamentally all about Oneness.
This oneness is formed from six individual elements that are all under One God and Father.
One Body.
One Spirit.
One Hope.
One Lord.
One Faith.
One Baptism.

These words are not independent or disconnected.
Together, they form a connected whole that describes the purpose of God as revealed in Ephesians.
So to understand the Unity of the Spirit, we must understand the theme of the book.
And Paul wants us to go beyond just understanding.
We are to endeavor to "keep" or "guard" this unity.
This isn't some light duty hobby.
The New English Translation reads "making every effort to keep the unity of the Spirit".
It is the very work of God's calling on our lives.

What is the theme of Ephesians?
Reading through this book, we'll soon discover that there is a tremendous amount going on.
We read about:

- "Before the foundation of the world" - the fact that in distant time past we were chosen in Christ.
- "Ages to come" - the fact that in the future, God is going to show the exceeding riches of His grace toward us in Christ.
- "The Fellowship of the Mystery" - the revelation of secrets about the unsearchable riches of Christ.
- "Far above all heavens" - the fact that Christ ascended up far above all heavens as part of His work in the heavenly realm.

And the list could go on!
It is all to easy for us to focus on these facts of time past, distant future, mysteries, or heavens far above all heavens and miss the common thread.
What do all these points have in common?
Or maybe we should ask, who do all these points have in common?
The person of Christ.
To be even more specific, the new person that God is creating in Christ.

== The New Person

Our thesis then is that the theme of Ephesians is in fact this new person in Christ.
It is the very revelation of this person at a level never before known.
Ephesians is like the Genesis for the new creation.
Here we get a glimpse into God’s purpose with Christ unlike any other place in Scripture.

When we look at Ephesians in this light, we begin to see how the first half of the book (chapters 1-3) are focused primarily on the creation of this new person.
Creation is bringing something into existence.
This is where God does the work.

____
For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.
[Eph 2:10 KJV]
____

The second half of the book (chapters 4-6), is focused primarily on identification with this new person.
Identification is a big theological word used to describe a linking or sense of identity that we share with someone or something else.
Yes, identification must be through faith.
But identification is also experience.
Identification is our response to the work that God has done for us.

____
And that ye put on the new man, which after God is created in righteousness and true holiness.
[Eph 4:24 KJV]
____

If we can speak of a new person, there must be some previous person against which we are comparing.
This first person is, of course, Adam.
In comparison to this, Paul calls Christ the "last Adam".

The word for "person" in the Greek is the word "anthropos".
While this is often translated as "man", it is in fact the word for "human being", whether male or female.
It is the word we get anthropology from.
Anthropology is not the study of only men.
It's the study of human beings, both male and female, along with their behaviors and societies.

Adam and Christ each play an important role as the head of two lineages.
They represent and stand for everyone related to them.
In the case of Adam, this relationship is physical through flesh and blood.
In the case of Christ, this relationship is spiritual through faith.
The new person is not merely Christ as an individual, it is Christ together with those that are called out by God "in Him" through faith.
The called of the new creation are all found in one person, Christ.

== Created in Christ

The Unity of the Spirit must be understood in light of the new person being created in Ephesians.
Much like the book of Ephesians itself, we can examine this unity both from the perspective of creation and from the perspective of identification.
The new person, as created, has one body, one spirit, and one hope.
This person, as experienced through identification, has one Lord, one faith, and one baptism.

=== One Body

When we say the new person has "one body", we have to stop and ask, "what kind of body is this?"
This is because the same word for body in the original is used in several different senses.
For example, body can simply mean a flesh and blood natural body like we have and like Adam had.
Body can also be used to refer to the spiritual resurrection body of an individual in contrast to the natural body.
Christ had a resurrection body, and those that are resurrected will have a body like His.
Body can even be used to refer to "heavenly bodies" like stars or angels.

But Paul uses the word body in a different sense to describe a called out group of individuals.
This is what we mean when we say the "body of Christ."
This isn't His natural earthy body or His spiritual resurrection body as an individual.
This is the group of called out individuals that are all identified together with Him.

Only Paul uses "body" specifically in this sense.
And throughout his writings it appears only 17 times.
Let's review which books this appears in:

- Romans (1 time)
- Corinthians (3 times)
- Colossians (5 times)
- Ephesians (8 times)

As it turns out, every time Paul uses "body" in Ephesians, he is using it in this sense.
The "Body of Christ" is embedded within the theme of the book.
No other book uses the word in this way more frequently.

So naturally, when we come to "One Body" in the Unity of the Spirit, it makes sense that he is using it this way.
But if we stop at just this word, we miss one important word that is unique to the book of Ephesians.

Paul uses a very unique form of the word for "body" that is only found once in the entire Bible in Ephesians 3, where he writes:

____
“To be specific, that the Gentiles are fellow heirs and fellow members of the body, and fellow partakers of the promise in Christ Jesus through the gospel “
[Eph 3:6 NASB]
____

This word for body is translated as the phrase "fellow members of the body" in the NASB.
But it is actually just one word.
In the original, "fellow heirs", "fellow members", and "fellow partakers" are all formed by adding the same prefix "syn" to the base word.
This prefix is about union, togetherness, and companionship.
Some have translated it into the English as "joint".
So we could say "joint heirs", "joint body", and "joint partakers".

What is a joint body?
One perspective on this is that Paul is building on what he already stated in the chapter 2 about Jews and Gentiles.
Christ broke down the division between Jews and Gentiles. He made peace "that He might reconcile them both to God in one body through the cross".
The joint body could be a reference to this reconciliation.

But there is another way to look at this.
In chapter 3, Paul declares that "The Mystery" was made known to him by revelation.
He then goes on to explain this Mystery as the Nations together forming "joint heirs", "a joint body", and "joint partakers" of "His promise in Christ".
When Paul uses the word "Gentiles" here, he is using the word for "nations" that could be used to refer to any nation.
With the reconciliation complete in Chapter 2, here in Chapter 3 Paul is viewing all nations together on an equal playing field.
The "joint body" isn't so much about the nations as it is about the body of Christ itself.

Paul is shedding new light on the nature and makeup of the body of Christ.
To help us appreciate this, let's compare the body of Christ as the Last Adam with the body of the first Adam in Genesis.
One of the things that the Genesis creation account makes clear is that man was created in the image of God.

____
Then God said, "Let Us make man in Our image, according to Our likeness; let them have dominion over the fish of the sea, over the birds of the air, and over the cattle, over all the earth and over every creeping thing that creeps on the earth."
[Gen 1:26 NKJV]
____

What it means to be created in the image and likeness of God is certainly a very profound question.
But a simple common thread that cannot be ignored is the plurality of the statement.
Let "us" make man in "our image".
Let "them" have dominion.
God refers to Himself as plural, and he refers to man as plural.

Then just a little later down, we get an expansion on the plurality of mankind.

____
So God created man in his [own] image, in the image of God created he him; male and female created he them.
[Gen 1:27 KJV]
____

So "them" is male and female viewed together.
And "they" were created in the image or likeness of God.
We are getting a picture of the Godhead in what He created in Adam.
The male and female that God created in Adam is a reflection of something within the image of God Himself.
Perhaps part of the image and likeness that Adam shared with God is the special relationship he had with Eve.

Adam was created in the image of God, but the Last Adam, Christ, is the very image of the unseen God.
Is it not possible that the Body of Christ might also reflect this dichotomy we see in the body of the first Adam?

In the books of Paul that specifically make mention of the "body of Christ" in the corporate sense, Paul actually makes use of both a male and a female identity when referring to the members of the body.
He only uses each of these once, so we do have to pay close attention.
When writing to the Corinthians, he compares them to a female example of a "chaste" or "faithful" virgin.
But when writing to the Ephesians, he compares them to a "perfect man" or a "perfect husband".
This isn't the word for "anthropos" or human being, it is the word specifically for a male.

// TODO: Include clear references for this in Cor and Eph

Are these two different bodies or are they one body?
Male and female are most certainly not the same, but can they not be one at some level?
When Paul speaks of Christ and the church in Ephesians 5,
he refers right back to the example of the first Adam in Genesis.

____
For this reason a man shall leave his father and mother and be joined to his wife, and the two shall become one flesh.
[Eph 5:31 NKJV]
____

Ultimately, at some level, all those called in Christ must be One in Christ.
But according to the manifold wisdom of God, He has chosen to use different callings, aspects, and gifts within this One Body to accomplish His purpose of the ages.
This is certainly one of the great mysteries of the body of Christ.

=== One Spirit

What else beyond the body is required to make a complete living person?
A body in and of itself is not a living creature.
A body can be dead.
And a body can be alive.

There are some that would say a living person has a body, soul, and spirit.
In this view, a person is a trichotomy with three parts.
This thinking is supported by the ancient Greek view that the soul is the immortal, immaterial part of a person.
The soul continues in existence beyond death.
It is as if the soul is trapped inside the body until death.

If we come to Scripture with this assumption looking for verses to prove it, we will no doubt find them.
But if we come to Scripture with the goal of gaining a Scriptural understanding of the soul, a different perspective will emerge.

In the Hebrew mind, the soul is not a part of the person, it is the complete living person.
When body and spirit are brought together, a living soul is formed.
We see this clearly in the creation account of man.

____
And the LORD God formed man [of] the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.
[Gen 2:7 KJV]
____

To state this the other way, if we take the spirit away from the body, life cannot continue.
James explains it this way when illustrating how faith without works is dead.
____
For as the body without the spirit is dead, so faith without works is dead also.”
[Jas 2:26 KJV]
____

Adam required a spirit to become a living creature.
God breathed this spirit into Adam.
// TODO: do we want to examine any aspects beyond "breath" here from the Hebrew?
The new person in Christ is no different.
But the Spirit that makes this person alive is the very Spirit of God dwelling within us.

=== One Hope

God wouldn't create a new person without purpose.
And purpose is what brings us to "One Hope".
The word hope is a word that easily gets diluted when we use it outside of the Scriptural sense.
Often, when we say "hope", were speaking about our wishes that rest on little more than our own desires.

But hope in a Biblical sense is much different.
It is the expectation of something promised by God.
Hope rests solidly on the Word of God.
And when we hope for something, we do not yet have it or see it.
We look forward to it.
We expect it.
What, then, does "One Hope" mean for the New Person?

After God created Adam as male and female, the very next thing He did was bless them.
When God speaks blessing to Adam, He is giving them their hope, their purpose.

From Genesis 1:28, we can see this was a three-fold hope:

1. Filling the Earth
2. Subduing the Earth
3. Dominion over the animals

These words are strong words in the Hebrew.
Without plumbing the depths of their meaning, suffice it to say that they imply what is essentially a kingdom on the Earth.
And this kingdom would have been a good thing for the Earth.
To subdue is not to sabotage.
Dominion is not destruction.
To subdue and have dominion imply establishing order and government.

When we come to Ephesians, we see the same pairing of blessing and hope.
But this time, the blessing is all in Christ.
And the blessings are spiritual blessings in the heavens.
Once again, we find a three-fold hope in Christ that has Him:

1. Far above all dominion
2. With all things under his feet
3. Filling all things

Interestingly enough, the order here is reversed.
It starts with dominion over all and it ends with filling all things.

In Jewish families, the firstborn son receives a special blessing and inheritance from the father.
This is a tradition that can be traced far back into the Old Testament.
There are some that say God did this as a way to differentiate the nation of Israel from the practices of the pagan nations at the time.
Among the nations that practiced human sacrifice, the firstborn was often chosen.
So instead of Jewish families sacrificing their firstborn, they blessed the firstborn.

God's plan for filling, ordering, and governing all creation rests in Christ.
Christ is the firstborn of all creation.
And as God's firstborn Son, it is through Him that the blessing flows.
This is the hope of Christ.
This is the hope of the new person created in Christ.

== Identification with Christ

Much like Adam had a body, a spirit, and a hope, the new person in Christ has one body, one spirit, one hope.
While this perspective is certainly insightful, it is like describing someone from the outside without ever experiencing life as they do.
When we have been identified with the new person in Christ, we can say we have one Lord, one faith, one baptism.

=== One Lord

When we say the New Person has One Lord, we are defining a relationship.
The word Lord is the word for Master.
In the Greek this word implies ownership and authority.
If we call Christ Lord, we are at the same time putting ourselves in submission to His authority.

One of the titles commonly associated with Christ is King.
And He is the King of Kings.
But the title King is strangely absent from the book of Ephesians.
King is a title that is tied heavily to the earthly realm.
It's about kings and kingdoms on the earth.
The Kingdom of Heaven, even though heavenly in origin, is ultimately realized on earth.

What can we say about this title "Lord" or "Master"?
It expands beyond just the earth to include the heavens.
In Colossians we learn about Christ's special relationship to all creation.

____
He is the image of the invisible God, the firstborn over all creation. For by Him all things were created that are in heaven and that are on earth, visible and invisible, whether thrones or dominions or principalities or powers. All things were created through Him and for Him. And He is before all things, and in Him all things consist.
[Col 1:15-17 NKJV]
____

It was through Christ and for Christ that all things were created.
This includes the visible and the invisible, the earthly and the heavenly.
While Christian tradition and Christian creeds might say that it was the Father that created all things, it is the firm teaching of Scripture that all things were created  by Christ, through Christ, and for Christ.

When we acknowledge "One Lord", we’re acknowledging Christ’s authority as creator and Master.
But at the same time, we’re also learning about our own identity in Him.

____
And He is the head of the body, the church, who is the beginning, the firstborn from the dead, that in all things He may have the preeminence.
[Col 1:18 NKJV]
____

The Head of all principality and power, the One that will have preeminence in all things is also the Head of the Body.
In Ephesians, Paul identifies us as members of His body, of His flesh, and of His bones.
This relationship is about as close as it gets.
As part of His body, that puts us with Christ where He is.
His hope is our hope.
When we say “Lord”, this is what we should be thinking of.
This is where we find our Identity.

=== One Faith

How does faith relate to the creation in Christ?
When God creates something, is faith required?
Both faith and creation share something closely in common.
Neither are possible without the Word of God.

In the Gospel of John, it is the Word of God which made all things in the beginning.
This Word was Christ; the Word was made flesh in Him.
In the Genesis creation account, God speaks the creation into existence.

In the Psalms, David speaks of the magnitude of the creation of the Lord.
This creation covers the earth, the heavens, and the heavens of heavens.
It includes animals, people, and angels.
All of these were created at the command of God.

____
Let them praise the name of the LORD, For He commanded and they were created.
[Psa 148:5 NKJV]
____

When God speaks to create, is there any choice in the matter?
He commands the creation.
There is no faith involved on the part of those that were created.
Like Isaiah says "Shall the clay say to him who forms it, What are you making?"
We have about as much say in the matter of God creating us as we do in choosing our parents.

As the forerunner to the earthly ministry of Christ, John the Baptist proclaimed a message of repentance and baptism.
One day, some of the Pharisees and Sadducees came to his baptism.
Rather than baptize them, John asks them a question.

____
Therefore bear fruits worthy of repentance, and do not think to say to yourselves, 'We have Abraham as [our] father.' For I say to you that God is able to raise up children to Abraham from these stones.
[Mat 3:8-9 NKJV]
____

Why would John speak about God raising up children of Abraham from these stones?
What did these stones have in common with the Pharisees?
The Pharisees took pride in the fact that they were physical descendants of Abraham.
Of course, they had no real say in this matter.
They had no more control of their own birth than the stone did.

But when it came to the Words of God, these Pharisees were as deaf, blind, and hard as a stone.
John's ministry was about the fruits of repentance.
Fruit implies some response to the Word of God.
It requires faith.
There was no faith in these hearts.
Even rock hard stone can't resist God, but a hard heart is resistance towards God.

God could have spoken to those stones and created physical children of Abraham.
The children raised up from the stones would have been just as physically related to Abraham as the Pharisees were.
But this isn't the kind of creation God was looking for.
Flesh and blood does not inherit the Kingdom of Heaven.
God desires faith in the inside.
When the Word of God is combined with faith, a new kind of creature is made.

Paul brings faith and the new creation closely together in Ephesians chapter two:
____
For by grace you have been saved through faith, and that not of yourselves; [it is] the gift of God, not of works, lest anyone should boast. For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.
[Eph 2:8-10 NKJV]
____

This faith does not come out of us.
It isn't based upon our words or our ideas.
It is based solidly upon the Word and calling of God.
All we can do is receive or reject this wonderful gift.

The old person is a material creation; the new person is a faith creation.
The old person was created by the Word and command of God.
The new person is created by the Word only through faith.
No amount of religion, effort, or good works can turn the old creation into the new creation.
These are two fundamentally different types of creatures.

=== One Baptism

When we see the difference between the material creation in Adam and the faith creation in Christ, we at some point have to ask ourselves which one is our real identity?
We cannot have a solid sense of who we are until we answer that question.
Is our identity found in the old person and what we inherit by nature from Adam, or is it found in the new person and what we inherit by faith in Christ?

This question of identity is fundamental to the "One Baptism" of the Unity of the Spirit.
Some of you may come to this point already thinking, "of course there is only one baptism!".
But others may see this and think, "how can there possibly be only one?"
We don't have to look very far in Scripture or within Christianity to realize that baptism is both a complicated and controversial topic.

What we do have to keep in mind the theme of the book of Ephesians.
Our thesis is that this book is about the New Person being created in Christ Jesus.
When Paul says there is "One Baptism", he is speaking specifically about this new creation in Christ.

It's difficult to truly understand this "One Baptism" if we don't face the fact that there are multiple baptisms spoken of throughout Scripture.
In fact, there are at least three illustrated right within the life of Christ.

At the beginning of His earthly ministry, Christ was baptized by John in the Jordan River.
Water baptism has a history that goes far back into the Old Covenant priesthood.
When Moses ordained Aaron as the first High Priest, one part of the ceremony was baptism in water.

After Moses baptized Aaron in water, he anointed him with oil.
Oil in Scripture is symbolic of the Holy Spirit.
Anointing in oil was something of significance under the Old Covenant.
But under the New Covenant, there was a far more powerful and lasting anointing.
The anointing of the Holy Spirit.
After John baptized Jesus, the Holy Spirit was seen descending on Him like a dove.
The spirit baptism manifested itself in the life of Christ through the gifts of the Spirit.
These were the sign gifts promised as part of the New Covenant.
They were the signs and tools of a priest under the New Covenant.

But if we stop at the water baptism of the Old Covenant or the spirit baptism of the New Covenant, we have an incomplete picture of baptism.
After Christ was baptized by John and anointed in the Holy Spirit He spoke of a third baptism that was yet future.
"I have a baptism to be baptized with" He says in Luke 12.
And this weighed heavily on Him until it was accomplished.
He was anticipating the baptism that was accomplished at the cross.
The baptism of His death, burial, and resurrection.

Nearly all of Paul's teaching on baptism in Scripture is about this baptism into Christ.
As Paul says in Romans 6 "as many of us as were baptized into Christ Jesus were baptized into His death."
This isn't water baptism or spirit anointing.
This is identification with the death, burial, and resurrection of Christ.

Every calling and purpose of God within the new creation ultimately must have it's basis here.
Yes, the cross brings fulfillment to the Old Covenant in Christ.
And the cross enables the commissioning of the New Covenant with its Spirit anointing.
But the baptism achieved by Christ through the cross is absolutely fundamental to the creation of the new person in Christ.

There is a side of this identification that can only be done by Christ.
We are complete in Him and nothing can undo that.
But there is a side to identification that requires us to identify with Him.
There comes a point where if we have been baptized into Christ, we have to put on Christ, as Paul says in Galatians.

In Colossians 2, Paul lays out in detail the work of Christ for us on the Cross:

1. "In Him you were circumcised ... without hands"
2. "Buried with Him in Baptism"
3. "Raised with Him through Faith"

This is our completeness in Him.
It is out of our power to do or undo this.

But in Ephesians 4, we come to our response to this wonderful work of Christ.
Here we must:

1. "Put off the old person"
2. "Be renewed in the spirit of your mind"
3. "Put on the new person"

Keeping the Unity of the Spirit, and making every effort to do so, is putting on the new person in Christ.
Every good work we were created to do starts here.
We cannot experience the fruit of the Spirit if we do not put on the New Person.

== Walking towards Hope

In Ephesians, God has made known to us incredible things regarding the Mystery of His will.
This culminates when, as Paul states,

____
...in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; [even] in him:
[Ephesians 1:10]
____

The Unity of the Spirit looks forward in anticipation to this ultimate realization of the Mystery of God's will.
That's the ultimate hope, the destination.

But God cares as much about the journey as He does about the destination.
He doesn't just give us distant future hope.
He gives us work to do in the here and now.

Adam's ultimate purpose was one of dominion over the earth.
This is the hope God proclaimed as he blessed them in Genesis chapter 1.
But in chapter 2, the day to day work that God gave Adam to do was to dress and keep the garden in Eden.
He had an ultimate hope and purpose, but he also had immediate work to do.
No doubt the purpose and work for Adam were closely related.
One has to wonder if the situation between Eve and the serpent that ultimately led to the fall was due to some neglect in this day to day work on the part of Adam.

God wants us to keep our eye on the future hope and prize.
We do this each day by walking in the good works God has created us for.
Making every effort to guard the Unity of the Spirit.
This is the will of God for our lives today.
One Body. One Spirit. One Hope. One Lord. One Faith. One Baptism.
One God and Father above all.
