= Unity of the Spirit

The Unity of the Spirit is all about One.
One Body.
One Spirit.
One Hope.
One Lord.
One Faith.
One Baptism.
One God and Father.

While these may seem like 6 very different and maybe even disconnected words, we should look at them as one connected whole.

Understanding the Unity of the Spirit in light of the New Creation in Ephesians.

What is the Unity of the Spirit?
Why would I care?
How can I understand it?

* The Words:
** Endeavoring -> making every effort: This is the same word as in 2 Tim 2:15.
** Keep -> Guarding: this is a parallel with keeping or guarding the garden in Gen 2.

Eph 4:3 is just as important as 2 Tim 2:15.
But we can't preserve something we don’t understand.

When reading a book, it's always wise to consider what major theme(s) shape the context of the book. If we are to properly understand the Fruit of the Spirit in Ephesians, we would do well to understand the theme of Ephesians. Some things that may stand out include:

- "Before the foundation of the world" (Eph 1:4) - This is time past. We learn in Ephesians that we were chosen in Christ before the foundation of the world.
- "Ages to come" (Eph 2:7) - This is time future. We learn in Ephesians that God is going to show the exceeding riches of His grace in the ages to come.
- "Lower parts of the earth" (Eph 4:9)
- "Far above all heavens" (Eph 4:10)
- "Mystery" (Eph 3:9)

These are all interesting and unique sub themes discussed through Ephesians, but how can we determine the overall theme?
Is there a common thread that keeps appearing throughout the book?
Ephesians 1:10 shows how the Mystery brings unity across heaven and earth. It illustrates how the future purposes of God depend on this. Eph 2 talks about present time in heaven and ages to come. Eph 1 talks about distant past. Before the foundation.
What do all these points have in common? Or maybe we should ask, who is the common point?

Christ is the answer! Instead of focusing on space and time, we need to think about a person and a purpose. The purpose of the new person!

[Eph 2:10 KJV] 10 For we are his workmanship, created[G2936] in Christ Jesus unto good works, which God hath before ordained that we should walk in them.

[Eph 4:24 KJV] 24 And that ye put on the new man, which after God is created[G2936] in righteousness and true holiness.



== The New Person

Creation vs identification. Two aspects of unity of the spirit we will consider.
All things created by or through Christ. Which creation is this referring to? The created word is a key word in Ephesians.

The New Person. The New Creation. The Last Adam, The Head of All, the Husband.
We are using "anthropos" here in the sense of one person standing for everyone related to that person. There are really only two people central to understanding the Bible. Associated with these two are two anthropologies.

We will find phrases like the "old man" used in Romans (Rom 6:6) or "natural man" used in Corinthians (1 Cor 2:14). We are introduced to the "second person" (Anthropos) in 1 Cor 15:47, but that is in direct reference to the "Lord from heaven." It is only in Ephesians that we gain insights into the deep Mystery of this New Person.

The unity of the spirit has to be understood in light of the new person created in Ephesians. Ephesians is the genesis of the new creation. The new creation cuts across all layers of heaven and earth. We can’t confine it to one. The Unity of the Spirit only exists within the New Creation in Christ.

Look at unity of spirit in two groups:

1. Creation
2. Identity

1. Body, spirit, hope - the New Anthropos God creates
2. Lord, faith, baptism - the identity we assume within this creation

Finally, one God and Father above all.

The gifts God gives are given with the purpose of building up the Body. The Fruit of the Spirit is a result of seeing Christ as Master and Head, putting off the old while putting on the new.


== Created in Christ

Ephesians is describing the creation of the body of the new person, the last Adam.
The called of the new creation are all found in one person, Christ.
He is all and in all.
Ephesians is the Genesis for the New Person. Here we get a glimpse into God’s purpose with Christ as the last Adam unlike any other place in Scripture.
The far above all might be thought of as the Eden of the new creation.
We’re learning about this last Adam in Ephesians at a level never before revealed.
His body is composed of called believers, and He is the head.
All callings and hopes find their origin in Him.

=== One Body

The word body can be used to refer to the body of an individual or to a group of individuals viewed together as a corporate body.
To make things even more interesting, individuals can have multiple types of bodies.
In Corinthians, Paul speaks of both a "natural" body and a "spiritual" body when referring to the body of an individual.
So when we say the phrase "the body of Christ", we could actually mean three different things:

1. The natural body of Jesus of Nazareth
2. The resurrection body of Christ
3. The corporate body of believers known as the "Body of Christ"

To appreciate the meaning of "One Body", we have to understand the context.

It is helpful to review all of Paul's teaching on body as a corporate group:

- Romans (1x)
- Corinthians (3x?)
- Colossians (5x)
- Ephesians (8x)

Every time Paul uses "body" in Ephesians, he uses it in the corporate sense.
In other words, he is referring to the group known as the "Body of Christ".
But there is something unique about the Greek word Paul uses in Ephesians that isn't found elsewhere.

In Eph 3:6, Paul uses a unique form of the word "body" that might be best understood as meaning "joint body".

The creation of man in the image of God.

The engaged husband and virgin in Christ.

Can 1 + 1 = One?

=== One Spirit

What is it that makes a person a complete living person?
If we just have a lifeless body, we know that that alone cannot constitute a complete person.
But what else does it take?

There are some that would say a person is composed of body, soul, and spirit.
In other words, a person is a trichotomy formed of these three parts.
This thinking is supported by the ancient Greek view that the soul is the immortal, immaterial part of a person.
In this view, the soul continues in existence beyond death.
In fact, the soul was the "real you" trapped inside a body until death.

If we come to Scripture with this assumption looking for verses that support it, we will find some.
But if we come to Scripture with the goal of gaining a Scriptural definition of the soul, we will gain a new perspective.

In the Hebrew mind, the soul is not a part of the person, it is the complete living person.
When body and spirit are brought together, a living soul is formed.
We see this clearly in the creation account of man.

____
“And the LORD God formed man [of] the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.” [Gen 2:7 KJV]
____

If we separate the spirit from the body, life cannot continue.

____
“For as the body without the spirit is dead, so faith without works is dead also.” [Jas 2:26 KJV]
____

=== One Hope

The word hope is a word that easily gets diluted when we use it outside of the Scriptural sense.
We might say that we "hope" it doesn't rain on Saturday.
Or I "hope" I can get one of those shiny new one thousand dollar smartphones when it's released.
But these hopes are resting on nothing more than our own wishes and desires.

Hope in a Biblical sense is much different.
It is the expectation of something promised by God.
It rests solidly on the Word of God.
And we hope for something, we do not yet have it or see it.
We look forward to it.
We expect it.
What, then, does hope mean for the New Person?

Let's think back to Adam.
After God created man as male and female, He blessed them.
When God speaks blessing to Adam, He is giving them their hope.
God would not create something lacking purpose.
From Genesis 1:28, we can see this was a three-fold hope:

1. Filling the earth
2. Subduing the earth
3. Dominion over the animals

These words are strong words in the Hebrew.
Without plumbing the depths of their meaning, suffice it to say that they imply what is essentially a kingdom on the earth.
And this kingdom would have been a good thing for the Earth.
To subdue is not to sabotage.
Dominion is not destruction.
To subdue and have dominion imply establishing order and government.

When we come to Ephesians chapter 1, we see the same pairing of blessing and hope.
Christ filling all things and being head over all things.

1. Far above all dominion
2. Put all things under his feet
3. Filling all things

Interestingly enough, the order here is reversed.
God's plan for filling, ordering, and governing all creation--the entire universe and whatever else that may include--rests in Christ.
This is the hope of Christ.
This is the hope of the New Person in Christ.

== Identity in Christ

This is where we assume our identity as part of this New Creation.
We can say, the New Person has:

- One Lord
- One Faith
- One Baptism

When we "put on Christ", we can say this about ourselves.

=== One Lord

When we say the New Person has One Lord, we are defining a relationship.
The word Lord is the word for Master.
In the Greek this word implies ownership and authority.

One of the titles most commonly associated with Christ in this capacity is King.
And He is, of course, the King of Kings.
But the title King is strangely absent from the book of Ephesians.
King is a title that is tied heavily to the earthly realm.
It's about kings and kingdoms on the earth.
The Kingdom of Heaven, even though heavenly in origin, is ultimately realized on earth.

But what can we say about this title "Lord" or "Master"?
It expands beyond just the earth to include the heavens.
In Colossians we learn about Christ's special relationship to all creation.

____
[Col 1:15-17 NKJV] He is the image of the invisible God, the firstborn over all creation. For by Him all things were created that are in heaven and that are on earth, visible and invisible, whether thrones or dominions or principalities or powers. All things were created through Him and for Him. And He is before all things, and in Him all things consist.
____

It was through Christ and for Christ that all things were created.
This includes the visible and the invisible, the earthly and the heavenly.
While Christian tradition and Christian creeds might say that it was the Father that created all things, it is the firm teaching of Scripture that all things were created  by, through, and for Christ.

When we acknowledge "One Lord", we’re acknowledging Christ’s authority as Lord.
But at the same time, we’re also learning about our own identity in Him.

____
[Col 1:18 NKJV] 18 And He is the head of the body, the church, who is the beginning, the firstborn from the dead, that in all things He may have the preeminence.
____

The Head of all principality and power, the One that will have preeminence in all things is also the Head of the Body.
In Ephesians, Paul identifies Christ as the Head over all things to the Church.
And as the Lord who has ascended far above all Heavens, what is under His feet?
All things are under His feet.
If Christ is the Head and He is over the Church, and if all things are under His feet, where does that put us?
The body is below the head and above the stuff under the feet.
We are members of His flesh and His bones.
His hope is our hope.
When we say “Lord”, this is what we should be thinking of.
This is where we find our Identity.

=== One Faith

When God creates something, is faith required?
How does faith relate to creation?
Both faith and creation share something closely in common.
Neither are possible without the Word of God.

In the Gospel of John, it is the Word of God which made all things in the beginning (John 1:1).
This Word was Christ; the Word was made flesh in Him.
In the Genesis creation account, God speaks the creation into existence.

In the Psalms, David speaks of the magnitude of the creation of the Lord.
This creation covers the earth, the heavens, and the heavens of heavens.
It includes animals, people, and angels.
All of these were created at the command of God.

____
[Psa 148:5 NKJV] 5 Let them praise the name of the LORD, For He commanded and they were created.
____

When God speaks to create, is there any choice in the matter?
He commands the creation.
There is no faith involved on the part of those that were created.
It's like Isaiah says "Shall the clay say to him who forms it, What are you making?"
[Isa 45:9 NKJV].
We have about as much say in the matter of God creating us as we do in choosing our parents.

Notice how praising God is an admonition, not a command.
God gave creation the ability to praise Him, but He does not force it to praise Him.

As the forerunner to the earthly ministry of Christ, John the Baptist was proclaiming a message of repentance and baptism.
One day, some of the Pharisees and Sadducees came to his baptism.

____
[Mat 3:7-9 NKJV] 7 Brood of vipers! Who warned you to flee from the wrath to come? Therefore bear fruits worthy of repentance, and do not think to say to yourselves, 'We have Abraham as [our] father.' For I say to you that God is able to raise up children to Abraham from these stones.
____

John certainly had a way with words.
Why would He speak about God raising up children of Abraham from these stones?
What did these stones have in common with the Pharisees?
They were certainly both part of God's creation.
But the Pharisees took pride in the fact that they were physical descendants of Abraham.
Of course, they had no real say in this matter.
They had no more control of their own birth than the stone did.

But when it came to the Words of God, these Pharisees were as deaf, blind, and hard as a stone.
John's ministry was about the fruits of repentance.
Fruit implies some response to the Word of God.
It requires faith.
There was no faith in these hearts.
Even rock hard stone can't resist God, but a hard heart is resistance towards God.

God could have spoken to those stones and created a physical descendant of Abraham.
The children raised up from the stones could be just as physically related to Abraham as the Pharisees were.
But this isn't what God was after.
Flesh and blood does not inherit the Kingdom of Heaven.
God desires faith in the inside.
When the Word of God is combined with faith, a new kind of creation is made.

Paul brings faith and creation closely together in Ephesians chapter two:
____
[Eph 2:8-10 NKJV] 8 For by grace you have been saved through faith, and that not of yourselves; [it is] the gift of God, 9 not of works, lest anyone should boast. 10 For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.
____

This faith does not come out of us.
It isn't based upon our words or our ideas.
It is based solidly upon the Word and calling of God.
All we can do is receive or reject this wonderful gift.

The old person is a material creation; the new person is a faith creation.
The old person was created by the Word and command of God.
The new person is created by the Word only through faith.

=== One Baptism

Some may come to this part of Unity of the Spirit and think, "of course there is only one!".
Others may see this and think, "how can there possibly be only one?"
How are we going to get to the bottom of this without some monumental study?
One of the things that will help us narrow this down considerably is remembering the theme of Ephesians.
Paul is saying that for the new person in Christ, there is One Baptism.

1. Water Washing Baptism - John's baptism
2. Spirit Anointing Baptism - The Father's anointing
3. The Cross Baptism - as symbol of baptism into Death, Burial, Resurrection

We could perhaps more accurately order this as water, cross, spirit.
The cross must be central in any discussion of baptism.
I don't think anyone would argue that water can replace or accomplish what was done on the cross.
Spirit anointing must follow faith in the cross.

This baptism is at the very center of the work of in Christ Jesus.
And it is intimately associated with His work on the Cross.
There is an aspect of this only Christ can do.
But there is also an aspect we share in.
And it is central to the identity of a New Person in Christ.

To appreciate the cross fully, we need to get an appreciation for identification.
Paul illustrates this with a baptism from a period very early in the history of Israel.
Baptized into Moses.

The work of Christ on the Cross (Col 2:11-12):

1. "In Him you were circumcised ... without hands"
2. "Buried with Him in Baptism"
3. "Raised with Him through Faith"

The good works we were created to do (Eph 4:22-24):

1. "Put off the old person"
2. "Be renewed in the spirit of your mind"
3. "Put on the new person"

This new person was created in righteousness.

Keeping the Unity of the Spirit (and making every effort to do so) is "walking worthy".
Paul gives us a lot of practical advice around what it looks like to keep this unity through the list of "put off" and "put on." In fact, if we we are struggling with an area in our life, we should focus on "putting on" the behavior of the new person in that area trough faith in our Lord and Head.
I have though about this considerably and studied it for a long time.
Ultimately, I have concluded this is a good work.

Illustration of put on Christ.


== Walking towards our Hope

Is it about the journey or the destination.
Both!

In Ephesians, God has made know to us incredible things.
The Mystery of His will.

____
Ephesians 1:10 (KJV) 10 That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; [even] in him:
____

The Unity of the Spirit is about the Mystery of God's will.
Everything in Christ has a purpose and will be brought together into the overall purpose in Christ. The unity of the spirit looks forward to this in anticipation.

That's the destination.
But God cares equally about the journey.

'''

I really like the example of walking through a country as a stranger towards a promised land in Christ.
This is how Paul summarizes our occupation.
Unity of the Faith is Keeping or Guarding the Unity of the Spirit.
Guarding the Unity of the Spirit means we don't add to it or subtract from it.
Making every effort: Paul's advice

'''
Adam had a hope of dominion, but he also had an immediate task of guarding the garden.
Did he take is eye off the ball?
Maybe he was dreaming about dominion and forgot to guard the garden.
We don't know.
But I do know it would be all too easy for us to do the same.

'''

A worthy walk is summed up in 2 verses in Eph 4:2-3:

Ephesians 4:2-3 (KJV) 2 With all lowliness and meekness, with longsuffering, forbearing one another in love; 3 Endeavouring to keep the unity of the Spirit in the bond of peace.

This sums up the entire chapter. It is the will of God.
It is how we are to walk towards our Hope.

Building and growing is how we get from the Unity of the Spirit to the Fruit of the Spirit.

'''

Recall Israel in the wilderness before entering the promised land. The work they had to do on this journey then was believing and not complaining! God would not take an unbelieving, complaining army into battle. It may be tempting to focus on the future plans God has, but He has work for us to do right here and right now.

This perspective brings new light on Paul’s comments in Philippians: “I can do all things through Christ who strengthens me!” These "all things" aren't the things that we want selfishly, they are the good works God has created us to do.

'''

We get hints at how God is creating the body of Christ. But we get many verses describing what this body looks like through fruit.
