= Unity of the Spirit

Paul opens the fourth chapter of Ephesians by urging us to "walk worthy" of the calling we have received from God.
This is a critical turning point in the book of Ephesians.
Paul just spent three chapters explaining what God has done for us in Christ.
That's what the calling is based on.
But now he shifts focus to explain what our response should be to our calling in Christ.

The Unity of the Spirit (Eph 4:4-6) is central to this worthy walk.
It is fundamentally all about Oneness.
This oneness is formed from six individual elements that are all under One God and Father.
One Body.
One Spirit.
One Hope.
One Lord.
One Faith.
One Baptism.

These words should not be looked at as independent or disconnected.
Together, they form a connected whole that gives deep insight into theme of Ephesians.
So for us to understand or appreciate the Unity of the Spirit, we must grasp the theme of Ephesians.
And Paul wants us to go beyond understanding or appreciating: we are to endeavor to "keep" or "maintain" or "guard" this unity.
This isn't some light duty hobby.
The New English Translation reads "make every effort".
It is the very work of God's calling on our lives.

So what is the theme of Ephesians?
Reading through this book, we'll soon discover that there is a tremendous lot going on.
For example, we'll read about

- "Before the foundation of the world" (Eph 1:4) - We learn that in distant time past we were chosen in Christ.
- "Ages to come" (Eph 2:7) - We learn that in the future, God is going to show the exceeding riches of His grace toward us in Christ.
- "The Fellowship of the Mystery" (Eph 3:9) - We learn secrets about the unsearchable riches of Christ.
- "Far above all heavens" (Eph 4:10) - We learn that Christ ascended up far above all heavens as part of His work in the heavenly realm.

And the list could go on!
It is all to easy for us to focus on time past, distant future, mysteries, or heavens far above all heavens and miss the common thread.
What do all these points have in common?
Or maybe we should ask, who do all these points have in common?
The person of Christ.
To be even more specific, the new person that God is creating in Christ.

== The New Person

Our thesis then is that the theme of Ephesians is in fact this new person in Christ.
It is the very revelation of this person at a level never before known.
Ephesians is like the Genesis for the New Person.
Here we get a glimpse into God’s purpose with Christ unlike any other place in Scripture.

When we look at Ephesians in this light, we begin to see how the first half of the book (chapters 1-3) are focused primarily on the creation of this new person.
Creation is bringing something into existence.
This is where God does the work.

____
[Eph 2:10 KJV] 10 For we are his workmanship, created[G2936] in Christ Jesus unto good works, which God hath before ordained that we should walk in them.
____

The second half of the book (chapters 4-6), is focused primarily on identification with this new person.
Identification is a big theological word used to describe a linking or sense of identity that we share with someone or something else.
Yes, identification must be through faith.
But identification is also experience.
Identification is our response to the work that God has done for us.

____
[Eph 4:24 KJV] 24 And that ye put on the new man, which after God is created[G2936] in righteousness and true holiness.
____

If we can speak of a new person, there must be some previous person against which we are comparing.
This first person is, of course, Adam.
In comparison to this, Paul calls Christ the "last Adam".

The word for "person" in the Greek is the word "anthropos".
While this is often translated as "man", it is in fact the word for "human being", whether male or female.
It is the word we get anthropology from.
Anthropology is not the study of men, it's the study of humans along with their behaviors and societies.

Adam and Christ each play an important role as the head of two anthropologies.
They represent and stand for everyone related to them.
In the case of Adam, the relationship is physically by flesh and blood.
In the case of Christ, the relationship is spiritual by faith.
The new person is not Christ as an individual, it is Christ together with those that are called out by God "in Him" through faith.
The called of the new creation are all found in one person, Christ.

== Created in Christ

The Unity of the Spirit must be understood in light of the new person being created in Ephesians.
In fact, the Unity of the Spirit is all about this new person.
We can examine this unity both from the perspective of creation and from the experience of identification.
This person, when created, has one body, one spirit, and one hope.
This person, experienced personally, has one Lord, one faith, and one baptism.

=== One Body

When we say the new person has "one body", we have to stop and ask, what kind of body is this?
This is because the same word for body in the original is used in several different senses.
For example, body can simply mean a flesh and blood natural body like we have and like Adam had.
Body can also be used to refer to the spiritual resurrection body of an individual in contrast to the natural body (1 Cor 15:44).
Christ had a resurrection body, and those that are resurrected will have a resurrection body.
Body can even be used to refer to "heavenly bodies" like stars or angles.

But Paul uses the word body in a corporate sense to describe a called out group of individuals.
This is what we mean when we say the "body of Christ."
This isn't His natural earthy body or even His spiritual resurrection body as an individual.
This is a group of called out individuals that are all related to Christ.
It is helpful to review all of Paul's teaching on body as a corporate group:

- Romans (1x)
- Corinthians (3x)
- Colossians (5x)
- Ephesians (8x)

As it turns out, every time Paul uses "body" in Ephesians, he is using it in this sense.
The "Body of Christ" is embedded within the theme of the book.
So naturally, when we come to "One Body" in the Unity of the Spirit, it makes sense that it is referring to this.
But if we stop at just this word, we miss one important word that is unique to the book of Ephesians.

Paul uses a very unique form of the word for "body" that is only found once in the entire Bible.

____
“To be specific, that the Gentiles are fellow heirs and fellow members of the body, and fellow partakers of the promise in Christ Jesus through the gospel “
(Eph 3:6 NASB)
____

This word for body is translated as "fellow members of the body" in the NASB.
But it is actually just one word.
In the original, "fellow heirs", "fellow members", and "fellow partakers" are all formed by adding the same prefix "syn" to the base word.
This prefix is about union, togetherness, and companionship.
Some have translated it into the English as "joint".
So we would have "joint heirs", "joint body", and "joint partakers".

What is a joint body?
One perspective on this is that Paul is building on what he already said in the previous chapter about Jews and Gentiles.
Christ broke down the division between Jews and Gentiles, he made peace "that He might reconcile them both to God in one body through the cross" (Eph 2:16).
So the joint body could be a reference to the reconciliation of both Jews and Gentiles to God in one body.

But there is another way to look at this.
Just a few verses back, Paul declares that "The Mystery" was made known to him by revelation.
He then goes on to explain this Mystery as the Gentiles being "joint heirs", "a joint body", and "joint partakers" of "His promise in Christ".
When Paul uses the word "Gentiles", it is really the word for "Nations".
With the distinctions and divisions broken down, this is all nations together on a level playing field.
So all nations together are forming this "joint body" in Christ.
The "joint body" isn't so much about the nations as it is about the body of Christ.

Paul is shedding light on the nature and makeup of the body of Christ.
While this is new revelation, God does follow patterns in His creation.
Let's compare the body of Christ as the Last Adam with the body of the first Adam in Genesis.
One of the things that the Genesis creation account makes clear is that man was created in the image of God.

____
[Gen 1:26 NKJV] 26 Then God said, "Let Us make man in Our image, according to Our likeness; let them have dominion over the fish of the sea, over the birds of the air, and over the cattle, over all the earth and over every creeping thing that creeps on the earth."
____

What it means to be created in the image and likeness of God is certainly a very profound question.
But a simple common thread that cannot be ignored is the plurality of the statement.
Let "us" make man in "our image".
Let "them" have dominion.
God refers to Himself as plural and he refers to man as plural.

Then just a little later down, we get an expansion on the plurality of mankind.

____
[Gen 1:27 KJV] So God created man in his [own] image, in the image of God created he him; male and female created he them.
____

So the "them" is male and female viewed together.
And "they" were created in the image or likeness of God.
Could we be getting a hint way back here in Genesis that God himself has plurality within His image or likeness that corresponds to the male and female He created in Adam.
Because in one sense Adam and Eve are one in that they both came from one, but in another they are two.
Perhaps part of the image and likeness that Adam shared with God is the special relationship he had with Eve.
Adam was created in the image of God, but the Last Adam, Christ, is the very image of the unseen God.
Is it not possible that the Body of Christ Himself just might reflect the plurality we see in the body of the first Adam?

When Paul is writing to the both the Ephesians and the Corinthians, he refers to the churches as the "Body of Christ".
When writing to the Corinthians, he compares them to a "chaste virgin".
In other words, he associates their identity with a female illustration.
But when writing to the Ephesians, he compares them to a "perfect man" or a "perfect husband".
This isn't the word for anthropos or human being, it is the word for a full grown male.
And it can be used to refer to a husband.

Can 1 + 1 = One?

=== One Spirit

What is it that makes a person a complete living person?
If we just have a lifeless body, we know that that alone cannot constitute a complete person.
But what else does it take?

If we separate the spirit from the body, life cannot continue.

____
“For as the body without the spirit is dead, so faith without works is dead also.” [Jas 2:26 KJV]
____

There are some that would say a person is composed of body, soul, and spirit.
In other words, a person is a trichotomy formed of these three parts.
This thinking is supported by the ancient Greek view that the soul is the immortal, immaterial part of a person.
In this view, the soul continues in existence beyond death.
In fact, the soul was the "real you" trapped inside a body until death.

If we come to Scripture with this assumption looking for verses that support it, we will find some.
But if we come to Scripture with the goal of gaining a Scriptural definition of the soul, we will gain a new perspective.

In the Hebrew mind, the soul is not a part of the person, it is the complete living person.
When body and spirit are brought together, a living soul is formed.
We see this clearly in the creation account of man.

____
“And the LORD God formed man [of] the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.” [Gen 2:7 KJV]
____

The new person that God is creating in Christ has both a body and a spirit.

=== One Hope

The word hope is a word that easily gets diluted when we use it outside of the Scriptural sense.
We might say that we "hope" it doesn't rain on Saturday.
Or I "hope" I can get one of those shiny new one thousand dollar smartphones when it's released.
But these hopes are resting on nothing more than our own wishes and desires.

Hope in a Biblical sense is much different.
It is the expectation of something promised by God.
It rests solidly on the Word of God.
And we hope for something, we do not yet have it or see it.
We look forward to it.
We expect it.
What, then, does hope mean for the New Person?

Let's think back to Adam.
After God created man as male and female, He blessed them.
When God speaks blessing to Adam, He is giving them their hope.
God would not create something lacking purpose.
From Genesis 1:28, we can see this was a three-fold hope:

1. Filling the earth
2. Subduing the earth
3. Dominion over the animals

These words are strong words in the Hebrew.
Without plumbing the depths of their meaning, suffice it to say that they imply what is essentially a kingdom on the earth.
And this kingdom would have been a good thing for the Earth.
To subdue is not to sabotage.
Dominion is not destruction.
To subdue and have dominion imply establishing order and government.

When we come to Ephesians chapter 1, we see the same pairing of blessing and hope.
Christ filling all things and being head over all things.

1. Far above all dominion
2. Put all things under his feet
3. Filling all things

Interestingly enough, the order here is reversed.
God's plan for filling, ordering, and governing all creation--the entire universe and whatever else that may include--rests in Christ.
This is the hope of Christ.
This is the hope of the New Person in Christ.

== Identification in Christ

The New Person created in Christ has one body, one spirit, one hope.
This perspective is most certainly helpful, but it is like describing someone from the outside without ever experiencing life as they do.
When we have been identified with the New Person, we experience life as that person.
We can say we have one Lord, one faith, one baptism.

=== One Lord

When we say the New Person has One Lord, we are defining a relationship.
The word Lord is the word for Master.
In the Greek this word implies ownership and authority.
If we call Christ Lord, we are at the same time putting ourselves in submission to His authority.

One of the titles most commonly associated with Christ in this capacity is King.
And He is, of course, the King of Kings.
But the title King is strangely absent from the book of Ephesians.
King is a title that is tied heavily to the earthly realm.
It's about kings and kingdoms on the earth.
The Kingdom of Heaven, even though heavenly in origin, is ultimately realized on earth.

But what can we say about this title "Lord" or "Master"?
It expands beyond just the earth to include the heavens.
In Colossians we learn about Christ's special relationship to all creation.

____
[Col 1:15-17 NKJV] He is the image of the invisible God, the firstborn over all creation. For by Him all things were created that are in heaven and that are on earth, visible and invisible, whether thrones or dominions or principalities or powers. All things were created through Him and for Him. And He is before all things, and in Him all things consist.
____

It was through Christ and for Christ that all things were created.
This includes the visible and the invisible, the earthly and the heavenly.
While Christian tradition and Christian creeds might say that it was the Father that created all things, it is the firm teaching of Scripture that all things were created  by, through, and for Christ.

When we acknowledge "One Lord", we’re acknowledging Christ’s authority as Lord.
But at the same time, we’re also learning about our own identity in Him.

____
[Col 1:18 NKJV] 18 And He is the head of the body, the church, who is the beginning, the firstborn from the dead, that in all things He may have the preeminence.
____

The Head of all principality and power, the One that will have preeminence in all things is also the Head of the Body.
In Ephesians, Paul identifies Christ as the Head over all things to the Church.
And as the Lord who has ascended far above all Heavens, what is under His feet?
All things are under His feet.
If Christ is the Head and He is over the Church, and if all things are under His feet, where does that put us?
The body is below the head and above the stuff under the feet.
We are members of His flesh and His bones.
His hope is our hope.
When we say “Lord”, this is what we should be thinking of.
This is where we find our Identity.

=== One Faith

When God creates something, is faith required?
How does faith relate to creation?
Both faith and creation share something closely in common.
Neither are possible without the Word of God.

In the Gospel of John, it is the Word of God which made all things in the beginning (John 1:1).
This Word was Christ; the Word was made flesh in Him.
In the Genesis creation account, God speaks the creation into existence.

In the Psalms, David speaks of the magnitude of the creation of the Lord.
This creation covers the earth, the heavens, and the heavens of heavens.
It includes animals, people, and angels.
All of these were created at the command of God.

____
[Psa 148:5 NKJV] 5 Let them praise the name of the LORD, For He commanded and they were created.
____

When God speaks to create, is there any choice in the matter?
He commands the creation.
There is no faith involved on the part of those that were created.
It's like Isaiah says "Shall the clay say to him who forms it, What are you making?"
[Isa 45:9 NKJV].
We have about as much say in the matter of God creating us as we do in choosing our parents.

Notice how praising God is an admonition, not a command.
God gave creation the ability to praise Him, but He does not force it to praise Him.

As the forerunner to the earthly ministry of Christ, John the Baptist was proclaiming a message of repentance and baptism.
One day, some of the Pharisees and Sadducees came to his baptism.

____
[Mat 3:7-9 NKJV] 7 Brood of vipers! Who warned you to flee from the wrath to come? Therefore bear fruits worthy of repentance, and do not think to say to yourselves, 'We have Abraham as [our] father.' For I say to you that God is able to raise up children to Abraham from these stones.
____

John certainly had a way with words.
Why would He speak about God raising up children of Abraham from these stones?
What did these stones have in common with the Pharisees?
They were certainly both part of God's creation.
But the Pharisees took pride in the fact that they were physical descendants of Abraham.
Of course, they had no real say in this matter.
They had no more control of their own birth than the stone did.

But when it came to the Words of God, these Pharisees were as deaf, blind, and hard as a stone.
John's ministry was about the fruits of repentance.
Fruit implies some response to the Word of God.
It requires faith.
There was no faith in these hearts.
Even rock hard stone can't resist God, but a hard heart is resistance towards God.

God could have spoken to those stones and created a physical descendant of Abraham.
The children raised up from the stones could be just as physically related to Abraham as the Pharisees were.
But this isn't what God was after.
Flesh and blood does not inherit the Kingdom of Heaven.
God desires faith in the inside.
When the Word of God is combined with faith, a new kind of creation is made.

Paul brings faith and the new creation closely together in Ephesians chapter two:
____
[Eph 2:8-10 NKJV] 8 For by grace you have been saved through faith, and that not of yourselves; [it is] the gift of God, 9 not of works, lest anyone should boast. 10 For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.
____

This faith does not come out of us.
It isn't based upon our words or our ideas.
It is based solidly upon the Word and calling of God.
All we can do is receive or reject this wonderful gift.

The old person is a material creation; the new person is a faith creation.
The old person was created by the Word and command of God.
The new person is created by the Word only through faith.
No amount of religion, effort, or good works can turn the old creation into the new creation.
The new person is a fundamentally different type of creation.

=== One Baptism

When we realize there are these two different creations in Scripture, the material creation in Adam and the faith creation in Christ, we at some point have to ask the question: which one is the real me?
We cannot have a solid sense of identity until we answer that question.
Is our identity found in the old person and what we inherit by nature from Adam, or is it found in the new person and what we inherit by faith in Christ?

This question of identity is fundamental to the "One Baptism" of the Unity of the Spirit.
Some of you may come to this point already thinking, "of course there is only one baptism!".
But others may see this and think, "how can there possibly be only one?"
We don't have to look very in Scripture or within Christianity to realize that baptism is both a complicated and controversal topic.
But we do have to keep in mind the theme of the book of Ephesians.
Our thesis is that this book is about the New Person being created in Christ Jesus.
When Paul says there is "One Baptism", he is speaking specifically about this new creation in Christ.

One of the best ways to understand baptism is to look at the baptisms present within the life of Christ Himself.

1. Water - John The Baptist
2. Spirit - The Father's Anointing
3. Cross - Death, Burial, Resurrection

Water baptism has a history that goes far back into the Old Covenant priesthood.
In fact, when Moses ordained the first High Priest, one part of the ceremony was baptism in water.
Holy spirit anointing or baptism is something that was promised as part of the New Covenant.
John the Baptist looked forward to the One who would baptize with the Holy Spirit.

When Paul is writing to the Nations at large in Ephesians, he is addressing people that were strangers from the covenants of promise (Eph 2:12).
These people were outside of the blessings and hope spoken to Israel.
The good news in Ephesians isn't that we are being plugged into the blessings and hope of the New Covenant.
The good news is that we are being plugged right into the body of Christ Himself.
And it is this one baptism that takes us from our identity in Adam to our identity in Christ as a faith creation that Paul is speaking of.
It is identification with the death, burial, and resurrection of Christ.
Every calling and purpose of God within the New Creation ultimately must have it's basis here.
There is an aspect of this only Christ can do.
But there is also an aspect we share in.
And it is central to the identity of a New Person in Christ.

There is a side of this identification that is already done in Christ.
We are complete in Him and nothing can undo that.
But there is a side to identification that requires work and effort.

To appreciate the cross fully, we need to get an appreciation for identification.
Paul illustrates this with a baptism from a period very early in the history of Israel.

When the Israelites were delivered from slavery in Egypt, their hope was in the promised land.
They had been delivered from slavery.
The armies of Pharaoh could not reach them to capture them again.
But in their walk through the desert towards their hope, many of them had not "put on" their new identity in freedom.

The work of Christ on the Cross (Col 2:11-12):

1. "In Him you were circumcised ... without hands"
2. "Buried with Him in Baptism"
3. "Raised with Him through Faith"

The good works we were created to do (Eph 4:22-24):

1. "Put off the old person"
2. "Be renewed in the spirit of your mind"
3. "Put on the new person"

This new person was created in righteousness.

Keeping the Unity of the Spirit (and making every effort to do so) is "walking worthy".
Paul gives us a lot of practical advice around what it looks like to keep this unity through the list of "put off" and "put on." In fact, if we we are struggling with an area in our life, we should focus on "putting on" the behavior of the new person in that area trough faith in our Lord and Head.
I have though about this considerably and studied it for a long time.
Ultimately, I have concluded this is a good work.

== Walking towards Hope

In Ephesians, God has made know to us incredible things.
The Mystery of His will.

____
Ephesians 1:10 (KJV) 10 That in the dispensation of the fulness of times he might gather together in one all things in Christ, both which are in heaven, and which are on earth; [even] in him:
____

The Unity of the Spirit looks forward in anticipation to this ultimate realization of the Mystery of God's will.
That's the ultimate hope, the destination.

But God cares as much about the journey as He does about the destination.
We certainly don't make the Unity of the Spirit.
All we can do is guard or keep it.
Guarding the Unity of the Spirit means we don't add to it or subtract from it.
This is how Paul summarizes our occupation.
Making every effort: Paul's advice
This is the will of God for our lives today.
It is how we are to walk towards our Hope in anticipation.

Adam's hope was one of dominion over the earth.
This is the hope God proclaimed as he blessed them in Genesis chapter 1.
But in chapter 2, the day to day task that God assigned Adam was to dress and keep the garden in Eden.
He had an ultimate hope and purpose, but he also had immediate work to do.
Is it possible that the situation between Eve and the serpent that ultimately led to the fall was due to some neglect in guarding and protecting the garden on the part of Adam.

God wants us to keep our eye on the future prize.
We do this each day by walking in the good works God has for us.
By making every effort to guard the Unity of the Spirit.
One Body. One Spirit. One Hope. One Lord. One Faith. One Baptism.
One God and Father above all.
