= Unity of the Spirit

Understanding the Unity of the Spirit in light of the New Creation in Ephesians.

== The Worthy Life

* The Focus: Make every effort to preserve the unity of the Spirit!

* The Words:

** Endeavoring -> making every effort: This is the same word as in 2 Tim 2:15.
** Keep -> Guarding: this is a parallel with keeping or guarding the garden in Gen 2.

Eph 4:3 is just as important as 2 Tim 2:15. Can we preserve something we don’t understand?

* The Question: Does it take effort?

'''

Look at unity of spirit in two groups:

1. Body, spirit, hope - the New Anthropos God creates
2. Lord, faith, baptism - the identity we assume within this creation

Finally, one God and Father above all.

'''

Thinking of the two major sections, the verses following the Unity of the Spirit can actually be looked at within this light:

1. Building the body: Eph 4:7-16
2. Fruit of the Spirit: Eph 4:8-6:9

The gifts God gives are given with the purpose of building up the Body. The Fruit of the Spirit is a result of seeing Christ as Master and Head, putting off the old while putting on the new.

'''

Need to mention the structure of Ephesians balancing basis and application (doctrine and practice):

- unity of Spirit
- Gifts of Grace
- Fruit of Spirit

== The New Anthropology

When reading a book, it's always wise to consider what major theme(s) shape the context of the book. If we are to properly understand the Fruit of the Spirit in Ephesians, we would do well to understand the theme of Ephesians. Some things that may stand out include:

- "Before the foundation of the world" (Eph 1:4) - This is time past. We learn in Ephesians that we were chosen in Christ before the foundation of the world.
- "Ages to come" (Eph 2:7) - This is time future. We learn in Ephesians that God is going to show the exceeding riches of His grace in the ages to come.
- "Lower parts of the earth" (Eph 4:9)
- "Far above all heavens" (Eph 4:10)
- "Mystery" (Eph 3:9)

These are all interesting bits and pieces discussed through Ephesians, but how can we determine the overall theme?
Is there a common thread that keeps appearing throughout the book?
Ephesians 1:10 shows how the Mystery brings unity across heaven and earth. It illustrates how the future purposes of God depend on this. Eph 2 talks about present time in heaven and ages to come. Eph 1 talks about distant past. Before the foundation.
What do all these points have in common? Or maybe we should ask, who is the common point?
This is like the time when you were in Sunday school and didn't know the answer to the question. Jesus is the answer.

Christ is the answer! Instead of focusing on space and time, we need to think about a person and a purpose. The purpose of the new person!

[Eph 2:10 KJV] 10 For we are his workmanship, created[G2936] in Christ Jesus unto good works, which God hath before ordained that we should walk in them.

[Eph 4:24 KJV] 24 And that ye put on the new man, which after God is created[G2936] in righteousness and true holiness.

Creation vs identification. Two aspects of unity of the spirit we will consider.
All things created by or through Christ. Which creation is this referring to? The created word is a key word in Ephesians.

The New Person. The New Creation. The Last Adam, The Head of All, the Husband.
We are using "anthropos" here in the sense of one person standing for everyone related to that person. There are really only two people central to understanding the Bible. Associated with these two are two anthropologies.

We will find phrases like the "old man" used in Romans (Rom 6:6) or "natural man" used in Corinthians (1 Cor 2:14). We are introduced to the "second person" (Anthropos) in 1 Cor 15:47, but that is in direct reference to the "Lord from heaven." It is only in Ephesians that we gain insights into the deep Mystery of this New Person.

The unity of the spirit has to be understood in light of the new person created in Ephesians. Ephesians is the genesis of the new creation. The new creation cuts across all layers of heaven and earth. We can’t confine it to one. The Unity of the Spirit only exists within the New Creation in Christ.

== Created in Christ

Ephesians is describing the creation of the body of the new person, the last Adam.
The called of the new creation are all found in one person, Christ.
He is all and in all.
The far above all might be thought of as the Eden of the new creation.
We’re learning about this last Adam in Ephesians at a level never before revealed.
His body is composed of called believers, and He is the head.
All callings and hopes find their origin in Him.

=== One Body

The word body can be used to refer to the body of an individual or to a group of individuals viewed together as a corporate body.
To make things even more interesting, individuals can have multiple types of bodies.
In Corinthians, Paul speaks of both a "natural" body and a "spiritual" body when referring to the body of an individual.
So when we say the phrase "the body of Christ", we could actually mean three different things:

1. The natural body of Jesus of Nazareth
2. The resurrection body of Christ
3. The corporate body of believers known as the "Body of Christ"

To appreciate the meaning of "One Body", we have to understand the context.

It is helpful to review all of Paul's teaching on body as a corporate group:

- Romans (1x)
- Corinthians (3x?)
- Colossians (5x)
- Ephesians (8x)

Every time Paul uses "body" in Ephesians, he uses it in the corporate sense.
In other words, he is referring to the group known as the "Body of Christ".
But there is something unique about the Greek word Paul uses in Ephesians that isn't found elsewhere.

In Eph 3:6, Paul uses a unique form of the word "body" that might be best understood as meaning "joint body".

The creation of man in the image of God.

The engaged husband and virgin in Christ.

Can 1 + 1 = One?

=== One Spirit

The first triplet in the Unity of the Spirit focuses more on the nature and purpose of this New Person.
When body and spirit are brough togeher, a person is created.
Hope looks forward to the ultimate purpose of creation.
These words are statements about something that has been completed in creation not something that we strive to do through effort.

=== One Hope

The ultimate purpose for the New Person.
Adam filling the earth and having dominion.
Christ filling all things and being head over all things.


== Putting on Christ

This is where we assume our identity as part of this New Creation.
In other words, we "put on Christ".

- One Lord
- One Faith
- One Baptism

=== One Lord

This defines our relationship with Christ.
The word in the Greek implies ownership and control.
For a lot of people the title most commonly associated with Christ in this capacity is King.
How we see Christ also impacts how we see ourselves.
But “King” doesn’t even show up in Ephesians.

This is all encompassing of the roles of Christ. When we say “One Lord”, this is what we should be thinking of.
We’re learning about Christ’s Identity. At the same time we’re learning about our own identitiy.

=== One Faith

Is faith required for creation?

These two things are closely connected with a common thread.
Neither faith nor creation are possible without the Word of God.

In John, it is the Word of God through which all things were made.
In Genesis, it was the Spirit of God that moved on the face of the deep while God spoke creation into existence.
If God speaks to create,

Review the example of stones in Matthew 3:8-9.
It was easier for God to create physical children of Abraham from the stones than believers from these religious leaders.
The stone doesn't resist God.
A hard heart is resistance towards God.
Recall the stones Joshua had the men set aside as they crossed.

Paul brings faith and creation together in Ephesians chapter two:

___
[Eph 2:8-10 NKJV] 8 For by grace you have been saved through faith, and that not of yourselves; [it is] the gift of God, 9 not of works, lest anyone should boast. 10 For we are His workmanship, created in Christ Jesus for good works, which God prepared beforehand that we should walk in them.
___

This faith does not come out of us.


The New Person is a faith-creation.
This is fundamentally different in nature to a material creation.
Faith is a distinguishing difference between the old creation and the new creation
It is not merely God speaking something into existence.
It is based upon the Word of God and would not be possible without the Word of God.

=== One Baptism

The "One Baptism" of Ephesians isn't the baptism of a priest under either the Old Covenant or the New Covenant.
This baptism is at the very center of the work of in Christ Jesus.
And it is central to being a New Person in Christ.
And it is intimately associated with His work on the Cross.

Here are some parallels that may prove helpful.

- Death -> Burial -> Resurrection (The Work of Christ)
- The Cross -> The Grave -> The Garden (The Gospels) - The Passover
- The Cross -> Lower Parts of Earth -> Far above all Heavens (Ephesians) - The Principalities and Powers
- Circumcision of Christ -> Baptism of Christ -> Triumph of Christ (Colossians)
- Put off the old person -> Be Renewed -> Put on the new person (Ephesians)

Baptism in Eph 4 should be studied in light of the phrase "put off ... put on". See Paul's teaching on putting on Christ in Gal, Col, Rom.

Keeping the Unity of the Spirit (and making every effort to do so) is "walking worthy". Paul gives us a lot of practical advice around what it looks like to keep this unity through the list of "put off" and "put on." In fact, if we we are struggling with an area in our life, we should focus on "putting on" the behavior of the new person in that area trough faith in our Lord and Head.

== Making Every Effort

Thesis: Ephesians is the Genesis for the New Person. Here we get a glimpse into God’s purpose with Christ as the last Adam unlike any other place in Scripture.

This is how Paul summarizes our occupation.

Guarding the Unity of the Spirit means we don't add to it or subtract from it.

Unity of the Faith is Keeping or Guarding the Unity of the Spirit.

Making every effort: Paul's advice

'''

A worthy life is summed up in 2 verses in Eph 4:2-3:

Ephesians 4:2-3 (KJV) 2 With all lowliness and meekness, with longsuffering, forbearing one another in love; 3 Endeavouring to keep the unity of the Spirit in the bond of peace.

This sums up the entire chapter. And in some ways the will of God in Ephesians.

Building and growing is how we get from the Unity of the Spirit to the Fruit of the Spirit.

'''

Recall Israel in the wilderness before entering the promised land. The work they had to do on this journey then was believing and not complaining! God would not take an unbelieving, complaining army into battle. It may be tempeting to focus on the future plans God has, but He has work for us to do right here and right now.

This perspective brings new light on Paul’s comments in Philippians: “I can do all things through Christ who strengthens me!” These "all things" aren't the things that we want selfishly, they are the good works God has created us to do.

'''

We get hints at how God is creating the body of Christ. But we get many verses describing what this body looks like through fruit.
