Journal for 2018
================

Feb 4, 2018 - Good Works
------------------------

Col 1:9-10 NKJV
_______________
For this reason we also, since the day we heard it, do not cease to pray for
you, and to ask that you may be filled with the knowledge of His will in all
wisdom and spiritual understanding; that you may walk worthy of the Lord,
fully pleasing [Him], being fruitful in every good work and increasing in the
knowledge of God;
_______________

In this prayer of Paul for the Colossians, we learn that it is not possible to
_walk worthy_ in life or be fruitful in _good works_ without being filled with
the _knowledge of His will_.  This wisdom and spiritual understanding comes from
God, and it is received through His Word.

A worthy life of truly good works will always flow out from a true knowledge of
God's will.  While many things may outwardly appear to us as good or  even
worthy, it is ultimately God who is the judge of this.

Feb 12, 2018 - Good Works
-------------------------

Eph 2:10 ESV
____________
For we are his workmanship, created in Christ Jesus for good
works, which God prepared beforehand, that we should walk in them.
____________

We were created by God to do good works.  These works are not something we
strap on unwillinging or take up as a religious discipline.  They flow out from
the very nature of what God has created in us.

Eph 4:22-24 ESV
_______________
to put off your old self, which belongs to your former manner of life and is
corrupt through deceitful desires, and to be renewed in the spirit of your
minds, and to put on the new self, created after the likeness of God in true
righteousness and holiness.
_______________

The old self will never produce good works that are acceptable to God.  The new
self produces nothing but good works, because it was created in true
righteousness and holiness.  The path to good works must be for us to be
_renewed_ and to _put on_ that new self God has created.
