= Journal for 2018

== Feb 4, 2018 - Good Works

Col 1:9-10 NKJV
_______________
For this reason we also, since the day we heard it, do not cease to pray for
you, and to ask that you may be filled with the knowledge of His will in all
wisdom and spiritual understanding; that you may walk worthy of the Lord,
fully pleasing [Him], being fruitful in every good work and increasing in the
knowledge of God;
_______________

In this prayer of Paul for the Colossians, we learn that it is not possible to
_walk worthy_ in life or be fruitful in _good works_ without being filled with
the _knowledge of His will_.  This wisdom and spiritual understanding comes from
God, and it is received through His Word.

A worthy life of truly good works will always flow out from a true knowledge of
God's will.  While many things may outwardly appear to us as good or  even
worthy, it is ultimately God who is the judge of this.

== Feb 12, 2018 - Good Works

Eph 2:10 ESV
____________
For we are his workmanship, created in Christ Jesus for good
works, which God prepared beforehand, that we should walk in them.
____________

We were created by God to do good works.  These works are not something we
strap on unwillinging or take up as a religious discipline.  They flow out from
the very nature of what God has created in us.

Eph 4:22-24 ESV
_______________
to put off your old self, which belongs to your former manner of life and is
corrupt through deceitful desires, and to be renewed in the spirit of your
minds, and to put on the new self, created after the likeness of God in true
righteousness and holiness.
_______________

The old self will never produce good works that are acceptable to God.  The new
self produces nothing but good works, because it was created in true
righteousness and holiness.  The path to good works must be for us to be
_renewed_ and to _put on_ that new self God has created.

== Feb 24, 2018 - Good Works

The word _works_ (G2041, ἔργον) appears eight times throughout the book of Titus. In Scripture, the number eight is symbolic of new  beginnings in the Bible. How fitting this is for the theme of good works in Titus.

- Tit 1:16: They profess to know God, but in _works_ they deny Him, being abominable, disobedient, and disqualified for every good _work_.
- Tit 2:7: in all things showing yourself to be a pattern of good _works_; in doctrine showing integrity, reverence, incorruptibility,[fn]
- Tit 2:14: who gave Himself for us, that He might redeem us from every lawless deed and purify for Himself His own special people, zealous for good _works_.
- Tit 3:1: Remind them to be subject to rulers and authorities, to obey, to be ready for every good _work_,
- Tit 3:5: not by _works_ of righteousness which we have done, but according to His mercy He saved us, through the washing of regeneration and renewing of the Holy Spirit,
- Tit 3:8: This is a faithful saying, and these things I want you to affirm constantly, that those who have believed in God should be careful to maintain good _works_. These things are good and profitable to men.
- Tit 3:14: And let our people also learn to maintain good _works_, to meet urgent needs, that they may not be unfruitful.

Central to any good work is the fact that salvation is not by our good works but by the work of The Son (Tit 3:5).

== Mar 25, 2018 - Good Works

In Matthew chapter 5, we find the first instance of the phrase _good works_ in the New Testament.
It follows the Beatitudes in Christ's Sermon on the Mount:

Mat 5:16 KJV
____________
Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.
____________

These good works are intended to make "light so shine" before others.
The result of seeing this light brings glory to the Father.

When introducing this "light of the world" (v. 14), Christ speaks of the city "set on a hill" that cannot be hidden.
How fitting that this Sermon on the Mount was spoken from an elevated mountain setting.

These _good works_ are in stark contrast to the _works_ of the Pharisees:

Mat 23:5 KJV
____________
But all their works they do for to be seen of men ...
____________

In both cases, the works are seen by others.
But the heart motivation and end result of these religious works performed by the Pharisees was totally different.
_Good works_ will always shine light before others that brings glory to the Father.
