= Journal for 2019

== Jan 12, 2019 - Three Questions

Questions to think about as we study the Bible:

1. What are the last four books of the Old Testament?
2. What are the two types of creation in the Bible?
3. Is there really only one Body of Christ?

== Jan 14, 2019 - Two Questions

Thinking about how to "rightly divide" at the highest level:

1. Where does the Old Testament end? What are the last 4 books?
2. Where does the New Testament begin? What happens between the two?

The division between Old Covenant and New Covenant is not in fact a line.
It is a series of mysteries (secret, or hidden things).

Old Covenant | Mystery (With and Without Temple) | New Covenant

== Jan 23, 2019

We tend to think of the transition between Old Covenant and New Covenant as a line.
This is encouraged by the labels we have in our Bibles today.
But it's also the way the Disciples anticipated things unfolding before they understood the Mysteries of the Kingdom.

A really important question is: what is happening between the Old and the New?

- Messiah had died and resurrected, so Israel was no longer bound by law to that covennat
- This period is more like the time from Abraham -> Moses, than from Moses -> Jesus
- The wedding feast hasn't taken place: is the Kinsman considered married yet?
- Mysteries abound: Paul even says he was a "steward of Mysteries"