= Journal for 2019

== Jan 12, 2019 - Three Questions

Questions to think about as we study the Bible:

1. What are the last four books of the Old Testament?
2. What are the two types of creation in the Bible?
3. Is there really only one Body of Christ?

== Jan 14, 2019 - Two Questions

Thinking about how to "rightly divide" at the highest level:

1. Where does the Old Testament end? What are the last 4 books?
2. Where does the New Testament begin? What happens between the two?

The division between Old Covenant and New Covenant is not in fact a line.
It is a series of mysteries (secret, or hidden things).

Old Covenant | Mystery (With and Without Temple) | New Covenant

== Jan 23, 2019

We tend to think of the transition between Old Covenant and New Covenant as a line.
This is encouraged by the labels we have in our Bibles today.
But it's also the way the Disciples anticipated things unfolding before they understood the Mysteries of the Kingdom.

A really important question is: what is happening between the Old and the New?

- Messiah had died and resurrected, so Israel was no longer bound by law to that covennat
- This period is more like the time from Abraham -> Moses, than from Moses -> Jesus
- The wedding feast hasn't taken place: is the Kinsman considered married yet?
- Mysteries abound: Paul even says he was a "steward of Mysteries"

== Jan 24, 2019

Three ways to look at Testament:

- A Will (God's Will)
- A Covenant (Between God and Israel)
- A Marriage (between Man and Bride)

== Jan 27, 2019

Christ is compared to Prophet, Priest, and King. Who was the first for each role in the OT?

- Prophet: Moses (Acts 3:22)
- Priest: Aaron (See esp Hebrews)
- King: David? (after God's heart, not just the will of the people)

If we are to understand the New Covenant, we must understand the Old Covenant.
Perhaps the key to understanding when (or at least the significant events related to when) the New Covenant is established is clearly understanding the establishment of the Old Covenant.
We need to line up Passover, crossing the Red Sea, the mountain, the wilderness, and the promised land under both Covenants.

== Jan 28, 2019

Consider how the temple and tabernacle fit into the picture, especially during the Mystery period.

The Temple is currently destroyed. But where is the Tabernacle? What role does it play in the future?
Can The Mystery be looked at in the light of God dwelling ("tabernacling") among the nations today (Col 1:27)?