#!/bin/sh

# See http://koti.24.fi/jusalak/GreekNT/NTTexts.htm
texts="BP05FNL TR-PRSD ELZPRSD ANT-PRSD WH27PRSD"
mkdir -p texts
for t in $texts; do
    wget -nc http://koti.24.fi/jusalak/GreekNT/$t.ZIP -O texts/$t.ZIP
    mkdir -p texts/$t && unzip texts/$t.ZIP -d texts/$t
done
