#!/bin/sh

# Downloads and unzips Greek NT texts from
#   http://koti.24.fi/jusalak/GreekNT/NTTexts.htm
# A useful reference: 
#   http://koti.24.fi/jusalak/GreekNT/Layman'sGuideEnglish.PDF

texts="BP05FNL TR-PRSD ELZPRSD ANT-PRSD WH27PRSD"
mkdir -p texts
for t in $texts; do
    wget -nc http://koti.24.fi/jusalak/GreekNT/$t.ZIP -O texts/$t.ZIP
    mkdir -p texts/$t && unzip texts/$t.ZIP -d texts/$t
done
